### ISSUE TITLE
Mark events with source

### ISSUE THREAD

**Issue by Downchuck** [elastic/logstash-forwarder#100]
It'd be nice to have the ability to use the client SSL certificate's DN with logstash and/or lumberjack input to decorate the message data. This could be used for instance to direct logs to different elasticsearch indexes or simply to add a field verifying securely that a log message came from a particular machine or user.

**Comment by jordansissel** [comment]
+1 on the idea.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by https://github.com/elastic/filebeat/. If this is still an issue with filebeat, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
