### ISSUE TITLE
Lumberjack send tons of data at file rotation and locks the old file

### ISSUE THREAD

**Issue by matteopiva** [elastic/logstash-forwarder#101]
Hello,

I'm monitoring all my application's logs using Lumberjack.

At midnight the old log "application.stash" file moves to a new filename with date appended "application-2013.10.14.stash" and a new freshly created and zero sized file named "application.stash" is then spawned. After that, the old file is compressed (gzip).

The problem is the following: when my logfile rotates, Lumberjack starts sending data to Logstash server (hundreds of megabytes) and do it for some minutes.

It seems that Lumberjack starts collecting data from the beginning of the file watching to old already rotated files. It's quite strange.

I'm attaching you some midnight logs:
Oct 14 00:00:07 lumberjack[8950]: 2013/10/14 00:00:07.361479 Launching harvester on rotated file: /opt/applications/application1.stash
Oct 14 00:00:07 lumberjack[8950]: 2013/10/14 00:00:07.361575 Launching harvester on rotated file: /opt/applications/application2.stash
Oct 14 00:00:07 lumberjack[8950]: 2013/10/14 00:00:07.361608 Launching harvester on rotated file: /opt/applications/application3.stash
Oct 14 00:00:07 lumberjack[8950]: 2013/10/14 00:00:07.361646 Launching harvester on rotated file: /opt/applications/application4.stash
Oct 14 00:00:07 lumberjack[8950]: 2013/10/14 00:00:07.403121 Starting harvester: /opt/applications/application1.stash
Oct 14 00:00:07 lumberjack[8950]: 2013/10/14 00:00:07.403204 Starting harvester: /opt/applications/application2.stash
Oct 14 00:00:07 lumberjack[8950]: 2013/10/14 00:00:07.403242 Starting harvester: /opt/applications/application3.stash
Oct 14 00:00:07 lumberjack[8950]: 2013/10/14 00:00:07.403278 Starting harvester: /opt/applications/application4.stash
Oct 14 00:00:09 lumberjack[8950]: 2013/10/14 00:00:09.230942 Registrar received 9 events
Oct 14 00:00:09 lumberjack[8950]: 2013/10/14 00:00:09.231007 Saving registrar state.
Oct 14 00:00:09 lumberjack[8950]: 2013/10/14 00:00:09.480409 Stopping harvest of /opt/applications/application1.stash; last change was %!d(float64=86408.533923619) seconds ago
Oct 14 00:00:10 lumberjack[8950]: 2013/10/14 00:00:10.620632 File truncated, seeking to beginning: /opt/applications/application2.stash
Oct 14 00:00:10 lumberjack[8950]: 2013/10/14 00:00:10.678873 Registrar received 100 events
Oct 14 00:00:10 lumberjack[8950]: 2013/10/14 00:00:10.679274 Saving registrar state.
Oct 14 00:00:10 lumberjack[8950]: 2013/10/14 00:00:10.750842 Registrar received 100 events
Oct 14 00:00:10 lumberjack[8950]: 2013/10/14 00:00:10.751781 Saving registrar state.
Oct 14 00:00:10 lumberjack[8950]: 2013/10/14 00:00:10.837743 Registrar received 100 events
Oct 14 00:00:10 lumberjack[8950]: 2013/10/14 00:00:10.837859 Saving registrar state.
... it continues for minutes ...

All rotated files is also locked:
> lsof |grep -i del|grep -i lum
lumberjac  8950     root    9r      REG             252,16 261326822        121 /opt/applications/application1-2013-10-13-00.stash.gz (deleted)
lumberjac  8950     root   10r      REG             252,16  69066574        189 /opt/applications/application2-2013-10-13-00.stash.gz (deleted)
lumberjac  8950     root   17r      REG             252,16  31325509        105 /opt/applications/application3-2013-10-13-00.stash.gz (deleted)
lumberjac  8950     root   18r      REG             252,16  31108128        229 /opt/applications/application4-2013-10-13-00.stash.gz (deleted)
>

How can I do to understand what happens during rotation and why all nights at midnight Lumberjack wants to send my logs away? :-)

I only want Logstash to analyze new file and leave the old logfile alone...

**Comment by lucasRolff** [comment]
i'm surprised this is still not fixed in the logstash-forwarder :-1:

**Comment by jordansissel** [comment]
i don't recall ever being able to reproduce this problem on linux.

**Comment by jordansissel** [comment]
I'm pretty sure this was fixed in 0.4.0 if not earlier. Please open a new ticket if you have this problem and include any cool details if able :)
