### ISSUE TITLE
Connect via proxy

### ISSUE THREAD

**Issue by fandrei** [elastic/logstash-forwarder#110]
Is it possible to make Lumberjack connect via proxy? (on WIndows)

**Comment by jordansissel** [comment]
At this time SOCKS5 support is not on the roadmap.

**Comment by jordansissel** [comment]
lsf features (but not bugs) are in freeze waiting on the result of an experiment described [here](http://www.elasticsearch.org/guide/en/logstash/roadmap/current/index.html#_logstash_forwarder). We can revisit this later if we need to.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by https://github.com/elastic/filebeat/. If this is still an issue with filebeat, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
