### ISSUE TITLE
Build on FreeBSD

### ISSUE THREAD

**Issue by Celedhrim** [elastic/logstash-forwarder#112]
Hi,

I'm unable to build on freeBSD :

./filecompare.go:10: undefined: FileState
./prospector.go:42: undefined: FileState
./registrar.go:9: undefined: FileState
./registrar.go:20: undefined: file_ids
./registrar.go:21: undefined: FileState
./registrar_other.go:10: undefined: FileState

Trying to cp filestate_linux.go or filestate_darwin.go gave me this error : 

./filecompare.go:12: invalid operation: fstat.Ino == state.Inode (mismatched types uint32 and uint64)
./filecompare.go:12: invalid operation: fstat.Dev == state.Device (mismatched types uint32 and int32)

Any fix ? ( all requirement are install )

ruby gem : fpm (0.4.42)
go lang : go-1.1.2,1

**Comment by alappe** [comment]
It'd be *very* nice if this patch could get merged…

**Comment by j-trash** [comment]
exactly the same problem exists on smartos/omnios

**Comment by palmerabollo** [comment]
Same problem here on smartos.

**Comment by jordansissel** [comment]
@j-trash @palmerabollo please open a separate ticket for smartos.

**Comment by jordansissel** [comment]
Looks like freebsd patches logstash-forwarder: http://svnweb.freebsd.org/ports/head/sysutils/logstash-forwarder/files/

we can incorporate this patch, but until we do, it looks like you can easily install logstash-forwarder on freebsd using ports. :)

**Comment by atwardowski** [comment]
This patch was submitted 9 months before the freebsd port existed. :)

**Comment by ruflin** [comment]
Closing as of https://github.com/elastic/logstash-forwarder/pull/132 (see comments)
