### ISSUE TITLE
DNS lookup doesn't strip out port

### ISSUE THREAD

**Issue by danslimmon** [elastic/logstash-forwarder#116]
Introduced by https://github.com/elasticsearch/logstash-forwarder/commit/5a816d62f75fa2b39cd3368461e550a1f6094333 (I think)

Steps to reproduce:

1. Create a config with "servers": ["example.com:12345"]
2. In the logs, you'll see:

```
DNS lookup failure "example.com:12345": lookup example.com:12345: no such host
```

Note the port number present in the hostname. This is not a red herring; if you check tcpdump you can see that it's trying to lookup literally "example.com:12345" as a hostname

**Comment by jordansissel** [comment]
Fixed as reported.
