### ISSUE TITLE
logstash stops receving/lumberjack stops shipping events

### ISSUE THREAD

**Issue by volker-fr** [elastic/logstash-forwarder#127]
Unclear if this bug is already fixed in a newer version of logstash-forwarder. Will deploy the new version soon.

Used version:
- lumberjack 0.1.2 (self created deb package around Sep. 18th, 2013, unclear which exact git commit version)
- logstash 1.2.1 (official build)

I saw the following occurrence on various systems.

Lumberjack system:
- Systems are all AWS EC2, logfiles, especially the high volume ones like syslog, apache, and nginx are mainly on the ephemeral device.
- dozen of logfiles harvested by lumberjack
- logfiles have fixed names
- various logfiles (e.g. apache, syslog, mysql, nginx)
- logrotate once a day
- Most times this happens to systems with a high log volume. But I also saw it on systems with a low log volume.

Logstash loghost system information:
- heavy running system (CPU often at 100% for a long period, high load & memory usage; yes, entire log system is not scaled well enough yet)
- only logstash+elasticsearch used, no redis or similar
- ElasticSearch runs once in a while into too less memory issues (let's call it a potential hick-up source)

What happens:
- ElasticSearch stops receiving events from a host that runs lumberjack. Only from one lumberjack system, logs from the other systems running lumberjack are still transmitted without any problems.

How it is fixed:
- restarting lumberjack. Nothing else, after it the events get without any issues into ElasticSearch

Unclear what causes it. Maybe logstash has a hickup and lumberjack has an problem with it. Maybe the system where lumberjack delays something (don't think so, the systems with low log volume usually has usually a lot of free capacities (beside on system updates or similar). Maybe lumberjack runs into issues with logrotate. Or logstash stops accepting or processing events unless lumberjack sends a specific trigger. Have to kick of tcpdump the next time.

**Comment by jordansissel** [comment]
Closed since #249 was resolved in a different commit.
