### ISSUE TITLE
Global fields for all paths?

### ISSUE THREAD

**Issue by zanloy** [elastic/logstash-forwarder#130]
Is it possible to have a field that applies to all the paths in the json config? I know it's trivial to add but the config files are generated from puppet and it's easier to have a "global" fields configuration that applies to all.

**Comment by kevinbowman-ta** [comment]
Are +1's appreciated?  If so, I'd like to +1 this feature for a similar reason as @zanloy mentions, but have SaltStack pull a tag from EC2's meta-data and propogate it with the files.

Something like having an additional "fields" section at the top level of the config, eg:
```
{
  # Default fields to add to all of the "files" entries below
  "fields": {
    "environment": "prod",
    "role": "webserver"
  },
  "network": {
    "servers": [ "localhost:5043" ],
    "ssl certificate": "./logstash-forwarder.crt",
    "ssl key": "./logstash-forwarder.key",
    "ssl ca": "./logstash-forwarder.crt",
    "timeout": 15
  },
  # The list of files configurations
  "files": [
    {
      "paths": [
        "/var/log/messages",
        "/var/log/*.log"
      ],
      "fields": { "type": "syslog" }
    }, {
      "paths": [ "-" ],
      "fields": { "type": "stdin" }
    }, {
      "paths": [
        "/var/log/apache/httpd-*.log"
      ],
      "fields": { "type": "apache" }
    }
  ]
}
```

**Comment by torrancew** [comment]
:+1 this is easy enough to workaround, but first-class support for "global" fields would make our automation a good deal more elegant!

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by https://github.com/elastic/filebeat/. If this is still an issue with filebeat, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
