### ISSUE TITLE
Bleeding of separate log files into single event when using multiline filter

### ISSUE THREAD

**Issue by phildougherty** [elastic/logstash-forwarder#133]
Logstash 1.3.1
logstash-forwarder 0.3.1
Elasticsearch 0.9.70

I'm having a problems where multiple multiline events are somehow ending up in the same event in ES. I'm unsure if this is a problem with logstash-forwarder or logstash itself, but I didn't run into this issue when using other shippers in the past (beaver).

Example of the file field in ES:

```
 "file": [
      "/mnt/log/test1.test.com.log",
      "/mnt/log/test2.test.com.log"
    ],
```

logstash-forwarder config snippet:

```
    {
      "paths": [
        "/mnt/log/test1.test.com.log"
      ],

      "fields": {
        "type": "node_error",
        "tags": "backend"
      }
    },
    {
      "paths": [
        "/mnt/log/test2.test.com.log"
      ],

      "fields": {
        "type": "node_error",
        "tags": "backend"
      }
    },
```

Logstash config for node_error type:

```
if [type] == "node_error" {
  multiline {
    negate => true
    pattern => "^error_start"
    what => 'previous'
  }
  grok {
    named_captures_only => true
    match => { "message" => "(?m)error_start: (?:%{TIMESTAMP_ISO8601:timestamp}|-).*request: (?:%{URIPATHPARAM:request}|-).*referer: (?:%{DATA:referrer}|-).*clientip: (?:%{IPORHOST:clientip}).*error_type: (?:%{DATA:error_type}|-).*error_message: (?:%{GREEDYDATA:error_message}|-).*error_stack: (?:%{GREEDYDATA:error_stack}|-)"}
  }
  date {
    match => [ "timestamp", "ISO8601" ]
  }
}
```

**Comment by objectiveSee** [comment]
This is still an open issue.  Can we get a definitive way of solving this, perhaps added to the README (since it's such a common case)

**Comment by miguno** [comment]
@jordansissel wrote:
> There is an identified problem with the way I implemented the lumberjack input and the multiline codec. For now, you must all use the multiline filter, instead. Sorry for the confusion.

A multiline filter seems not to solve the problem.  For reference our logstash config (using multiline filters) looks as follows:

```
filter {

  # App logs of `foo`
  if [type] == "foo" {
    multiline {
      pattern => "^%{TIMESTAMP_ISO8601} "
      negate => true
      what => previous
    }
  }

  # Garbage collection logs of `foo`
  if [type] == "foo-gc" {
    multiline {
      pattern => "^%{TIMESTAMP_ISO8601} "
      negate => true
      what => previous
    }
  }
}
```

Even in this multline filter setup we see data from `foo` being merged with data from `foo-gc`.

**Comment by driskell** [comment]
@miguno See my earlier post https://github.com/elasticsearch/logstash-forwarder/issues/133#issuecomment-46835984

{quote}
You need to use stream_identity on logstash side so it can distinguish between log streams. I think %{host}.%{file}.%{type} is what I used. The default uses path but forwarder uses file thus the blurring.
{quote}

It's due to the second problem with LSF - it identifies files using a "file" field. Whereas Logstash uses "path" field, and the Logstash multiline filter defaults to using "path" to distinguish different streams. Setting stream_identity allows you to tell Logstash to use "file" field too to separate streams.

**Comment by miguno** [comment]
Thanks for the follow-up, @driskell.  In fact we have been deploying the file->path change right after my post above -- your comment was the only workaround that we haven't tested yet. :-)

```
    multiline {
      pattern => "^%{TIMESTAMP_ISO8601} "
      negate => true
      what => previous
      stream_identity => "%{host}.%{file}.%{type}"
    }
```

I'll report back whether this config setting solved the problem in our case.  Again, thanks Jason!

**Comment by miguno** [comment]
Doh.  I realized just now that this ticket is under logstash-forwarder, and not under logstash. :-)

@driskell: Your workaround didn't work in our case, but most likely because we're running logstash and not logstash-forwarder.  So other readers of this thread may still want to try the path->file change you suggested.

**Comment by driskell** [comment]
It's likely the same solution in your case - you just need to work out which fields to set in stream_identity, based on which input you are using. So switching path->file works for lumberjack input - just work out which identifies individual streams for your input.

**Comment by miguno** [comment]
May I ask two questions then: For one, do you know if there is an overview of the available fields like `host` and `path` (I failed to find find any)?

> It's due to the second problem with LSF - it identifies files using a "file" field. Whereas Logstash uses "path" field, and the Logstash multiline filter defaults to using "path" to distinguish different streams. Setting stream_identity allows you to tell Logstash to use "file" field too to separate streams.

I read your comment a few times but I'm not sure I fully understand your explanation.

I read in the docs that the default `stream_identity` in logstash is `host.path.type`.  My current understanding is that the even the shorter version `host.path` should be enough to uniquely identify a file in a simple setup such as ours (think: `/var/log/foo/*.log`), but apparently that's not the case in practice.  What I don't understand is how switching from `host.path.type` to `host.file.type` could help -- how would `server1.foo1.log.barType` be any better than `server1.full-path-too-foo1.log.barType`?  (I'm sure you have a good reason for suggesting this config change, but I am not yet sure how it would help, and thus how I could adapt your logstash-forwarder workaround to logstash.)

**Comment by driskell** [comment]
Available fields differs per event. Different inputs set different fields, and it also depends on any filters - filters can add/remove fields. Best to check output in elastic search or something to see the full fields for an event, then you can improve the multiline stream_identity accordingly.

stream_identity is indeed host.path.type by default. Logstash file input stores full path to file in "path" so it identifies different file streams.

Logstash forwarder stores the full path to file in "file", NOT "path". This is the issue. So stream_identify becomes `server1..barType` for every file. If you change stream_identity to host.file.type stream_identity would be correct, `server1.full-path-to-foo1.log.barType`.

For LSF I would actually say this is better: "%{host}.%{file}.%{path}.%{type}" - this works for both default and LSF - if LSF is ever fixed to change the field so it's called "path", it'll still work.

**Comment by miguno** [comment]
Ah, now I understand.  Many thanks for the clarification, Jason.

FYI:  In our case (logstash) we do have a sane `path`.  The strange thing is that the actual log data (the message field) is, sometimes, clearly from a different log file.  So occasionally we have events that say:

- The event's path is `/var/log/foo/appA.log`.
- The event's message is `appB could not do XYZ`.
- This message was actually logged in `appB.log`, not `appA.log`.

To me this looks like the error happens before we have the chance to fiddle with `stream_identity`, i.e. the actual data fields and their values are already messed up in a way that we can't recover from it via a logstash config.  I remember @jordansissel mentioning this will happen if you use a multiline codec, as here only a single codec is applied to all matching files, but we already switched to the [workaround he suggested](https://github.com/elasticsearch/logstash/issues/1435#issuecomment-60950110) (switching from multiline codec to multiline filter), and that doesn't help either.

**Comment by driskell** [comment]
How did you check you had a sane `path` ? If the event is received from LSF it won't - it'll be in `file`. Best to start with the multiline filter, apply the stream_identity fix, then monitor the events.

**Comment by miguno** [comment]
> How did you check you had a sane path ?

I looked at the raw data of the event stored in Elasticsearch.  From what I've seen the data in ES is identical to what I'd see if I use `stdout` as `output`.

Is there a different / better way to check?

> If the event is received from LSF it won't - it'll be in file. 

As I said above, we're not using LSF -- we're using "native" (JVM) logstash.

**Comment by miguno** [comment]
Example snippet of what I see in ES:

```json
{
  "_index": "...",
  "_type": "foo",
  "_id": "AUva4ImuChWEJmRj67Py",
  "_score": null,
  "_source": {
    "@timestamp": "2015-03-02T14:25:22.000+00:00",
    "message": "appB could not do XYZ",
    "@version": "1",
    "type": "foo",
    "host": "server1",
    "path": "/var/log/foo/appA.log",
    ...
    "tags": [
      "msg_parsed_ok"
    ]
  },
  "sort": [
    1425306322000
  ]
}
```

**Comment by driskell** [comment]
Ah I see. Probably best raised in the logstash issues then instead of here. Sorry.
Only thing I can think of is if the file is renamed appA to appB I think Logstash retains original filename as the stream - but at this point it should not be updating. Best to raise in Logstash repository though.

**Comment by jordansissel** [comment]
This is a lumberjack input bug; can y'all open a new ticket on github.com/logstash-plugins/logstash-input-lumberjack?
