### ISSUE TITLE
 Read error looking for ack: read tcp x.x.x.x:xxxx: i/o timeout

### ISSUE THREAD

**Issue by phildougherty** [elastic/logstash-forwarder#134]
I'm getting hit with this issue daily, which does not appear to be a TLS handshake issue which other github issues have mentioned. Everything will be chugging along nicely (I'm running 3 logstash indexers and handling around 1500 events/sec), then I will get an error about the lumberjack input crashing on a single indexer, and then all indexing grinds to a halt across all servers. I have been unable to find a way to recover from this issue, it will just randomly come back to life hours later.

I have tried messing with ntpdate as someone mentioned that could be a problem, but I'm running ntpd and my clock isn't behind. Restarting logstash does not help. Putting up a firewall on logstash servers to disallow all traffic, letting logstash fully start, then removing the firewall also does not help (someone mentioned that logstash will start accepting connections before the lumberjack pipeline is ready to handle requests which may be the cause of this problem). 

Could anyone give me a hand identifying how I can work around this issue or if this is a known bug? 

```
2013/12/18 19:24:15.370427 Connected to 10.0.1.11
2013/12/18 19:24:30.370584 Read error looking for ack: read tcp 10.0.1.11:5043: i/o timeout
2013/12/18 19:24:30.370690 Loading client ssl certificate: /opt/logstash-forwarder/ssl/logstash-forwarder.crt and /opt/logstash-forwarder/ssl/logstash-forwarder.key
2013/12/18 19:24:30.571044 Setting trusted CA from file: /opt/logstash-forwarder/ssl/ca.crt
2013/12/18 19:24:30.571406 Connecting to 10.0.1.11:5043 (10.0.1.11)
```

Logstash: 1.3.1
Logstash-Forwarder: 0.3.1
Ubuntu 12.04 LTS

**Comment by karthik87** [comment]
@driskell 
I have a strange issue where in my logstash forwarder connects to the logstash server only when I reboot my instance running the forwarder. Is it anything related to firewall or iptables?

**Comment by bkou** [comment]
For those of you who arrived here from google, check your elasticsearch log.

If you see "java.io.IOException: Too many open files", you need to raise your open file limit.

Elasticsearch recommends you [raise your open file limit to 32k or 64k](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/setup-configuration.html). Default on ubuntu is 4096. To check, go to: http://localhost:9200/_nodes/process?pretty

```
{
  "cluster_name" : "elasticsearch",
  "nodes" : {
      ...
      "process" : {
        ...
        "max_file_descriptors" : 4096,
        ...
      }
    }
  }
}
```

After following the procedure here:
http://posidev.com/blog/2009/06/04/set-ulimit-parameters-on-ubuntu/
You'll probably want to raise your soft limit to 32k or 64k instead of 9k as the link says. The link is not specific to elasticsearch, but is a general guide to raising your open file limit.

This is my current process info:

```
{
  "cluster_name" : "elasticsearch",
  "nodes" : {
      ...
      "process" : {
        ...
        "max_file_descriptors" : 65536,
        ...
      }
    }
  }
}
```

**Comment by adrianhowchin** [comment]
I was also getting this error in my lumberjack logs, after a restart of the ELK host. There was next to no CPU being used, despite the fact that I knew that thousands of messages per second were being sent to the host.

I fixed it by shutting down both logstash (indexer) and Elasticsearch, then starting up (in order):
1) Elasticsearch
2) Logstash

I suspect that when the VM got rebooted, it started up Logstash (the indexer) before Elasticsearch.

HTH.

Cheers,
Adrian

**Comment by Sennahoi** [comment]
I had similar problems when my harddisk ran out of free space, in that case, my elasticsearch.log said something like "shards will be relocated away from this node". HTH.
