### ISSUE TITLE
logstash-forwarder syslog output is broken

### ISSUE THREAD

**Issue by blalor** [elastic/logstash-forwarder#137]
I'm seeing the following in `/var/log/messages`:

    Dec 21 13:51:45 vagrant-dev-vagrant-blalor 2013-12-21T13:51:45Z vagrant-dev-vagrant-blalor logstash-forwarder[5955]: 2013/12/21 13:51:45.202314 Connecting to 10.0.1.13:4244 (10.0.1.13) 

logstash-forwarder is providing its own timestamp multiple times and duplicates the hostname.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
