### ISSUE TITLE
Do not assume cwd should be pwd for the prospector statefile

### ISSUE THREAD

**Issue by tomvachon** [elastic/logstash-forwarder#138]
I found when running something via upstart and not having a chdir and trying to debug and running by hand, the .logstash-forwarder would either be in / (via upstart without a chdir) or whatever PWD I was in in debugging.  This caused weird results in offsets.  

The forwarder should only put the state file in its own rundir (perhaps the parentdir of the executable?), preventing many of them from littering the FS and causing debugging problems.

Old Desc:
When running the executable directly, you end up no matter what flags are set, getting a start position at exactly 1/2 the byte length of the file.  Running via the .sh, all flag are obeyed and it starts at the end of the file.

**Comment by jordansissel** [comment]
I agree a setting for this would be nice.

**Comment by jordansissel** [comment]
For the meantime, `cd /some/path` before running logstash-forwarder will provide a workaround.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by https://github.com/elastic/filebeat/. If this is still an issue with filebeat, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
