### ISSUE TITLE
Missing log entries in log rotated files

### ISSUE THREAD

**Issue by jeffgus** [elastic/logstash-forwarder#144]
I tried to simulate the issue. I think what is happening is that the harvester isn't starting at the beginning of the new file. For testing, I set the timeout to 1 minute to simulate:

-        } else if age := time.Since(last_read_time); age > ( 24 * time.Hour ) {
+        } else if age := time.Since(last_read_time); age > ( time.Hour / 60 ) {

Then I did:
# for i in `seq 1 10000`;do echo $i >> test;sleep 1;done

After a time moved the file:
# mv test test.1

The logstash stdout output looked like this:
2014-01-14T23:38:58.331+0000 linux 1
[... skipped ...]
2014-01-14T23:39:23.330+0000 linux 25
2014-01-14T23:39:23.330+0000 linux 26
2014-01-14T23:39:23.331+0000 linux 27
2014-01-14T23:39:28.330+0000 linux 28
2014-01-14T23:39:28.330+0000 linux 31
2014-01-14T23:39:28.330+0000 linux 32
2014-01-14T23:39:35.830+0000 linux 33
2014-01-14T23:39:35.831+0000 linux 34
2014-01-14T23:39:35.831+0000 linux 35

Note that 29 through 30 are missing even though the new file starts with 29.

Jan 14 15:39:25 linux journal: 2014-01-14T15:39:25-08:00 linux logstash-forwarder[26550]: 2014/01/14 15:39:25.829328 Launching harvester on rotated file: /root/test
Jan 14 15:39:25 linux journal: 2014-01-14T15:39:25-08:00 linux logstash-forwarder[26550]: 2014/01/14 15:39:25.829362 Starting harvester: /root/test
Jan 14 15:39:25 linux journal: 2014-01-14T15:39:25-08:00 linux logstash-forwarder[26550]: 2014/01/14 15:39:25.829385 Current file offset: 6

The .conf file is set to watch only one file:
"files":[
  {"paths":["/root/test"],
   "fields":{"type":"root_test"}
  }]
}

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by jordansissel** [comment]
No response since march. If this is still a problem, then please open a new ticket and we can work together to improve things :)
