### ISSUE TITLE
Source not gofmt'd (or gofmt'd differently from default)

### ISSUE THREAD

**Issue by mipearson** [elastic/logstash-forwarder#152]
I have `gofmt` set to run on a save hook in my editor. Was quite surprised, on commit time, to see massive whitespace diffs.

I can tune gofmt to match your whitespace settings, but I'm not sure whether you did this intentionally.

I'll push through a quick PR of a default gofmt run. If you didn't do this intentionally, I recommend that you merge it. If you did do it intentionally, I recommend that you add a note to the README containing your preferred gofmt settings.

**Comment by jordansissel** [comment]
We'll move towards fully gofmt'd source soon. I agree with the idea.

**Comment by jordansissel** [comment]
logstash-forwarder is going to be retired, so without much more life in it, I don't know if we need to gofmt. The nice Elastic Beats folks are much more stylish than I if you wish to play with the new filebeat or libbeats!
