### ISSUE TITLE
logstash-forwarder and DELETED files

### ISSUE THREAD

**Issue by cova-fe** [elastic/logstash-forwarder#155]
I've run in an issue: I'm using logstash-forwarder to read data from files that are rotated daily (classical log files). Today I found that rotated files were kept in DELETED status by logstash-forwarder, thus preventing the OS to free up space. As anyone experienced the same issue?

**Comment by jordansissel** [comment]
Logstash-forwarder closes files not-modified in 24 hours now by default. The 24-hour time is tunable via the "dead time" setting

**Comment by suyograo** [comment]
If you have further questions please open it in discuss: https://discuss.elastic.co/c/logstash/logstash-forwarder
