### ISSUE TITLE
logstash-forwarder randomly stopping to send logs

### ISSUE THREAD

**Issue by teu** [elastic/logstash-forwarder#162]
Hi,

have the problem that the forwarder is randomly stopping to send logs. File is still populated with logs but the forwarder decided it's an old file and doesn't check any more.

```
2014/02/08 16:49:46.750622 Loading client ssl certificate: /opt/lumberjack/lumberjack.crt and /opt/lumberjack/lumberjack.key
2014/02/08 16:49:46.750979 Starting harvester: -
2014/02/08 16:49:47.035138 Current file offset: 0
2014/02/08 16:49:46.871471 Skipping old file: /var/log/apache2/access.json
2014/02/08 16:49:47.990506 Setting trusted CA from file: /opt/lumberjack/lumberjack.crt
2014/02/08 16:49:48.012460 Connecting to 10.62.197.248:6781 (logstash.sherstondevelopments.co.uk)
2014/02/08 16:49:48.415488 Connected to 10.62.197.248
2014/02/09 16:49:53.700060 Stopping harvest of -; last change was %!d(float64=86406.632560624) seconds ago

```

Now restarting it works but is a bit of a pain as those are AWS instances in a cluster. All the instances from that cluster stopped, not sure if at the same time.

**Comment by tpiha** [comment]
I can confirm this problem. I'm monitoring files and logstash forwarder just stops sending events in a random amount of time. It's working normally on one server which sends only small amount of data, but on those with larger amounts of data, it stops sending after some time without any message on logstash forwarder or logstash side.

This is a really big problem for us.

**Comment by evalencia** [comment]
Im seeing the same issues if the log isn't updated in 24 hours it stops sending events to logstash. This log is randomly written to at times but still need to get this:

2015/02/06 03:13:20.740771 Stopping harvest of /var/log/nodejs/nodejs.log; last change was %!d(float64=86405.153875113) seconds ago

**Comment by kikicarbonell** [comment]
:+1:

**Comment by phandinhloc** [comment]
Well, we have the same problem. logstash-forwarder just stop sending logs until we restart it.

**Comment by rakslice** [comment]
"This is not a bug"  What requirement of log monitoring calls for stopping monitoring the log file after a period of time !?

**Comment by jordansissel** [comment]
Maybe there's been some misunderstanding. It should be still checking for
those files to be modified later even if it closed the file.  The "close if
file is idle" is an optimization to allow resource cleanup. If the file is
modified later, it should be reopened. If not, this is a bug.

**Comment by JDiPierro** [comment]
I haven't encountered this bug in a while because I created a cron job to restart the forwarder every night at midnight.. but I believe it wasn't re-opening the file if it was modified later. Someone currently encountering the bug should verify this.

**Comment by driskell** [comment]
Ideally provide new logs if yo have issues like this. I think in the OP case there's not enough information, and a mixup between "Stooping harvest of..." and "Skipping old file..."
The former happens 24h (configurable now I think) after the last change to the open file.
The latter happens for new files if they've not been touched for 24h - usually during startup only if there's a previously unknown file there which is old. Can also appear if you move/copy in an old file. Just stops unnecessary shipping since its expected to ship realtime.

**Comment by jordansissel** [comment]
I think we need more information. Upon restart, what files are not reopened? Can you attach your logstash-forwarder config?

**Comment by jordansissel** [comment]
No updates since March. If this is still an issue, let's open a new ticket and we can work together on a fix :)
