### ISSUE TITLE
Keeps sending file, over and over.. (svlogd rotation issue?)

### ISSUE THREAD

**Issue by Xevian** [elastic/logstash-forwarder#168]
I've just started to use logstash-forwarder to ship logs from several of our tools, they're all running via runit and logs handled by svlogd.. I just had one of them rotate the 'current' file and then logstash-forwarder continuously sends the old file (now called '@4000000053060bf01d46491c.s')..

I suspect this is to do with how svlogd does rotation? from there docs..

"svlogd closes current, changes permission of current to 0755, renames current to @timestamp.s, and starts with a new empty current. If svlogd sees num or more old log files in the log directory, it removes the oldest one. "

This is what I see repeated untill I restart the the forwarder:

Feb 20 14:09:01 col-a logstash-forwarder[2716]: 2014/02/20 14:09:01.967623 File truncated, seeking to beginning: /opt/toola/log/current
Feb 20 14:09:03 col-a logstash-forwarder[2716]: 2014/02/20 14:09:03.071630 Registrar received 100 events
Feb 20 14:09:03 col-a logstash-forwarder[2716]: 2014/02/20 14:09:03.326686 Registrar received 100 events
Feb 20 14:09:03 col-a logstash-forwarder[2716]: 2014/02/20 14:09:03.501103 Registrar received 100 events
Feb 20 14:09:03 col-a logstash-forwarder[2716]: 2014/02/20 14:09:03.684181 Registrar received 100 events
Feb 20 14:09:03 col-a logstash-forwarder[2716]: 2014/02/20 14:09:03.855328 Registrar received 100 events
Feb 20 14:09:04 col-a logstash-forwarder[2716]: 2014/02/20 14:09:04.028524 Registrar received 100 events
Feb 20 14:09:04 col-a logstash-forwarder[2716]: 2014/02/20 14:09:04.205414 Registrar received 100 events
Feb 20 14:09:04 col-a logstash-forwarder[2716]: 2014/02/20 14:09:04.381633 Registrar received 100 events
Feb 20 14:09:04 col-a logstash-forwarder[2716]: 2014/02/20 14:09:04.547635 Registrar received 100 events
Feb 20 14:09:04 col-a logstash-forwarder[2716]: 2014/02/20 14:09:04.720709 Registrar received 100 events
Feb 20 14:09:04 col-a logstash-forwarder[2716]: 2014/02/20 14:09:04.892277 Registrar received 100 events
Feb 20 14:09:05 col-a logstash-forwarder[2716]: 2014/02/20 14:09:05.057871 Registrar received 100 events
Feb 20 14:09:05 col-a logstash-forwarder[2716]: 2014/02/20 14:09:05.229471 Registrar received 100 events
Feb 20 14:09:05 col-a logstash-forwarder[2716]: 2014/02/20 14:09:05.396937 Registrar received 100 events
Feb 20 14:09:05 col-a logstash-forwarder[2716]: 2014/02/20 14:09:05.560962 Registrar received 100 events
Feb 20 14:09:05 col-a logstash-forwarder[2716]: 2014/02/20 14:09:05.728579 Registrar received 100 events
Feb 20 14:09:05 col-a logstash-forwarder[2716]: 2014/02/20 14:09:05.901546 Registrar received 100 events
Feb 20 14:09:06 col-a logstash-forwarder[2716]: 2014/02/20 14:09:06.065657 Registrar received 100 events
Feb 20 14:09:06 col-a logstash-forwarder[2716]: 2014/02/20 14:09:06.236078 Registrar received 100 events
Feb 20 14:09:06 col-a logstash-forwarder[2716]: 2014/02/20 14:09:06.406848 Registrar received 100 events
Feb 20 14:09:06 col-a logstash-forwarder[2716]: 2014/02/20 14:09:06.575179 Registrar received 100 events
Feb 20 14:09:06 col-a logstash-forwarder[2716]: 2014/02/20 14:09:06.755718 Registrar received 100 events
Feb 20 14:09:06 col-a logstash-forwarder[2716]: 2014/02/20 14:09:06.935162 Registrar received 100 events
Feb 20 14:09:07 col-a logstash-forwarder[2716]: 2014/02/20 14:09:07.102253 Registrar received 100 events
Feb 20 14:09:07 col-a logstash-forwarder[2716]: 2014/02/20 14:09:07.279536 Registrar received 100 events
Feb 20 14:09:07 col-a logstash-forwarder[2716]: 2014/02/20 14:09:07.452380 Registrar received 100 events
Feb 20 14:09:07 col-a logstash-forwarder[2716]: 2014/02/20 14:09:07.614695 Registrar received 100 events
Feb 20 14:09:07 col-a logstash-forwarder[2716]: 2014/02/20 14:09:07.779857 Registrar received 100 events
Feb 20 14:09:15 col-a logstash-forwarder[2716]: 2014/02/20 14:09:15.204703 Registrar received 83 events

**Comment by jordansissel** [comment]
```
 Feb 20 14:09:03 col-a logstash-forwarder[2716]: 2014/02/20 14:09:03.071630 Registrar received 100 events
Feb 20 14:09:03 col-a logstash-forwarder[2716]: 2014/02/20 14:09:03.326686 Registrar received 100 events
Feb 20 14:09:03 col-a logstash-forwarder[2716]: 2014/02/20 14:09:03.501103 Registrar received 100 events
```

These are not indications of "sending file over and over". Can you clarify? Is this still occuring?

**Comment by jordansissel** [comment]
No response in a while. If this is still an issue, we can reopen, or just file a new ticket and we can work together on fixing things :)

**Comment by suyograo** [comment]
Can you reopen a new issue if this is still happening?

**Comment by suyograo** [comment]
Can you reopen a new issue if this is still happening?
