### ISSUE TITLE
Optionally SSL

### ISSUE THREAD

**Issue by meganuke19** [elastic/logstash-forwarder#178]
I plan use lumberjack in my local network and not need ssl. Maybe add SSL use optionally?

**Comment by urso** [comment]
TLS configuration can be disabled explicitly in filebeat (not default). NOT RECOMMENDED, even in "private" networks I would think twice about sending data in plain-text between machines.

Disabling in logstash still pending: elastic/ruby-lumberjack/pull#14

**Comment by urso** [comment]
still depends on logstash-plugins/logstash-input-lumberjack#55

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?

**Comment by sandstrom** [comment]
@jordansissel Thanks for making logstash! :boat: 

*(for reference if others end up on this thread, SSL is optional in filebeat: https://github.com/elastic/filebeat/issues/44#issuecomment-142239608)*
