### ISSUE TITLE
Monitoring API for Logstash Forwarder

### ISSUE THREAD

**Issue by kiranos** [elastic/logstash-forwarder#183]
Hi I'm still testing this and would really like to have some sort of way to know and easily setup a check with icinga/nagios if logstash-forwarder is shipping logs or if it somehow has halted.

I dont know how to solve it, there could be a threshold in the config file which says to generete an error in a logfile if no logs has been processed under this threshold or some other way for a third party script to check when the last time was that logstash-forwarder processed a logfile.

Might be good to brainstorm if this feature seems feasible, I would love to have some sort of security by knowing that I will get an alarm if the logs stops to pour in.

Thanks

**Comment by jordansissel** [comment]
lsf is feature-frozen until the experiment described [here](http://www.elasticsearch.org/guide/en/logstash/roadmap/current/index.html#_logstash_forwarder) is concluded. In general, I agree with @avleen and others: there needs to be an API to ask lsf how it's doing.

In the meantime, using a logfile as a heartbeat can help.

**Comment by jordansissel** [comment]
We will add an API for filebeat for monitoring

**Comment by elvarb** [comment]
Then think about how well this goes together with the logstash http poller input :-)

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
