### ISSUE TITLE
Document where do logstash-forwarder's own logs get logged

### ISSUE THREAD

**Issue by jameshfisher** [elastic/logstash-forwarder#186]
I've installed logstash-forwarder via the Debian repository.

When I start it manually using `/opt/logstash-forwarder/bin/logstash-forwarder -config /etc/logstash-forwarder`, I get log events on stdout, e.g.

    2014/04/01 11:31:24.213086 Registrar received 1 events
    2014/04/01 11:31:34.148949 Registrar received 1 events
    2014/04/01 11:32:34.151435 Registrar received 1 events

However when I start it using `service logstash-forwarder start`, I don't know where those logs go, and I can't find any documentation on it.

**Comment by juise** [comment]
+1, very annoying/noisy and meaningless

**Comment by Thinkscape** [comment]
Same here on Debian. Surprised that *forwarder effectively forwards itself* ... 

The only workaround I found is to manually remove `-log-to-syslog` param from init script.

**Comment by jordansissel** [comment]
There is a `-quiet` flag you can use that omits the informational logs such as "Received N messagse"

**Comment by Thinkscape** [comment]
@jordansissel will `-quiet` work alongside `-verbose` ?

**Comment by sergeykalenyuk** [comment]
Logstash-forwarder is called with: "-config /etc/logstash-forwarder -spool-size 100 -log-to-syslog true -quiet true".
Still have new notices in Kibana.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
