### ISSUE TITLE
logstash-forwarder not shipping logs from configured folder

### ISSUE THREAD

**Issue by shankarLyatiss** [elastic/logstash-forwarder#189]
I have a simple 2 VM setup with logstash forwarder on one of them trying to ship logs to the logstash instance on the other VM. Although I see that log stash-forwarder is able to connect to the logstash instance, nothing gets actually shipped. 
Here are the details : 
Here is my config on logstash forwarder side: 
 {
"network": {
   "servers": [ "<public IP/private IP>:5043" ],
   "ssl key": "/etc/ssl/private/logstash-forwarder.key",
   "ssl ca": "/etc/ssl/certs/logstash-forwarder.crt"
 },
 "files": [
   {
     "paths": [ "/home/ubuntu/tmp/*.log" ],
     "fields": {"type": "example"}
   }
 ]
}

On the logstash side, here is the input config: 
input {
lumberjack {
  port => 5043
  ssl_certificate => "/etc/ssl/certs/logstash-forwarder.crt"
  ssl_key => "/etc/ssl/private/logstash-forwarder.key"
  type => "example"
  host => "<public ip/private ip>"
  debug => true
}
}
output {
stdout {}
}

First, I see that the two are connected - via logs: 
 Connecting to <public ip/private ip>:5043 (public ip/private ip)
 Connected to <public ip / private ip>
When there is a new file or an update to an existing file, I see the following logs in the log stash-forwarder: 
 Starting harvester: /home/ubuntu/tmp/tmp1.log
 Current file offset: 337

However, I don't see any actual transport of data. I did a tcp dump on port 5043 to observe the traffic & I don't see any traffic beyond the initial tcp connection. 

This used to work for me earlier. I'm missing the log which looks like : 
Registrar received 1 events
Registrar received 23 events
Registrar received 1024 events

I'm not sure what I am doing wrong.

**Comment by karthik87** [comment]
I am running a logstash server on a cloud VM and trying to connect to it using a logstash-forwarder from another cloud VM. I am using the SSL keys specified by @driskell in one of the forums using lc-tlscert.go. The issue is, the connection works fine only when I restart the VM running the forwarder. While it is ok on a testing setup, I can restart my production servers easily. So I need to know why it behaves this way.

Thanks,
Karthik

**Comment by jordansissel** [comment]
Based on the original report (lsf not shipping files) - the described behavior seems like the default behavior (start following a file stream at the _end_ for unknown files). The fix is to use -from-beginning flag to tell it to start at the beginning for unknown files.

**Comment by splashx** [comment]
What's the recommended setting for bulk import? 
I'm getting `Skipping file (older than dead time of 24h0m0s):` and setting "deadtime" in the path to "999h" seems silly.
