### ISSUE TITLE
Support for AMQP (RabbitMQ preferred) as transport

### ISSUE THREAD

**Issue by lxndrp** [elastic/logstash-forwarder#190]
Folks,

I would appreciate very much if you'd consider adding [AMQP](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html) as an output transport to lumberjack.

At least for the RabbitMQ and ActiveMQ implementations of AMQP, authentication, encryption, and compression are supported, so that the main requisites for a new transport are met.

The background is that we are running very large numbers of potential log shippers, and I'd like to distribute the load via our RabbitMQ HA clusters rather than via direct `lumberjack -> logstash` connections, as we cannot afford loss of messages on server crash or overload. RabbitMQ brings features for federation, queue rerouting, throttling and rate limiting, replication and many other things which logstash does not have.

Let me know what you think.

Cheers,
Alexander

**Comment by karlatkinson** [comment]
LSF -> SQS would be awesome :+1: 
I've got a ton of EC2 instances I want to ship logs off without having to use full-on logstash.

**Comment by jerrac** [comment]
From the sounds of things, lsf's functionality is going to be rolled into
logstash itself. See
http://www.elastic.co/guide/en/logstash/roadmap/current/index.html
Hopefully lowering RAM usage is part of that.

--David Reagan

**Comment by jonatanblue** [comment]
Thank you for discussing this issue, I really appreciate the work you're doing and the thought going into this. Here is my contribution to why this is an important feature when you start running Logstash and Elasticsearch at scale.

@jordansissel asked:
> what is the benefit in doing putting a broker in between lsf and logstash, where today the protocol used does not require a broker?

Elastic [recommends using a broker/queue](https://www.elastic.co/guide/en/logstash/current/deploying-and-scaling.html) when *"data coming into a Logstash pipeline exceeds the Elasticsearch cluster’s ability to ingest the data"*.

The assumption that forwarders can hold on to data until successfully pushed is invalid if your servers are part of an automatically scaling cluster or group. For example, servers in an AWS AutoScaling Group may be terminated at any time, and any log events not yet pushed will then be lost. You must use a queue, or you will regularly lose data.

The recommended [queueing pipeline](https://www.elastic.co/guide/en/logstash/current/deploying-and-scaling.html#deploying-message-queueing) design puts a shipper between the Logstash Forwarders and the queue:
![deploy_5](https://cloud.githubusercontent.com/assets/2016004/10969261/070ba53c-83bf-11e5-852f-76977f2b85c5.png)

In this case the forwarder->logstash only limitation adds unnecessary complexity. I understand there are issues involved with supporting other tools, like RabbitMQ, but from a systems design perspective the shipper in this picture is pure waste. If you already have a queue where all events are buffered, why not forward the log events straight to the queue? Why send them via an additional Logstash server? This is not a problem with only a handful of forwarders, but with hundreds or thousands of them you will need an increasing number of powerful shippers.

@gauthier-delacroix suggests shifting the forwarding responsibility to RabbitMQ - I'm all for that, but if queueing is part of the recommended design of a scalable Logstash, wouldn't it make sense for Logstash Forwarder to facilitate it?

There is a related discussion at https://github.com/elastic/logstash/issues/3693, but I'm not sure how/if it addresses this issue.

**Comment by adiworkoholic** [comment]
It's been 4 months since the last activity on this. Any updates on the way forward ?

**Comment by ruflin** [comment]
As logstash-forwarder is no longer under active development and was replaced by filebeat, it is best to continue this discussion under the following issue: https://github.com/elastic/beats/issues/943
