### ISSUE TITLE
Duplicate and missing lines

### ISSUE THREAD

**Issue by pascalrobert** [elastic/logstash-forwarder#207]
Hi,

We use logstash-forwarder to monitor a custom log file, on a Ubuntu 12.04 LTS box (ext3 file system). Currently, we are doing this:

- logstash-forwarder watchs /var/log/AT/log.txt
- a cron job launch at midnight, and it rename /var/log/AT/log.txt to /var/log/AT/logYESTERDAY.txt
- the PHP script that write /var/log/AT/log.txt also write the same data in another log (NOT watched by logstash-forwarder), so that we can compare Logstash's output with the copy

But we have some issues:

- We have missing lines in Logstash. Those lines are written when the cronjob is started, but they do are written to the /var/log/AT/logYESTERDAY.txt file.

- We have many (~ 2500 lines out of a +90 000 lines file) duplicate lines. Sometimes the offset is the same for the duplicate, sometimes it's the same offset. The timestamp that Logstash adds is different for every case. It happens all day long, so it's not related to the file renaming operation done by the cron.

I saw someone who created an issue about duplicates, so I looked at the log to see if a special char was at the end of the line, and everything's is fine.

**Comment by jordansissel** [comment]
No response since Aug 2014. If this is still a problem, please open a new ticket and we can work together on a solution :)
