### ISSUE TITLE
unsigned logstashforwarder RPM for CentOS5/RHEL5 ?

### ISSUE THREAD

**Issue by MattMacGillivray** [elastic/logstash-forwarder#209]
I've found a signed CentOS6/RHEL6 logstash forwarder RPM for installation here:
http://packages.elasticsearch.org/logstashforwarder/centos/logstash-forwarder-0.3.1-1.x86_64.rpm

However, using my puppet scripts, when i try to install it on RHEL5, it gives the following error because it's using v4 signatures, whereas CentOS5/RHEL5 only support v3 signatures:
Error: Execution of '/bin/rpm -i /opt/logstashforwarder/swdl/logstash-forwarder-0.3.1-1.x86_64.rpm' returned 1: error: /opt/logstashforwarder/swdl/logstash-forwarder-0.3.1-1.x86_64.rpm: Header V4 RSA/SHA1 signature: BAD, key ID d88e42b4

I'm using puppet-logstashforwarder for installation, is there an unsigned, or v3 signature compatible rpm/repo?

Thanks,

Matt.

**Comment by ficus** [comment]
Also wondering if there is a current RPM.  Tried to build and install manually and got fed up writing init.d script.  That RPM linked above worked but logstash-forwarder ended up running as root.

**Comment by twkonefal** [comment]
For those of you with access:
https://access.redhat.com/solutions/24128

The gist is thus:
"As explained in the man page for createrepo, sha256 is used as the default checksum type, which the version of yum on Red Hat Enterprise Linux 5 does not recognize:"

Resolution:
"When creating a yum repository with the createrepo command on Red Hat Enterprise Linux 6, use the -s sha option for Red Hat Enterprise Linux 5 repositories:

# createrepo -s sha .

So, maybe we could get a RHEL5/CentOs5 repo with this technique?
