### ISSUE TITLE
Memory leak with logstash-forwarder on logstash side https://logstash.jira.com/browse/LOGSTASH-2168

### ISSUE THREAD

**Issue by timhaak** [elastic/logstash-forwarder#212]
Hi

Adding this here so people are aware.

Fault is on log stash side not on the forwarder.

https://logstash.jira.com/browse/LOGSTASH-2168

**Comment by jordansissel** [comment]
Logstash 1.5.2 has a circuit breaker in the lumberjack input to keep the lumberjack input from consuming excess resources when the Logstash pipeline is stuck. I believe this problem is fixed.
