### ISSUE TITLE
Logstash forwarder keeps lock on log files on windows

### ISSUE THREAD

**Issue by kozyarchuk** [elastic/logstash-forwarder#216]
Logstash forwarder keeps lock on log files on windows even after the log producer has exited.   To reproduce.

1. run logstash-forwarder on some folder.
2. run a script to generate a log in that folder
3. wait for producer to finish
4. try to delete/rename newly created log file
5. stop logstash-forwarder and repeat deletion

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by kozyarchuk** [comment]
This was resolved by merging one of the branches.
-- Maksim

**Comment by vitalyal** [comment]
logstash forwarder built from latest master still locks files. Original steps to reproduce are still valid. Which branch merge has worked for you?

**Comment by toebens** [comment]
We are also having this problem. This is still an issue. It is blocking us of using logstash-forwarder.
Unfortunately i don't know golang to help out and providing a bugfix. It would be really cool if this could be fixed pretty soon.

**Comment by ruflin** [comment]
This should now be fixed in filebeat (next version of logstash-forwarder) with https://github.com/elastic/filebeat/pull/74

**Comment by ruflin** [comment]
As the next release of logstash-forwarder will be [filebeat](https://github.com/elastic/filebeat), I will close this issue based on the comment above. In case the issue still exists in filebeat, please reopen or open a new issue directly in the filebeat repo.
