### ISSUE TITLE
Failed to tls handshake

### ISSUE THREAD

**Issue by JohanTan** [elastic/logstash-forwarder#230]
I tried to run the latest version of logstash-forwarder but got this error when using the same ssl certificate:

"2014/07/18 12:54:26.661369 Failed to tls handshake with 10.200.234.123 x509: certificate is valid for , not elastics1b"

Regenerating certificate does not help.

**Comment by GermanG** [comment]
```
openssl req -x509 -subj '/CN=*.example.org/' -nodes -newkey rsa:2048 -keyout logstash-forwarder.key -out logstash-forwarder.crt
```

Worked for me, as long as you have logstash.example.org in your DNS or /etc/hosts

**Comment by abdalians** [comment]
Hi 

We are seeing this in our logs on 2 out of 24 hosts. 22 Hosts are working fine just 2 of them give the tls handshake error. We are using the same logstash-forwarder-0.4.0-1.x86_64.rpm on all the hosts with the same config file and cert. 

Any help is appreciated. 

2015/06/16 12:22:56.669086 Connecting to [10.202.61.81]:5000 (hostname.domainname.com) 
2015/06/16 12:22:56.746125 Failed to tls handshake with 10.202.61.81 x509: certificate is valid for , not hostname.domainname.com
2015/06/16 12:22:57.746697 Connecting to [10.202.61.81]:5000 (hostname.domainname.com) 
2015/06/16 12:22:57.824563 Failed to tls handshake with 10.202.61.81 x509: certificate is valid for , not hostname.domainname.com

**Comment by jordansissel** [comment]
@abdalians you need to provide lsf and logstash with a certificate that is valid for the address you are connecting.

**Comment by abdalians** [comment]
yes absolutely correct, it is the same cert on all the 24 hosts, and the config points to the same fqdn. the fqdn resolves to the same IP on all hosts as well. 

Still no go, getting the tls error.

**Comment by jordansissel** [comment]
@abdalians "certificate is valid for , not hostname.domainname.com" this log message seems to indicate that your certificate has an empty common name, I guess, and you are expecting it to be hostname.domainname.com. I don't know what to tell you other than to investigate the certificate you have on the 2 (of 24) logstash-forwarders which are not working.

**Comment by abdalians** [comment]
I literally scp the cert file over from one of the working hosts and the lsf config is pointing to this file. 
I even downgraded to a lower version of lsf but still doesnt work.

**Comment by jordansissel** [comment]
@abdalians I don't have enough information to advise you further. Sorry :(

**Comment by abdalians** [comment]
thanks. is there additional info I can provide that can shed light? 

is there a tls_strict_verify = false option I can specify?

**Comment by jordansissel** [comment]
> is there a tls_strict_verify = false option I can specify?

No.

> is there additional info I can provide that can shed light?

I don't know. lsf is claiming that your provided certificate has _no_ subject information, and you disagree and say you are using a correct certificate. I don't know how to reconcile that disagreement.

**Comment by driskell** [comment]
Is the binary the same on those hosts or could it be built differently or installed from elsewhere?

**Comment by driskell** [comment]
Scratch that. RPM -.-

**Comment by driskell** [comment]
I guess check that you actually have 0.4.0 on ALL hosts and not a mix with the previous RPM. I can guess the previous RPM did not verify hostname so would actually work with blank common name. But using blank common name with 0.4.0 will fail. Just a thought!

**Comment by abdalians** [comment]
@jordansissel  is there a debug flag on lsf? 

@driskell yes the version output from both working and not working hosts is 0.4.0 
/opt/logstash-forwarder/bin/logstash-forwarder -version
0.4.0

the working hosts worked with 0.3 also and the failing hosts also failed with 0.3 

Could there be a underlying tls package missing or config setting on the os level that is causing this ?

**Comment by jordansissel** [comment]
@abdalians logstash-forwarder is a self-contained build, there is no external dependency (TLS package or OS-level setting) that would likely cause your issue. My best guess is that your ssl cert is still not correct. 

Can you attach your full logstash-forwarder config file from the broken host?

**Comment by driskell** [comment]
What if you ran `</dev/null openssl s_client -connect 10.202.61.81:5000` (sorry if I typo it)
Should dump the logstash certificate so we can see what Golang SHOULD be seeing.

**Comment by abdalians** [comment]
@jordansissel  here is the config same on both working / failing hosts. 
http://pastebin.com/yqfGpayu


@driskell  Here it is.. from a working and failing host. 
http://pastebin.com/hkyFuT6v

**Comment by jordansissel** [comment]
From your `openssl s_client` example - 

`subject=/C=XX/L=Default City/O=Default Company Ltd`

There's no CN field, here. The certificate you've given to Logstash (lumberjack input) has no CN (commoName) field and therefore matches no hostname. Given the error you get from logstash-forwarder (`certificate is valid for , not ....`), this is the error I expect given the configuration I observe through your `openssl s_client` output.

Your logstash lumberjack input on hostname.domainname.com:5000 has an incorrect SSL certificate with no commonName field.

**Comment by abdalians** [comment]
"Your logstash lumberjack input on hostname.domainname.com:5000 has an incorrect SSL certificate with no commonName field."

can you please help me explain then why the other 22 hosts are working against the same hostname.domainname.com:5000. 

I swear I am not making this up... :(

**Comment by jordansissel** [comment]
@abdalians I believe you, I'm just trying to apply my experience to your reports. I agree it's weird, so I don't have much explanation :\

**Comment by abdalians** [comment]
ok np Thanks guys @jordansissel @driskell

**Comment by driskell** [comment]
No problem. It may be something weird but if you change the certificate it would hopefully fix everything.

I do wonder though if the other servers are definitely running 0.4.0. Only reason I can think they work fine is if 0.3.2 (last version) was installed
as that did not check certificate name IIRC. Maybe 0.4.0 is installed but service never restarted so it still runs 0.3.2? Who knows!? Sorry haven't been able to pin point exactly.

**Comment by suyograo** [comment]
Closing this, if y'all hit any more issues related to this please open a new one
