### ISSUE TITLE
ZLib Errors cause logstash to quit

### ISSUE THREAD

**Issue by rwilliamselab** [elastic/logstash-forwarder#235]
Having multiple errors such as Zlib::DataError: invalid distance code and logstash Zlib::DataError: invalid block type that causes the logstash service to stop. Feeders to the service are from other logstash instances (4 of them) also running logstash and using the lumberjack protocol to send logs

**Comment by jordansissel** [comment]
> blow up

Can you provide more details? What's your configuration? What is this `300K` number and why is it special? Is one line 300KB? or is it three-hundred-thousand lines of text?

**Comment by suyograo** [comment]
No response since March, please reopen the issue if you have more details
