### ISSUE TITLE
Support conf.d based configuration

### ISSUE THREAD

**Issue by shivanshukumar** [elastic/logstash-forwarder#244]
Having a way to specify logstash-forwarder configuration in fragments that get merged would be very helpful.

Instead of specifying one single json file, I could have one file each per component that I install on a host e.g. 
/etc/logstash-forwarder/conf.d/apache
/etc/logstash-forwarder/conf.d/syslog
/etc/logstash-forwarder/conf.d/mysql
/etc/logstash-forwarder/conf.d/some_app
/etc/logstash-forwarder/conf.d/network

together making up the configuration for logstash-forwarder

also use this in the init script.

**Comment by jordansissel** [comment]
Fixed - #136 is fixed.
