### ISSUE TITLE
server.rb drops debug information for failed SSL connections on the floor

### ISSUE THREAD

**Issue by mipearson** [elastic/logstash-forwarder#246]
See https://github.com/elasticsearch/logstash-forwarder/blob/master/lib/lumberjack/server.rb#L45-L62

Possible fix is to merge @driskell 's https://github.com/driskell/logstash-forwarder/commit/11b1ed22b86f9ae32b18222fe7235353d9587263

**Comment by jordansissel** [comment]
+1 on making things easier to debug, especially SSL.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
