### ISSUE TITLE
Remove commented out / unused code

### ISSUE THREAD

**Issue by mipearson** [elastic/logstash-forwarder#248]
This project contains sections which are entirely commented out or are unused. This can make it difficult for contributors to identify where a bug might need to be fixed or how to make sure their change is compataible with the rest of the codebase.

eg, https://github.com/elasticsearch/logstash-forwarder/commits/master/lib/lumberjack/server2.rb

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by https://github.com/elastic/filebeat/. If this is still an issue with filebeat, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
