### ISSUE TITLE
Lumberjack client truncates UTF-8 text

### ISSUE THREAD

**Issue by brianwells** [elastic/logstash-forwarder#253]
I ran into an issue where the Logstash lumberjack input would occasionally receive truncated logs and was able to determine that [lumberjack/client.rb](https://github.com/elasticsearch/logstash-forwarder/blob/master/lib/lumberjack/client.rb) truncates strings that contain UTF-8 characters. 

It seems that this could be fixed by adjusting [line 124](https://github.com/elasticsearch/logstash-forwarder/blob/master/lib/lumberjack/client.rb#L124) of client.rb so that it forces the data to be treated as BINARY before packing the data into the frame for sending.

I've put together a Gist that demonstrates the bug and the potential fix: https://gist.github.com/brianwells/5a90abb94f3f8a295681

**Comment by suyograo** [comment]
this should fix it https://github.com/elasticsearch/logstash-forwarder/pull/329

**Comment by ph** [comment]
New version of the gem fix this issue.
