### ISSUE TITLE
A way to set up different log files so they can go to a different logstash servers

### ISSUE THREAD

**Issue by deadbeef404** [elastic/logstash-forwarder#257]
Hi all,
I'm sorry if I'm missing someone obvious but I have a question.

Is it possible to set up logstash-forwarder to forward one or two log files to always go to logstash server A, and have a completely different log file always go to logstash server B?

**Comment by jordansissel** [comment]
See my previous comment. To send the same logs to two different servers you'll need two different logstash-forwarders run separately.
