### ISSUE TITLE
Support sending logs to Kafka, instead of directly to logstash

### ISSUE THREAD

**Issue by blysik** [elastic/logstash-forwarder#258]
It's useful to have a buffer for logstash indexers to pull from.  (Redis, RabbitMQ, Kafka).  logstash-forwarder should support sending data into Kafka.

**Comment by BCWilsonDotCom** [comment]
+1 any updates on this?

**Comment by jordansissel** [comment]
Logstash has a Kafka output you can use for this purpose. At this time, the
only output lsf supports is to Logstash (via the lumberjack protocol).

**Comment by rberger** [comment]
Logstash requires deploying and running a JVM on every client. So it would be a win to have a lightweight client (like logstash-forwarder) as the mechanism to send to Logstash servers via Kakfa.

We have prototyped somehing using [fluentd](http://www.fluentd.org/) as the client writing onto kafka and being read by the logstash kafka input module. But this has the requirement of having to put ruby on all our client servers.

We're using Kafka for everything else. It would be nice to have it transport logs as well and have a lightweight client with no dependencies like logstash-forwarder.

If I had time I would take a stab at it. There is a couple very nice kafka library for go: 

The basic but full featured go client for Kafka
https://github.com/Shopify/sarama

Supports avro and schema registry, built on top of sarma:
https://github.com/stealthly/go_kafka_client

**Comment by TinLe** [comment]
Have you looked at kafkacat?   I was using lsf, but that got painful.
Since I switched to kafkacat, I have not had any problems.

https://github.com/edenhill/kafkacat

I use kafkacat to read logfiles and send to our kafka infrastructure.
It's wrapped in runit and tail -F to always follow new log files.   Simple
and work great.

Tin


On Tue, Jul 21, 2015 at 12:51 PM, Robert J. Berger <notifications@github.com

**Comment by rberger** [comment]
That’s pretty nice.

Do you need to do anything special so the logstash kafka input module will consume the logs on the topic you use kafkacat to publish to?

Could you share an example runit config file that does this? Do you have a config file per log or you tail a bunch of logs and let logstash sort it out?

Thanks
Rob
rberger@ibd.com <mailto:rberger@ibd.com> if you want to continue this privately, not sure if its appropriate for the issues forum.

**Comment by TinLe** [comment]
Since my log files are already in json format, I did not have to do
anything special.   I used the default log_event schema.

Yes, one config file per log, as these logs can get fairly large (700GB to
1TB+ per day).

Here is the meat of the kafkaput.sh script.   Define the variable and you
are good to go.

TOPIC="log-event_nginx_json"
PARTITIONS=-1
COMPRESSION="gzip"
#DEBUG="-c 3 -T"
DEBUG=
PATH=/export/apps/kafkacat:$PATH
NGINXLOG=/export/apps/nginx/logs/access-json.log
BROKER="kafka-zk-broker.example.com:12345"

tail -F ${NGINXLOG} | kafkacat -P -b ${BROKER} -t ${TOPIC} -p ${PARTITIONS}
-z ${COMPRESSION} ${DEBUG}

As for runit, just tell it to keep the script running, that's it.

#!/bin/bash
exec 2>&1
exec chpst -u app:app /export/apps/kafkacat/kafkaput.sh

I used fpm to create a kafkaput rpm with the script and runit setup as the
postinstall.   Now I just have to distribute the rpm via our deploy system
and voila.

Tin

**Comment by jonatanblue** [comment]
+1

**Comment by NikolaeVarius** [comment]
+1

**Comment by trixpan** [comment]
for those +1 this thread. I don't think it will happen anytime soon. 

Agree or not, Elastic still seem to see LS as the gateway to Kafka when using the ELK stack.With the death of LF, this is even more explicitly stated with :

> " In particular, we are very likely to reject pull requests that add a new output type (libbeat output
> for kafka, riemann, etc.). The reason is that maintaining all these outputs would involve a
> significant effort which is already spent in Logstash. You can use Logstash as a gateway to lots
> of already supported systems."

https://github.com/elastic/libbeat/blob/master/CONTRIBUTING.md


There are a few options in addition to the kafkacat already mentioned above, in special:

Mozilla's heka (just be mindfull Heka's kafka implementation using Sarama async is not durable)
https://github.com/mozilla-services/heka/

Some random dude's kafka version of "lumberjack" 
https://github.com/hyqer/kafka-forwarder
The code is largely unmaintained but can it uses Sarama (shopify Go's Kafka library) for all the heavy lifting and the library is well kept.

**Comment by tbragin** [comment]
For those that may not be following Beats closely, libbeat (and Filebeat) now support a Kafka output in master: https://github.com/elastic/beats/pull/942

**Comment by ruflin** [comment]
Closing this issue in favor of https://github.com/elastic/beats/issues/943 so we can continue the discuss there and the related issues.

**Comment by sunilmchaudhari** [comment]
> Since my log files are already in json format, I did not have to do
> anything special. I used the default log_event schema.
> 
> Yes, one config file per log, as these logs can get fairly large (700GB to
> 1TB+ per day).
> 
> Here is the meat of the kafkaput.sh script. Define the variable and you
> are good to go.
> 
> TOPIC="log-event_nginx_json"
> PARTITIONS=-1
> COMPRESSION="gzip"
> #DEBUG="-c 3 -T"
> DEBUG=
> PATH=/export/apps/kafkacat:$PATH
> NGINXLOG=/export/apps/nginx/logs/access-json.log
> BROKER="kafka-zk-broker.example.com:12345"
> 
> tail -F ${NGINXLOG} | kafkacat -P -b ${BROKER} -t ${TOPIC} -p ${PARTITIONS}
> -z ${COMPRESSION} ${DEBUG}
> 
> As for runit, just tell it to keep the script running, that's it.
> 
> #!/bin/bash
> exec 2>&1
> exec chpst -u app:app /export/apps/kafkacat/kafkaput.sh
> 
> I used fpm to create a kafkaput rpm with the script and runit setup as the
> postinstall. Now I just have to distribute the rpm via our deploy system
> and voila.
> 
> Tin
> 
> On Tue, Jul 21, 2015 at 1:34 PM, Robert J. Berger [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > That’s pretty nice.
> > Do you need to do anything special so the logstash kafka input module will
> > consume the logs on the topic you use kafkacat to publish to?
> > Could you share an example runit config file that does this? Do you have a
> > config file per log or you tail a bunch of logs and let logstash sort it
> > out?
> > Thanks
> > Rob
> > [rberger@ibd.com](mailto:rberger@ibd.com) mailto:[rberger@ibd.com](mailto:rberger@ibd.com) if you want to continue this
> > privately, not sure if its appropriate for the issues forum.
> > > On Jul 21, 2015, at 12:57 PM, Tin Le [notifications@github.com](mailto:notifications@github.com) wrote:
> > > Have you looked at kafkacat? I was using lsf, but that got painful.
> > > Since I switched to kafkacat, I have not had any problems.
> > > https://github.com/edenhill/kafkacat
> > > I use kafkacat to read logfiles and send to our kafka infrastructure.
> > > It's wrapped in runit and tail -F to always follow new log files. Simple
> > > and work great.
> > > Tin
> > > On Tue, Jul 21, 2015 at 12:51 PM, Robert J. Berger <
> > > [notifications@github.com](mailto:notifications@github.com)
> > > > wrote:
> > > > Logstash requires deploying and running a JVM on every client. So it
> > > > would
> > > > be a win to have a lightweight client (like logstash-forwarder) as the
> > > > mechanism to send to Logstash servers via Kakfa.
> > > > We have prototyped somehing using fluentd http://www.fluentd.org/ as
> > > > the client writing onto kafka and being read by the logstash kafka
> > > > input
> > > > module. But this has the requirement of having to put ruby on all our
> > > > client servers.
> > > > We're using Kafka for everything else. It would be nice to have it
> > > > transport logs as well and have a lightweight client with no
> > > > dependencies
> > > > like logstash-forwarder.
> > > > If I had time I would take a stab at it. There is a couple very nice
> > > > kafka
> > > > library for go:
> > > > The basic but full featured go client for Kafka
> > > > https://github.com/Shopify/sarama
> > > > Supports avro and schema registry, built on top of sarma:
> > > > https://github.com/stealthly/go_kafka_client
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > [#258 (comment)](https://github.com/elastic/logstash-forwarder/issues/258#issuecomment-123460036)
> > > > .
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > > [#258 (comment)](https://github.com/elastic/logstash-forwarder/issues/258#issuecomment-123461159)
> > > > .
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > [#258 (comment)](https://github.com/elastic/logstash-forwarder/issues/258#issuecomment-123469899)
> > .

Hi Tin,
Does kafka cat support Kafka connection over SSL?

**Comment by TinLe** [comment]
@sunilmchaudhari It's been years since I last used kafkacat, but last I checked, it does support talking to kafka over SSL.
