### ISSUE TITLE
proposal: Docker Support of container logs

### ISSUE THREAD

**Issue by sigmonsays** [elastic/logstash-forwarder#262]
Hello,

I am opening this issue to discuss collection of docker logs from docker containers. I am open to making a PR for this and might even do it if it wont be pushed upstream.

I'm not certain of the best way to achieve what I want however.  With existing logstash-forwarder,  I did inject the glob /srv/docker/containers/*/*.log properly. However, the container name is way too long and not meaningful. What I wish to do is provide docker support to logstash. 

I can imagine this working in a few different ways.

1. execute program with a mapping of "log name" to "log file"
I could easily invoke docker in this script to split out a list of log file names and the absolute path to the logfile, that logstash would read and begin following.

2. provide a way to translate the path to a "frontend" path

The log format is as follows 

find /srv/docker/containers/*/*.log
/srv/docker/containers/05672ed08e5b55d42d233d1ac8f2a9e1e88675c1d53d168a86eebdc33483f72e/05672ed08e5b55d42d233d1ac8f2a9e1e88675c1d53d168a86eebdc33483f72e-json.log
/srv/docker/containers/07ed3371a1ff5c4338d12be862dfe1a3d3716d0e545149a89d404c32b65cd082/07ed3371a1ff5c4338d12be862dfe1a3d3716d0e545149a89d404c32b65cd082-json.log

Sample log
{"log":" some message from a daemon\n","stream":"stdout","time":"2014-08-29T03:42:31.392041385Z"}

the log format is \n delimited and json structured.

**Comment by jordansissel** [comment]
Docker's got a logging api now for containers that will support fluentd and gelf protocols in Docker 1.8 - Logstash supports both fluentd and gelf protocols and will integrate with Docker in this way.

Long term, we will work with Docker to get lumberjack integrated if we find fluentd or gelf not working well enough.
