### ISSUE TITLE
init script config parameter

### ISSUE THREAD

**Issue by eskp** [elastic/logstash-forwarder#267]
Hey Jordan,

At the moment supplied init script is pointing to the wrong config file location and fails silently.

DAEMON_ARGS="-config /etc/logstash-forwarder -spool-size 100 -log-to-syslog"

1) Logstashforwarder gets installed in /etc/logstashforwarder (on Ubuntu anyway)

2) Looks like Logstashforwarder requires the config file and not the directory. I saw there is a request for this but looks like this is not yet implemented.

Cheers,

Simon

**Comment by jordansissel** [comment]
It looks like this was fixed, this is how LSF is run now:

```
$(PREFIX)/bin/logstash-forwarder -config /etc/logstash-forwarder.conf
```
