### ISSUE TITLE
NXLOG with Logstash-Forwarder "local error: protocol version not supported"

### ISSUE THREAD

**Issue by macling66** [elastic/logstash-forwarder#269]
SERVER
nxlog]# java -version
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)
Java HotSpot(TM) Client VM (build 23.25-b01, mixed mode)

CLIENT 
# java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) Client VM (build 24.65-b04, mixed mode, sharing)

2014/09/22 11:52:28.814451 Waiting for 2 prospectors to initialise
2014/09/22 11:52:28.814620 Launching harvester on new file: /var/log/messages
2014/09/22 11:52:28.814711 Launching harvester on new file: /var/log/httpd/access_log
2014/09/22 11:52:28.814767 harvest: "/var/log/messages" (offset snapshot:0)
2014/09/22 11:52:28.815107 All prospectors initialised with 0 states to persist
2014/09/22 11:52:28.815368 harvest: "/var/log/httpd/access_log" (offset snapshot:0)
2014/09/22 11:52:28.815619 Loading client ssl certificate: /installer/openssl/server11-cert.pem and /installer/openssl/server11-keyno.pem
2014/09/22 11:52:30.070699 Setting trusted CA from file: /installer/openssl/LinggaCA-cert.pem
2014/09/22 11:52:30.071603 Connecting to [10.147.252.13]:6514 (10.147.252.13) 
2014/09/22 11:52:30.080763 Failed to tls handshake with 10.147.252.13 local error: protocol version not supported
2014/09/22 11:52:31.081374 Connecting to [10.147.252.13]:6514 (10.147.252.13) 
2014/09/22 11:52:31.083352 Failed to tls handshake with 10.147.252.13 local error: protocol version not supported

Please advice how to solve ...

**Comment by jordansissel** [comment]
I don't know what "nxlog with logstash-forwarder" means.

Regarding your error:

> 2014/09/22 11:52:30.080763 Failed to tls handshake with 10.147.252.13 local error: protocol version not supported


This means logstash-forwarder is connecting to a server which uses a version of TLS/SSL that is unsupported. I don't know what version of logstash-forwarder you are using, but minimum version is TLS 1.0.

**Comment by suyograo** [comment]
Please reopen if you have more info
