### ISSUE TITLE
registry rotation on Windows fails

### ISSUE THREAD

**Issue by justmara** [elastic/logstash-forwarder#270]
clean start of logstash-forwarder build from sources as of 23 sept shows this funny error:

````
2014/09/23 12:35:36.775917 Registrar: precessing 130 events
2014/09/23 12:35:36.776917 registry rotate: rename of .logstash-forwarder to .logstash-forwarder.old - rename .logstash-forwarder .logstash-forwarder.old: The system cannot find the file specified.
2014/09/23 12:35:36.777917 WARNING: (continuing) update of registry returned error: rename .logstash-forwarder .logstash-forwarder.old: The system cannot find the file specified.
````

And really there is no `.logstash-forwarder` file, BUT the `.logstash-forwarder.new` one.
If you manually create this file and start it again, you get new error:

````
2014/09/23 12:42:23.639208 Registrar: precessing 15 events
2014/09/23 12:42:23.640208 registry rotate: rename of .logstash-forwarder to .logstash-forwarder.old - rename .logstash-forwarder .logstash-forwarder.old: The process cannot access the file because it is being used by another process.
2014/09/23 12:42:23.640208 WARNING: (continuing) update of registry returned error: rename .logstash-forwarder .logstash-forwarder.old: The process cannot access the file because it is being used by another process.
````
Really? Another process? It is locked by forwarder itself!
And both these error lines keeps spamming stdout every time new events in file found.

**Comment by j-maly** [comment]
Seeing this as well. Please update on a fix.

**Comment by sledorze** [comment]
Same issue here..

**Comment by adriaangraas** [comment]
Also having the same issue. Is somebody aware of a temporary workaround?

**Comment by huksley** [comment]
Having the same problem

**Comment by harryo1968** [comment]
Hi, sorry to be such a noob.  But how can I manually merge and compile using this fix?  I can I manually copy the changed lines and recompile?

**Comment by mkuzmin** [comment]
@harryo1968 you can always copy files manually, but here is a better approach: https://sethvargo.com/checkout-a-github-pull-request/

**Comment by harryo1968** [comment]
Awesome!  Thanks @mkuzmin !

**Comment by vlaadbrain** [comment]
ping,  whats the ETA on fixing this?

**Comment by jordansissel** [comment]
there is no ETA at this time.

**Comment by radiumx3** [comment]
@jordansissel  there is a PR pending with the fix to this, please take a look at it and concider merging maybe ?

**Comment by ruflin** [comment]
This should be fixed in filebeat (next version of logstash-forwarder) with https://github.com/elastic/filebeat/pull/43 and https://github.com/elastic/filebeat/pull/45

**Comment by ruflin** [comment]
As the next release of logstash-forwarder will be [filebeat](https://github.com/elastic/filebeat), I will close this issue based on the comment above. In case the issue still exists in filebeat, please reopen or open a new issue directly in the filebeat repo.
