### ISSUE TITLE
logstash-forward should not swallow tls handshake errors

### ISSUE THREAD

**Issue by mdaniel** [elastic/logstash-forwarder#271]
If `logstash-forward` is running in "quiet" mode, it treats _all_ output as "verbose" and eats it, but this has the unfortunate side-effect of hiding `Failed to tls handshake with 1.2.3.4 x509: blah blah` messages, which are pretty important.

I am aware of the [other "tls handshake" issues](https://github.com/elasticsearch/logstash-forwarder/issues?q=is%3Aissue+tls+handshake) but this is actually a logging one.

I can appreciate there are different viewpoints on this issue: if the thing isn't working, run it in "verbose" or "debug" mode. The other viewpoint is that all output is not the same, and even in "verbose" mode there are lines that **require** attention and others that are just the traditional definition of verbose.

**Comment by urso** [comment]
lumberjack connection errors are logged with error level in libbeat (new filebeat)
