### ISSUE TITLE
Add documentation around using AWS Elastic Load Balancers

### ISSUE THREAD

**Issue by grahamc** [elastic/logstash-forwarder#274]
There is a misleading thread on the mailing list here that says Lumberjack doesn't support using AWS ELBs: https://groups.google.com/d/msg/logstash-users/JDZ9oH7Nwfs/0piGCH3B-OMJ

It is worth noting that configuring Lumberjack to forward TCP traffic is possible by having the ELB load balance straight TCP, without any knowledge of SSL.

Here are the steps I used to create my load balancer:
![ec2_management_console](https://cloud.githubusercontent.com/assets/76716/4427494/c3311574-45bf-11e4-8409-d248f43925fd.png)
![ec2_management_console](https://cloud.githubusercontent.com/assets/76716/4427508/dd08be5c-45bf-11e4-8635-7f06a4d6b080.png)

I then used this command to generate my SSL certificate:

```
openssl req -x509 -batch -nodes -newkey rsa:2048 -keyout /ssl/key -out /ssl/cert -days 365 -subj '/CN=internal-logstash-abc123.us-west-2.elb.amazonaws.com'
```

And that should do it.

**Comment by mcbain** [comment]
I'm have a simple route53 alias to my internal-elb. The certificate must be created with CN=rout53-domain-name to be accepted by logstash.
Unfortunaly i can't get it working like this.
When using the health check with TCP/5043 loadbalancher, not even the instance gets healthy into the elb.
Does the certificate need to be on the public dns name of the elb?
Even when using simple nginx as health check (which adds the instance to the elb) the simple TCP 5043->5043 tunnel works. 

```
Failed to tls handshake with 10.10.0.206 read tcp 10.10.0.206:5043: i/o timeout
2015/02/14 16:47:53.773164 Connecting to [10.10.0.206]:5043 (xxx.example.com) 
```

**Comment by grahamc** [comment]
I don't understand where nginx is coming in, can you say more, @mcbain? It looks like your security groups are mucked up. IE: the loadbalancer's security group can't access the logstash instance's port 5043, given via the "i/o timeout".

**Comment by mcbain** [comment]
The running nginx was only used as health target to get the instance into the elb, since just tcp 5043 did not work. I read about increasing some elb timeout, will try this tomorrow.

**Comment by grahamc** [comment]
The time out makes no difference here. Did you verify your security groups permit your load balancer access to the logstash servers?



- Graham

**Comment by mcbain** [comment]
@grahamc you are right ... i had a typo in my server-inbound rules for TCP/5042 with VPC access.

**Comment by vankhoa011** [comment]
I added more than two logstash behind ELB. However, There is only one logstash receive traffic .
What's problem ?

**Comment by tbragin** [comment]
After discussion we decided not to document specific setup with various load balancers. 

To be clear, LSF supports its own connection balancing to Logstash:
	* Random load distribution per connection
	* You can specify multiple IPs or DNS name that maps to multiple IPs for Logstash instances

External load balancers can add functionality, such as least connection based balancing, but setup is specific to each vendor, so we can't keep up with documenting the specifics.
