### ISSUE TITLE
Fresh install getting "logstash-forwarder Syntax error: ( unexpected" when running from /opt/logstash-forwarder/bin

### ISSUE THREAD

**Issue by lserman** [elastic/logstash-forwarder#275]
Command I'm running:

```
sudo /opt/logstash-forwarder/bin/logstash-forwarder -config /etc/logstashforwarder/config.json 
```

Exact error:

```
/opt/logstash-forwarder/bin/logstash-forwarder: 1: /opt/logstash-forwarder/bin/logstash-forwarder: Syntax error: "(" unexpected
```

This is from a fresh install of https://github.com/elasticsearch/puppet-logstashforwarder 

```
$config = {
    'logstashforwarder_USER' => 'root',
    'logstashforwarder_GROUP' => 'root',
  }

  class { 'logstashforwarder':
    package_url => 'http://packages.elasticsearch.org/logstashforwarder/debian/pool/main/l/logstashforwarder/logstash-forwarder_0.3.1_amd64.deb',
    servers => ['192.168.50.4:5043'],
    ssl_ca => 'puppet:///modules/role/logstash/logstash-forwarder.crt',
    ensure => present,
    init_defaults => $config,
  }
```

Logstash and Logstash-forwarder are running in separate Vagrant boxes. Any idea what is going on here? I can't find anything.

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by https://github.com/elastic/filebeat/. If this is still an issue with filebeat, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
