### ISSUE TITLE
logstash-forwarder reporting "connection refused" but logstash agents are online

### ISSUE THREAD

**Issue by robin13** [elastic/logstash-forwarder#280]
In my setup a cluster (~120 machines) is sending their events (on average ~5000/second) to another cluster (10 machines) of logstash agents, each set up to listen on one port for logstash-forwarder connections (lumberjack input).

Occasionally a single machine will stop sending its events and entries like this will start popping in the machines syslog every second (ips obscured with a '1')

Oct  8 07:13:04 apm02 logstash-forwarder[23376]: 2014/10/08 07:13:04.997668 Connecting to 1.1.1.1:5044 (es105)
Oct  8 07:13:04 apm02 logstash-forwarder[23376]: 2014/10/08 07:13:04.998409 Failure connecting to 1.1.1.1: dial tcp 1.1.1.1:5044: connection refused

I can see that they are trying all the machines in the cluster (random sequence), and I can confirm that on each of the machines they are trying the logstash agents are running and processing events from other logstash-forwarders.

After about 10 minutes of these log entries, there are no further log entries from logstash-forwarder - it seems that the logstash-forwarder has stopped trying to make a connection and is hanging - when I restart it it immediately connects successfully to a logstash agent and continues sending its events.

Preceding that I also see frequently:
Oct  8 06:23:55 apm02 logstash-forwarder[23376]: 2014/10/08 06:23:55.947080 Registrar received 1000 events
Oct  8 06:24:25 apm02 logstash-forwarder[23376]: 2014/10/08 06:24:25.986106 Read error looking for ack: read tcp 1.1.1.1:5044: i/o timeout
Oct  8 06:24:25 apm02 logstash-forwarder[23376]: 2014/10/08 06:24:25.986255 Setting trusted CA from file: /etc/logstash-forwarder/cluster.crt
Oct  8 06:24:25 apm02 logstash-forwarder[23376]: 2014/10/08 06:24:25.990116 Connecting to 1.1.1.1:5044 (es110)
Oct  8 06:24:26 apm02 logstash-forwarder[23376]: 2014/10/08 06:24:26.054082 Connected to 1.1.1.1
Oct  8 06:24:26 apm02 logstash-forwarder[23376]: 2014/10/08 06:24:26.460071 Registrar received 1000 events

I'm using logstash-forwarder 0.3.1 and logstash 1.4.2

Any ideas what could be going wrong here, and more importantly... how to remedy it?

**Comment by suyograo** [comment]
Closing this, please reopen if the issue still exists
