### ISSUE TITLE
Logstash-forwarder UTF 8 charset issue with VMware Technologies

### ISSUE THREAD

**Issue by gauravchouhan** [elastic/logstash-forwarder#281]
I'm gathering syslogs with logstash-forwarder (Lumberjack) and shipping to Logstash. I'm getting some errors at kibana Dashboard i.e at tags Field & message(_grokparsefailure).
   The below Issue arise when i m doing this setup in VMware Technologies only .When i m using VirtualBox or Physical Server the same setup work fine & Also the logs are readable.  
   I am asking here to see if there is anything I need to do on the Logstash . All comments and ideas are welcomed. Thanks! Details below.
   
   My Elk Stack Server Details:
   Logstash Server ==> logstash-1.4.2
   Elasticsearch   ==> Elasticsearch-1.1.1
   Kibana          ==> Kibana-3.0.1

    Logstash config file: 
    input {
    tcp {
    type => "syslog"
    port => 5000
    }
    }

    filter {
      if [type] == "syslog" {
        grok {
          match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
          add_field => [ "received_at", "%{@timestamp}" ]
          add_field => [ "received_from", "%{host}" ]
        }
        syslog_pri { }
        date {
          match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
        }
      }
    }

    output {
      elasticsearch { host => localhost }
      stdout { codec => rubydebug }
    }

    Logstash-forwarder conf file:
{
  "network": {
    "servers": [ "logstash_server_private_IP:5000" ],
    "timeout": 15
  },
  "files": [
    {
      "paths": [
        "/var/log/messages",
        "/var/log/secure"
       ],
      "fields": { "type": "syslog" }
    }
   ]
}

    Logstash shows these errors:

{
       "message" => "\\u0000/\\u00005\\xC0\\u0011\\xC0\\u0012\\xC0\\u0013\\xC0\\u0014\\u0001\\u0000\\u0000\\e\\u0000\\u0005\\u0000\\u0005\\u0001\\u0000\\u0000\\u0000\\u0000\\u0000",
      "@version" => "1",
    "@timestamp" => "2014-10-08T13:42:33.685Z",
          "host" => "10.11.30.215:59556"
}
{
       "message" => "\x00\b\x00\x06\x00\x17\x00\x18\x00\x19\x00\v\x00\x02\x01\x00",
      "@version" => "1",
    "@timestamp" => "2014-10-08T13:42:49.657Z",
          "host" => "10.11.30.215:59556"
}
{:timestamp=>"2014-10-08T19:12:49.682000+0530", :message=>"Received an event that has a different character encoding than you configured.", :text=>"\\u0016\\u0003\\u0001\\u0000X\\u0001\\u0000\\u0000T\\u0003\\u0001T53\\xA5]\\xC1V/\\xBE\\x86\\xAA\\xCEV\\xF2\\xAB7\\x92\\xB1\\xE3|S\\x83\\xBC\\f\\u0018\\xBE\\u001E\\x98\\xBBb\\xBCF\\u0000\\u0000\\u0010\\u0000\\u0005\\u0000", :expected_charset=>"UTF-8", :level=>:warn}
{:timestamp=>"2014-10-08T19:12:49.687000+0530", :message=>"Received an event that has a different character encoding than you configured.", :text=>"\\u0000/\\u00005\\xC0\\u0011\\xC0\\u0012\\xC0\\u0013\\xC0\\u0014\\u0001\\u0000\\u0000\\e\\u0000\\u0005\\u0000\\u0005\\u0001\\u0000\\u0000\\u0000\\u0000\\u0000", :expected_charset=>"UTF-8", :level=>:warn}
{
       "message" => "\\u0016\\u0003\\u0001\\u0000X\\u0001\\u0000\\u0000T\\u0003\\u0001T53\\xA5]\\xC1V/\\xBE\\x86\\xAA\\xCEV\\xF2\\xAB7\\x92\\xB1\\xE3|S\\x83\\xBC\\f\\u0018\\xBE\\u001E\\x98\\xBBb\\xBCF\\u0000\\u0000\\u0010\\u0000\\u0005\\u0000",
      "@version" => "1",
    "@timestamp" => "2014-10-08T13:42:49.683Z",
          "host" => "10.11.30.215:59557"
}
{
       "message" => "\\u0000/\\u00005\\xC0\\u0011\\xC0\\u0012\\xC0\\u0013\\xC0\\u0014\\u0001\\u0000\\u0000\\e\\u0000\\u0005\\u0000\\u0005\\u0001\\u0000\\u0000\\u0000\\u0000\\u0000",
      "@version" => "1",
    "@timestamp" => "2014-10-08T13:42:49.688Z",
          "host" => "10.11.30.215:59557"
}

**Comment by jordansissel** [comment]
I don't think this is a problem on with lsf; lsf doesn't really worry about UTF-8 and lets logstash deal with it.

**Comment by jordansissel** [comment]
Closing since this is old, idle, and I think best filed against a Logstash plugin specifically - not an lsf problem
