### ISSUE TITLE
invalid syslog format

### ISSUE THREAD

**Issue by bodepd** [elastic/logstash-forwarder#290]
Using version 0.3.1 from the elasticsearch packages, I get very strangely formatted entries in syslog:

````
Oct 22 20:29:09 hostname :09Z hostname logstash-forwarder[16061]: 2014/10/22 20:29:09.835410 Connected to logstash_ip
````

3 strange thing about this entry:

1. it does not place the syslog_program field after the host field
2. it writes :09Z as a field, this appears to be a :, followed by MINUTE, followed by a Z
3. it writes the data a second time in a different format

**Comment by suyograo** [comment]
Dup of #283
