### ISSUE TITLE
logstash-forwarder works on initial "from-beginning" load, then just stops sending new log entries

### ISSUE THREAD

**Issue by brianamccarthy** [elastic/logstash-forwarder#291]
Hello, maybe I'm missing something obvious ...

But I've set up logstash-forwarder in a standard config with the -from-beginning=true switch.  This initially loads the log entries and I can see them on my logstash /elasticsearch server side (in both STDOUT as they load and kibana)

So I know connectivity is there, the logs can be sent, and they make it to elasticsearch.

But after that initial load, the forwarder just stops sending new entries.  I see it recording events on the agent side regularly.

2014/10/22 16:49:59.258594 Registrar received 1 events
2014/10/22 16:50:11.756222 Registrar received 2 events
2014/10/22 16:50:19.257130 Registrar received 7 events
2014/10/22 16:50:26.754008 Registrar received 1 events
2014/10/22 16:50:31.753480 Registrar received 2 events

But they don't get to the logstash server after that initial "from-beginning=true" load ... It loads once the first time, then just seems like it's done ....

Is there a way to troubleshoot this more ?

The conf is very basic:

{
  "network": {
    "servers": [ "XXX.XX.XX.XX:5000" ],
    "timeout": 15,
    "ssl ca": "/etc/pki/tls/certs/forwarder.crt"
  },
  "files": [
    {
      "paths": [
        "/var/log/tomcat/tomcat.log"
       ],
      "fields": { "type": "tomcat" }
    }
   ]
}

I'm running with these options:

/opt/logstash-forwarder/bin/logstash-forwarder -config /etc/logstash-forwarder -from-beginning=true

Any help would be greatly appreciated.

Thanks!

**Comment by tbragin** [comment]
Closing for now, most likely related to the same question as, which we should make more clear in documentation: https://github.com/elastic/logstash-forwarder/issues/323
