### ISSUE TITLE
json parse error due to extra comma in list

### ISSUE THREAD

**Issue by wjimenez5271** [elastic/logstash-forwarder#297]
I was debugging an issue in my config which turned out to be due to a comma at the end of a json list for files being watched:

```
      "paths": [
        "/var/log/messages",
        "/var/log/*.log",
        "/var/log/other",
      ],
```

This proved to be difficult to spot because my [JSON validation tool](http://nerdery.com/json-accelerator) confirmed the config as valid JSON so I didn't suspect the JSON syntax as the culprit till much later on in the debug process. It would improve the user experience if either the JSON parser was more graceful with extra commas in a list or would supply a more informative error message (even something like a static string: 'check for commas after last element in a json list'). Or a line number of where the bad character was found. This is the only error message I got:

```
2014/10/30 16:21:18.849742 Failed unmarshalling json: invalid character ']' looking for beginning of value
2014/10/30 16:21:18.849750 on LoadConfig: invalid character ']' looking for beginning of value
```

Thanks and keep up the good work with logstash-fowarder, its great!

**Comment by josh-padnick** [comment]
@wjimenez5271 Thanks for posting this.  I ran into the same issue and fixed it quickly as a result of your post.

**Comment by wjimenez5271** [comment]
Awesome, glad it was a help!

**Comment by nareshmg** [comment]
sorry but I am not clear...what was the solition or fix ?

I am getting same error and here is my file...

input {
  file {
    path => "C:\software\data.csv"
    #type => "core2"
    start_position => "beginning"    
  }
}
filter {
  csv {
      separator => ","
      columns => ["Date","Open","High","Low","Close","Volume","Adj Close"]
  }
  mutate {convert => ["Open", "float"]}
  mutate {convert => ["High", "float"]}
  mutate {convert => ["Low", "float"]}
  mutate {convert => ["Close", "float"]}
  mutate {convert => ["Volume", "float"]}
}
		output {  
		    elasticsearch {
		        action => "index"
		        host => "localhost"
		        index => "stock"
		        workers => 1
		    }
		    stdout {}
		}

**Comment by jordansissel** [comment]
@nareshmg You said you are getting the same error, but you posted a logstash configuration, not a logstash-forwarder configuration. This seems not right. Can you clarify?

**Comment by nareshmg** [comment]
![image](https://cloud.githubusercontent.com/assets/12221915/7847734/6a790cf0-047a-11e5-833a-675f15ac13d9.png)

**Comment by nareshmg** [comment]
thx,,, I followed this blog to build the same...
http://blog.webkid.io/visualize-datasets-with-elk/

**Comment by jordansissel** [comment]
@nareshmg You are using a logstash configuration with logstash-forwarder. The logstash-forwarder config file format is different from Logstash itself. The error you are getting is expected because you have an invalid configuration file. You should use your configuration file with _Logstash_ only.

**Comment by nareshmg** [comment]
@jordansissel thx for correcting me...downloading logstash now...and trying it out

**Comment by nareshmg** [comment]
@jordansissel now logstash gives the error that says --- 
io/ console not supported; tty will not be manipulated
No Command given

I am able to run Elasticsearch and Kibana on my windows machine but not Logstash

Windows 7 enterprise 64 bit os

thx again !
