### ISSUE TITLE
If CPU profiler is enabled, causing the process to die after 60 seconds, print an error message

### ISSUE THREAD

**Issue by binary1230** [elastic/logstash-forwarder#304]
if the CPU profiler option is enabled, this code runs:

```
        if runProfiler() {
                f, err := os.Create(options.cpuProfileFile)
                if err != nil {
                        log.Fatal(err)
                }
                pprof.StartCPUProfile(f)
                go func() {
                        time.Sleep(60 * time.Second)
                        pprof.StopCPUProfile()
                        panic("done")
                }()
        }
```

as a first time logstash-forwarder user that turned on this option (-cpuprofiler) by mistake (due to a misleading puppet setting in a module I was using), it looked like logstash-forwarder was crashing instead of exiting.

it would be nice if right before the ```panic("done") ```, it printed a message saying "CPU profiler run is now completed, exiting as planned. To disable, remove -cpuprofiler from the command line".  That way at least some text besides "done" is being printed

or something similar.  would've saved me half a day of trying to figure out what was up : )

**Comment by suyograo** [comment]
Fixed in https://github.com/justmara/logstash-forwarder/commit/4677e41b7d2b8cb734f68419141d91efb0c1ece7

**Comment by binary1230** [comment]
thanks!!! good stuff
