### ISSUE TITLE
Registry write permission denied

### ISSUE THREAD

**Issue by stongo** [elastic/logstash-forwarder#305]
I'm having a problem with logstash-forwarder trying to update it's registry. I supervise logstash-forwarder with runit and run it as an unprivileged user, so not sure exactly where it's trying to create the tmp file. I get this error:

`update of registry returned error: open .logstash-forwarder.new: permission denied`

doesn't seem like https://github.com/elasticsearch/logstash-forwarder/blob/master/registrar.go#L40 specifies any directory, but not overly familiar with go, so not sure what the default location for os.Create() would be when no path is specified

should there a configuration item for specifying registry path?

if not, knowing where it's trying to write .logstash-forwarder.new would be helpful

**Comment by ruflin** [comment]
This should be resolved in filebeat through making the registryFile path and name configurable: https://github.com/elastic/filebeat/blob/master/etc/filebeat.yml#L73

**Comment by ruflin** [comment]
As the next release of logstash-forwarder will be [filebeat](https://github.com/elastic/filebeat), I will close this issue based on the comment above. In case the issue still exists in filebeat, please reopen or open a new issue directly in the filebeat repo.
