### ISSUE TITLE
Update registry warning

### ISSUE THREAD

**Issue by wjimenez5271** [elastic/logstash-forwarder#307]
Getting these warnings from logstash:

```
WARNING: (continuing) update of registry returned error: rename .logstash-forwarder.new .logstash-forwarder: no such file or directory
```

What does this mean?

**Comment by ruflin** [comment]
Closing this issue as this should be fix in filebeat which is the next version of logstash-forwarder: https://github.com/elastic/beats/tree/master/filebeat
