### ISSUE TITLE
Support multiline logs

### ISSUE THREAD

**Issue by zerkms** [elastic/logstash-forwarder#309]
So guys, keeping in mind logstash multiline plugin is not thread safe (and from what I understand - is not going to be for a lot of reasons) - any chance the logstash forwarder gets some option to join multiple lines and send a combined single line to the logstash?

The set of multiline plugin rules to distinguish the multiple lines of the same entry seems enough for almost every case.

May be an option to specify a join separator would be useful additionally though.

What do you think?

**Comment by hartfordfive** [comment]
+1, would definitely be useful when it comes to elasticsearch error stack traces.

**Comment by hartfordfive** [comment]
:+1:

**Comment by odyssey4me** [comment]
+1 this would be very useful to distribute the multiline processing out to the log shipper instead of having to do this on the logstash indexer

**Comment by driskell** [comment]
If anyone is in dire need, this feature exists in Log Courier.
https://github.com/driskell/log-courier/blob/stable/docs/codecs/Multiline.md

**Comment by odyssey4me** [comment]
Thanks @driskell - also note that similar support appears to be available in the beaver log shipper: https://github.com/josegonzalez/python-beaver

**Comment by pandujar** [comment]
+1

**Comment by klynch** [comment]
+1

**Comment by gagor** [comment]
+1

**Comment by debraj-manna** [comment]
+1

**Comment by Mrc0113** [comment]
+1

**Comment by cknapp** [comment]
+1

**Comment by prashanthrajagopal** [comment]
+1

**Comment by yancl** [comment]
+1

**Comment by swood** [comment]
Hello.

Is it already done? I still have the same problem with logstash-forwarder.

**Comment by vmcano** [comment]
+1

**Comment by ruflin** [comment]
This isn't implemented but is planned for Filebeat, the next version of logstash-forwarder.  I'm closing this issue so all future comments and inputs can go directly into: https://github.com/elastic/filebeat/issues/89
