### ISSUE TITLE
logstash-forwarder reads and forwards binary files

### ISSUE THREAD

**Issue by vladionescu** [elastic/logstash-forwarder#314]
Using a file glob like /var/log/httpd/*access* results in logstash-forwader reading every access log in that directory, including the old archived logs. When logstash-forwarder sends these binaries to the destination (a logstash instance outputting to ES) the destination gets very confused: logstash gets paid a visit by OOM Killer, and ES spins out of control.

Would it be reasonable to ignore binary files outright? If not, can we add a config file flag enabling this ignore functionality? I can figure something out and send a PR if the above is appropriate.

**Comment by hartfordfive** [comment]
@vladionescu, I'm working on a patch for [issue 89](https://github.com/elasticsearch/logstash-forwarder/issues/89) which will add the "exclude" option to the config files.  Once it's complete, you'll easily be able to exclude files matching patterns such as "/var/log/*.gz".

**Comment by suyograo** [comment]
Dup of https://github.com/elastic/logstash-forwarder/issues/89
