### ISSUE TITLE
forwarder json problem

### ISSUE THREAD

**Issue by stafot** [elastic/logstash-forwarder#316]
At some point my logstash forwarder used to work properly but at some point fail to start with this error message "Failed unmarshalling json: invalid character ']' looking for beginning of value logstash" 

This message appears only if i run forwarder with this command /opt/logstash-forwarder/bin/logstash-forwarder -config="/etc/logstash-forwarder" 
If i run it as a service it fails without any error message, if i restart the service getting this  \* Restarting log shipper logstash-forwarder
start-stop-daemon: warning: failed to kill PID: No such process
   ...done.

The first time stopped forwarder working i found in syslog this message: 
onnection from UDP: [54.194.184.218]:63707->[10.38.143.181]
Nov 21 12:41:38 logstash-forwarder[PID]: 2014/11/21 12:41:38.692517 Read error looking for ack: EOF
Nov 21 12:41:38  logstash-forwarder[PID]: 2014/11/21 12:41:38.692592 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
Nov 21 12:41:38 logstash-forwarder[PID]: 2014/11/21 12:41:38.692827 Connecting to X.X.X.X:5000 (X.X.X.X)
Nov 21 12:41:38 logstash-forwarder[PID]: 2014/11/21 12:41:38.694128 Failure connecting to X.X.X.X: dial tcp X.X.X.X:5000: connection refused

At server side logstash and ES cluster seems to work fine.. 

I found many similar problems with mine but not any solution. 

Any suggestion would be appreciated. 

S.

**Comment by Neetuj** [comment]
ran into this..thanks!

**Comment by jordansissel** [comment]
This is an unfortunate side effect of not using a configuration parser that allows me any ability to influence the error reporting. Sorry for the irritations about this.

For folks who are confused by the errors and invalid JSON, I like to use http://jsonlint.com/ for validating my JSON (you can paste in stuff, click validate, it tells you what's wrong).

**Comment by driskell** [comment]
@jordansissel I found a golang issue that says that the error returned by Json package  is actually a struct containing all line numbering and position of the error: https://groups.google.com/forum/#!topic/golang-nuts/fizimmXtVfc

For reference my Log Courier issue with more info and linked PR with how I approached reporting in Log Courier: https://github.com/driskell/log-courier/issues/102
