### ISSUE TITLE
SIGTERM should allow registrar to finish writing

### ISSUE THREAD

**Issue by zvikagart** [elastic/logstash-forwarder#328]
I notice that when sending a SIGTERM, logstash-forwarder will sometimes exit with a corrupted (semi-written) .logstash-forwarder.new file. I therefore suspect that when I start logstash-forwarder again the registrar reads old offset information and the forwarder resends some log lines.
It would be nice if the forwarder could perform a graceful shutdown, at least upon SIGTERM, SIGINT signals.

Some background: I'm using a dockerized logstash-forwarder to automatically ship container logs (stdout/stderr). I'm using docker-gen to generate forwarder config from the list of running containers and then restart the forwarder. I am seeing the above problem on a daily basis now.

**Comment by jordansissel** [comment]
@zvikagart I"m pretty sure `.logstash-forwarder.new` isn't ever read from, it's a temporary file written to with the intent of using it to atomically update `.logstash-forwarder`. Do you find this is otherwise?

**Comment by zvikagart** [comment]
No, you're absolutely right. But a graceful shutdown will complete the `.logstash-forwarder` file update so we won't end up sending duplicate log lines.

**Comment by jordansissel** [comment]
"graceful shutdown" is a terrible misnomer. I'm going to update the ticket name.

**Comment by jordansissel** [comment]
We can look into a "finish acknowledging the current transmitted payload" solution, but for the short term, can you describe why you need to restart logstash-forwarder so frequently? If it's just to add new files, why not just use wildcards to look for new files automatically?

**Comment by zvikagart** [comment]
I described my use case in the initial comment. I generate logstash-forwarder configuration dynamically from the list of running docker containers. Every container start/stop regenerates the config and reloads the forwarder.

Here's what a generated config looks like:
```
{
    "files": [
        
        {
            "paths": ["/var/lib/docker/containers/96cc8053bc967ec2aa8583c8ef6a8aa424403d96b8d246d7de3aa51fc3c52d16/96cc8053bc967ec2aa8583c8ef6a8aa424403d96b8d246d7de3aa51fc3c52d16-json.log"],
            "fields": {
                "type": "nginx-log",
                "tags": "nginx,docker"
            }
        }
        
        ,{
            "paths": ["/var/lib/docker/containers/201331ef466811b50b9a476c35016786d54041e5064bf804aae3f1c330b1813f/201331ef466811b50b9a476c35016786d54041e5064bf804aae3f1c330b1813f-json.log"],
            "fields": {
                "type": "foo-log",
                "tags": "foo,docker"
            }
        }
        
        ,{
            "paths": ["/var/lib/docker/containers/8feaae2c3c171f4fe336774ac2658017a1692503e0449d057530757a88daadde/8feaae2c3c171f4fe336774ac2658017a1692503e0449d057530757a88daadde-json.log"],
            "fields": {
                "type": "bar-log",
                "tags": "bar,docker"
            }
        }
        
        ,{
            "paths": ["/var/lib/docker/containers/3cf940428f7073979c183382f60c8b820237135a1f23d7d474f713dc2ebc14a3/3cf940428f7073979c183382f60c8b820237135a1f23d7d474f713dc2ebc14a3-json.log"],
            "fields": {
                "type": "baz-log",
                "tags": "baz,docker"
            }
        }
}
```

Can I use wildcards and still retain type/tag information?

**Comment by driskell** [comment]
If it helps until LSF has this (or the replacement occurs), Log Courier has both graceful shutdown and config reload.

**Comment by jordansissel** [comment]
>  I am seeing the above problem on a daily basis now.

What problem, though? The content of .logstash-forwarder.new is not documented nor is it a user-servicable part. If it appears corrupt or partially-written after shutdown, I agree this is an indication that we could do better on some shutdown, but what's the negative impact? How does it impact your use? What behavior isn't working?

**Comment by timove** [comment]
I have a setup, where I read logs from stdin. I used to kill the logstash-forwarder when the log source exited. This led to lost messages unless I postponed the termination of the logstash-forwarder another 5s, the current idleTimeout.  In this situation a "graceful shutdown" would be better.

**Comment by ruflin** [comment]
There is now a `shutdown_timeout` config option in filebeat which should help with this issue. Please upgrade to filebeat 5.0. Closing this issue.
