### ISSUE TITLE
Lumberjack chokes on massively long line

### ISSUE THREAD

**Issue by br0ch0n** [elastic/logstash-forwarder#33]
I have Lumberjack eating a python log.  It would spontaneously stop sending traffic to logstash (but not crash, process is still running).  I've tracked it down to the fact that it hits a single absurdly long line in my log file.  Restarting lumberjack makes it resume from current time (not from where it left off, though I believe LJ doesn't track its place right now?)

I've exported and measured the long line in question:

me@Server:~# wc longline.txt    
    1  1453 27840 longline.txt

I'm assuming this is too large for LJ to handle, but it would be nice for it to handle it gracefully rather than silently hang.

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by webmat** [comment]
Haha nope! That was the C version :-) You can close, as far as I'm concerned.

**Comment by jordansissel** [comment]
Sweet, <3
