### ISSUE TITLE
Difference in behavior on 32 bit vs 64 bit TLS cert handling

### ISSUE THREAD

**Issue by cteodorski** [elastic/logstash-forwarder#331]
Multiple machines running identical config and identical cert.  Some running 64 bit versions and some running 32 bit versions.    The 64 bit are humming along just fine.  The 32 bit machines are all reporting the following:

Dec 14 13:01:45 <servername> logstash-forwarder[549]: 2014/12/14 13:01:45.022439 Connecting to [x.x.x.x]:5000 (x.x.x.x) 
Dec 14 13:01:45 <servername> logstash-forwarder[549]: 2014/12/14 13:01:45.112432 Failed to tls handshake with x.x.x.x x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

**Comment by suyograo** [comment]
Closing this since there has been no responses. Please reopen if you disagree
