### ISSUE TITLE
Failed to TLS handshake occurs after arbitrary time, restarting logstash fixes

### ISSUE THREAD

**Issue by driskell** [elastic/logstash-forwarder#346]
Related to initial report by @myatu in #91

I've just remembered an issue I saw with log courier with stalling on my own systems. After a while, all of a sudden, new clients couldn't connect and would start reporting handshake timeouts.

I think if a single problematic client (or malicious client) pauses during handshake, the accept call in server.rb sticks trying to read to do the TLS handshake. No other connections are accepted or handshake handled until this finishes as its single threaded

I debugged the issue by sending SIGQUIT to Jruby to get Java stack trace and repeating it periodically. You can see a connection in OpenSSL accept stuck and blocking connection accept loop if it's this issue. Restarting logstash fixes it as it ends that attempt to connect. Eventually though the problematic client triggers it again.

My root cause was a single dodgy remote firewall/balancer dropping connections mid handshake from a single client.

I solved it in Log Courier by moving the TLS handshake to the client thread:
https://github.com/driskell/log-courier/commit/f5330eb2e2cb9da34850352feff0ebb0627be273

**Comment by karthik87** [comment]
@driskell 
I have a strange issue where in my logstash forwarder connects to the logstash server only when I reboot my instance running the forwarder. When I run the docker first time, i just get the following,
Failure connecting to x.x.x.x dial tcp x.x.x.x:5043: i/o timeout

Then when I issue reboot and again run the same docker its connected and can ship logs smoothly.
But I can restart my production servers this easily. So I am stuck here.

Is it anything related to firewall or iptables?

**Comment by driskell** [comment]
Closing as the code for lumberjack has moved.
