### ISSUE TITLE
lsf loses state of some files

### ISSUE THREAD

**Issue by AntonStoeckl** [elastic/logstash-forwarder#349]
I'm updating my issue as when trying to find a way to replay old logs I found an issue.

I'm on Ubuntu 14.04 and installed from deb repository:
http://packages.elasticsearch.org/logstashforwarder/debian

My issue seems related to #350

My config has two files:

```bash
{
  "network": {
    "servers": [ "server:5000" ],
    "timeout": 15,
    "ssl ca": "/etc/pki/tls/certs/logstash-forwarder.crt"
  },
  "files": [
    {
      "paths": [
        "/var/log/nginx/access.log"
       ],
      "fields": { "type": "nginx-access", "application": "geolocation" }
    },
    {
      "paths": [
        "/var/log/nginx/error.log"
      ],
      "fields": { "type": "nginx-error", "application": "geolocation" }
    }
  ]
}
```

But the .logstash-forwarder file most time only has one file:

```bash
{
  "/var/log/nginx/access.log":
  {
    "source":"/var/log/nginx/access.log",
    "offset":19138095,
    "inode":265743,
    "device":64769
  }
}
```

Sometimes the other file (error.log) appears in the .logstash-forwarder file, so it seems this file only contains parsed files where the harvester is behind!? I can see the same effect on other servers running lsf (with more files in the config). Only files with heavy writes constantly show up on the state file.

Now when I stop lsf there is a good chance that the state of the error.log file is currently not tracked in the .logstash-forwarder file.

When I restart lsf after a while I can see that the events logged in the error.log between stop and start are missing in elasticsearch.

syslog shows:

```bash
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.352975 Loading registrar data
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.353215 Loading registrar data
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.353326 Launching harvester on new file: /var/log/nginx/error.log
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.353406 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.353784 Connecting to 185.48.117.171:5000 (185.48.117.171) 
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.353894 Starting harvester at position 47372928: /var/log/nginx/access.log
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.353968 Current file offset: 47372928
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.354136 Starting harvester: /var/log/nginx/error.log
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.354228 Current file offset: 7203285
Jan 17 00:52:48 geolocation-proxy :48+01:00 on-proxy logstash-forwarder[59526]: 2015/01/17 01:52:48.442312 Connected to 185.48.117.171
```

So indeed, the harvester thinks that error.log is a new file and starts at the end of the file.

Best regards, Anton

**Comment by ruflin** [comment]
@AntonStoeckl I'm currently looking at this issue and trying to find out by what it is caused. Does this issue still exist? 
If the harvester restart I assume the file information (inode / device) changed. This means a new file was created. Are these files on a shared volume or something simliar?

**Comment by driskell** [comment]
This is with an older version of the logstash-forwarder. Before 0.4 it would only ever write the state for a single file - it was fixed here: https://github.com/elastic/logstash-forwarder/commit/140880a0634a7e5c3cbf6551d3abd7608372ea85#diff-d2db8748ea2c0b302ff9ec8636bbd000

**Comment by ruflin** [comment]
@driskell Thanks for the comment.
@AntonStoeckl I will close this issue. Please reopen if the problem still exists.
