### ISSUE TITLE
Support for storing client IP in lumberjack server

### ISSUE THREAD

**Issue by stanhu** [elastic/logstash-forwarder#352]
I noticed that the Lumberjack server, unlike the TCP server, does not store the client IP in an event when it receives data. This would be incredibly helpful for me to log where the events are coming from without having to make each client request its external IP. Is there a reason this isn't supported?

**Comment by jordansissel** [comment]
The ruby server code for this was moved to elastic/ruby-lumberjack

**Comment by jordansissel** [comment]
Thanks for your efforts here! Can you open this against elastic/ruby-lumberjack? I'm in favor of having this feature.
