### ISSUE TITLE
-syslog not logging to syslog

### ISSUE THREAD

**Issue by dlangille** [elastic/logstash-forwarder#355]
From https://groups.google.com/forum/#!topic/logstash-users/A_FBYj9C-6U

I am using logstash-forwarder-0.3.1.20140829 on FreeBSD 9.3-RELEASE-p5

I'd like logstash-forwarder to log, to either syslog or a file.

I've tried various options with -debug, -syslog, and --log-to-syslog

Based on output such as this, I've concluded that -syslog and --log-to-syslog are identical:

$ sudo /usr/local/bin/logstash-forwarder -config=/usr/local/etc/logstash-forwarder.conf -log-to-syslog=true -debug=true 
2014/12/08 02:20:51.029255 --- options -------
2014/12/08 02:20:51.029276 config-file: /usr/local/etc/logstash-forwarder.conf
2014/12/08 02:20:51.029281 idle-timeout: 5s
2014/12/08 02:20:51.029284 spool-size: 1024
2014/12/08 02:20:51.029287 harvester-buff-size: 16384
2014/12/08 02:20:51.029289 --- flags ---------
2014/12/08 02:20:51.029291 tail (on-rotation): false
2014/12/08 02:20:51.029293 use-syslog: true
2014/12/08 02:20:51.029296 verbose: false
2014/12/08 02:20:51.029298 debug: true

Nothing is appearing anywhere in /var/log/*

Is this expected?

FWIW, In random desperation, I've tried adding this to /etc/syslog.conf to get something:

. /var/log/logstash-forwarder.log

Still, nothing.

**Comment by magnusbaeck** [comment]
Must be a FreeBSD-specific problem. It certainly works on Linux:

    $ ./logstash-forwarder -config test.config -syslog & ; sleep 3 ; kill %1 ; tail -n 3 /var/log/syslog
    [1] 29023
    [1]  + exit 2     ./logstash-forwarder -config test.config -syslog
    May 17 21:37:32 hallonet logstash-forwarder[29023]: 2015/05/17 21:37:32.801776 Failure connecting to ::1: dial tcp [::1]:5043: connection refused
    May 17 21:37:33 hallonet logstash-forwarder[29023]: 2015/05/17 21:37:33.802160 Connecting to [::1]:5043 (localhost)
    May 17 21:37:33 hallonet logstash-forwarder[29023]: 2015/05/17 21:37:33.802270 Failure connecting to ::1: dial tcp [::1]:5043: connection refused

Which version of the Go compiler did you use when compiling?

**Comment by dlangille** [comment]
I don't know, I don't find go here:

$ pkg info -x go
gobject-introspection-1.42.0
p5-HTTP-Negotiate-6.01_1
pango-1.36.8_1

**Comment by dlangille** [comment]
It looks to have been go-1.4.2

Does this help?

**Comment by tbragin** [comment]
Appears to be a dup of https://github.com/elastic/logstash-forwarder/issues/137

**Comment by jordansissel** [comment]
I don't know what freebsd's default syslog configuration is, but LSF uses the syslog `Informational` severity with a facility of `Daemon`. Can you check if your syslog configuration will write to files these messages received at this severity+facility? That's my guess what is going on.

**Comment by dlangille** [comment]
I added this entry to /etc/syslog.conf on a FreeBSD 9.3 machine:

daemon.*,*.notice;authpriv.none;kern.debug;lpr.info;mail.crit;news.err  /var/log/messages

I restarted syslogd

I ran this:

sudo /usr/local/bin/logstash-forwarder -config=/usr/local/etc/logstash-forwarder.conf -log-to-syslog=true -quiet=false

Nothing appeared on /var/log/messages

I ran this instead:

$ sudo /usr/local/bin/logstash-forwarder -config=/usr/local/etc/logstash-forwarder.conf -log-to-syslog=true -quiet=false -syslog=false
2015/08/15 23:42:32.770886 	--- options -------
2015/08/15 23:42:32.770912 	config-arg:          /usr/local/etc/logstash-forwarder.conf
2015/08/15 23:42:32.770919 	idle-timeout:        5s
2015/08/15 23:42:32.770922 	spool-size:          1024
2015/08/15 23:42:32.770926 	harvester-buff-size: 16384
2015/08/15 23:42:32.770928 	--- flags ---------
2015/08/15 23:42:32.770931 	tail (on-rotation):  false
2015/08/15 23:42:32.770934 	log-to-syslog:          false
2015/08/15 23:42:32.770937 	quiet:             false
2015/08/15 23:42:32.770979 {
  "network": {
    "servers":         [ "metrics.int.unixathome.org:5043" ],

.... etc

**Comment by magnusbaeck** [comment]
> `$ sudo /usr/local/bin/logstash-forwarder -config=/usr/local/etc/logstash-forwarder.conf -log-to-syslog=true -quiet=false -syslog=false`

But you're disabling syslog logging with `-syslog=false`. Change that to `syslog=true` and remove `-log-to-syslog=true` (that option is deprecated in favor of `-syslog`).

**Comment by dlangille** [comment]
Nothing turns up in ```/var/log/messages``` with this command:

```shell
$ sudo /usr/local/bin/logstash-forwarder -config=/usr/local/etc/logstash-forwarder.conf -quiet=false -syslog=true
```

**Comment by jordansissel** [comment]
I'll try to reproduce this on freebsd. No ETA.

I tried to do this just now, but my network is quite flakey so I am forced to give up on this work right now.

**Comment by jordansissel** [comment]
If you could provide full `truss -f` (or if truss doesn't exist anymore, maybe dtruss?) of logstash-forwarder during a time you expect it to be logging and also on startup, this would help.

**Comment by dlangille** [comment]
I intend to run syslogd in debug mode and see what's going on.

**Comment by dlangille** [comment]
I have a solution.

```shell
touch /var/log/logstash-forwarder
chmod 600 /var/log/logstash-forwarder
```

Add this to ```/etc/newsyslog```

```shell
!logstash-forwarder
*.*						/var/log/logstash-forwarder.log
```

Add this to ```/etc/rc.conf```

```shell
logstash_forwarder_enable="YES"
logstash_forwarder_flags="-quiet=false -syslog=true"
```

This gives you:

```shell
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656846 	--- options ------- 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656882 	config-arg:          /usr/local/etc/logstash-forwarder.conf 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656896 	idle-timeout:        5s 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656904 	spool-size:          1024 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656911 	harvester-buff-size: 16384 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656918 	--- flags --------- 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656926 	tail (on-rotation):  false 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656933 	log-to-syslog:          true 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656940 	quiet:             false 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.656982 {   "network": {     "servers":         [ "metrics.int.unixathome.org:5043" ], #    "ssl certificate": "/usr/local/etc/ssl/wp.freebsddiary.org.crt", #    "ssl key":         "/usr/local/etc/ssl/wp.freebsddiary.org.nopassword.key",     "ssl ca":          "/usr/local/etc/ssl/sub.class2.server.ca.pem"   },   "files": [     {       "paths": [          "/var/log/messages"       ],       "fields": { "type": "syslog" }     },     {       "paths": [          "/var/log/wp.freebsddiary.org-access.log"       ],       "fields": { "type": "apache", "vhost": "wp.freebsddiary.org" }     }   ] }  
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.657415 Loading registrar data from //.logstash-forwarder 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.657473 Waiting for 2 prospectors to initialise 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.657532 Resuming harvester on a previously harvested file: /var/log/messages 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.657726 Registrar will re-save state for /var/log/messages 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.657763 Registrar will re-save state for /var/log/wp.freebsddiary.org-access.log 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.657828 harvest: "/var/log/messages" position:85735 (offset snapshot:85735) 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.657898 Resuming harvester on a previously harvested file: /var/log/wp.freebsddiary.org-access.log 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.658008 harvest: "/var/log/wp.freebsddiary.org-access.log" position:80339 (offset snapshot:80339) 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.658043 All prospectors initialised with 2 states to persist 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.658068 Setting trusted CA from file: /usr/local/etc/ssl/sub.class2.server.ca.pem 
Aug 18 13:27:12 freebsddiary logstash-forwarder[68980]: 2015/08/18 13:27:12.659055 Connecting to [10.0.0.1]:5043 (metrics.int.unixathome.org)  
```

**Comment by dlangille** [comment]
Next step: remove extraneous timestamp from log message.  While researching this issue, I found a reference to that.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better! 

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
