### ISSUE TITLE
fields and paths are mixed

### ISSUE THREAD

**Issue by antofran22** [elastic/logstash-forwarder#358]
I probably got something wrong somewhere. But what hat happens for me is that certain events (log entries) have wrong tags. This did not happen for every event, just for some.
Chain:
<pre>
logstash-forwarder -> (input lumberjack) logstash (gelf output) -> graylog2  
</pre>

forwarder installation:
* cloned from git
<pre>
git describe --tags
v0.3.1-58-g19ce4a1
</pre>
* built with go

forwarder config:
<pre>
{
  "network": {
    "servers": [ "elk.xx.ch:9111" ],
    "ssl certificate": "/usr/local/xx/pki/tls/cert/selfsigned.crt",
    "ssl key": "/usr/local/xx/pki/tls/private/selfsigned.key",
    "ssl ca": "/usr/local/xx/pki/tls/cert/selfsigned.crt" 
  },
  "files": [
    {
      "paths": [ 
        "/usr/local/xx/var/logs/xx.log" 
      ],
      "fields": { "type": "APPLICATION" }
    },
    {
      "paths": [ 
        "/usr/local/xx/var/logs/httpd-access.log" 
      ],
      "fields": { "type": "WEBSERVER" }
    }
  ]
}
</pre>

type is set in the forwarder and logType in the indexer (logstash) to make sure it is not the index who messes it up.

<pre>
filter{
  if [type] == "APPLICATION" {
     noop{
        add_field => { "logType" => "as"}
     }
  }
}
</pre>

The message below has type APPLICATION but it is as http-access log message (I grepped and it only occures in the access logs, not xx). It also claims to have path /usr/local/xx/var/logs/xx.log

<pre>
10.0.2.2 - - [21/Jan/2015:16:20:01 +0100] "GET /api/core/v3/contents?count=1&fields=id HTTP/1.1" 200 117 0 1 "http://localhost:8080/exc/tools" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36" "application/json" 4D77CA6CF1F1194C17CBA07B17E364F6" 
</pre>

I could provide more information regarding setup, or sniff the traffic to get the packets sent. But as I said, I probably got something wrong on the way rather than this is a bug. 

I tested the same setup using logstash as a forwarder and I did not experience this problem.

gruss,
francis

**Comment by jordansissel** [comment]
Can you attach your full logstash config?

**Comment by antofran22** [comment]
It is not 100% the configuration I had ( I dropped the virtual box) but it is pretty the same. If needed I can set it up once more. 
```
input {
  lumberjack {
    # The port to listen on
    port => 9111

    # The paths to your ssl cert and key
    ssl_certificate => "/etc/pki/tls/cert/selfsigned.crt" 
    ssl_key => "/etc/pki/tls/private/selfsigned.key" 
  }
}

filter{
  if [type] == "APPLICATION" {
	 noop{
		add_field => { "logType" => "as"}
	 }
  }
  
  if [type] == "WEBSERVER" {
	 noop{
		add_field => { "logType" => "ws"}
	 }
  }
}

output {
  #test elasticsearch and kibana
  elasticsearch { 
	host => "192.168.33.60" 
	protocol => "http" 
	port => "9200" 
  }

  #test elasticsearch with graylog
 gelf {
    host => "192.168.33.40"
    port => "12201"
    short_message => "test"
   }
}
```

**Comment by michio-nikaido** [comment]
I've seen this too

**Comment by michio-nikaido** [comment]
RESOLVED:   After recompiling logstash-forwarder and adding a bunch of debug emits, it became obvious that the correct info was being sent by logstash-forwarder.

It turned out that the issue was on the logstash lumberjack input plugin where I had included a 

```
   codec => multiline {
       pattern => "^\s"
       what => "previous"
    }
```

which appeared to be the source of the problem.  My log lines weren't (as far as I could tell) matching the multiline regexp, but removing this codec got things working as I would have expected.

**Comment by UlrichEckhardt** [comment]
Hello Michio Nikaido, your problems with the multiline codec is probably not the issue here, as the setup in question doesn't use it. Still, check out https://github.com/elastic/logstash/issues/2925 for a workaround for the broken multiline codec. In short, use the multiline filter instead of the multiline codec.

**Comment by alekseymykhailov** [comment]
>In short, use the multiline filter instead of the multiline codec.

unfortunately it will not work if logstash started with more than 1 filter worker

it crashes with:
```
Error: Cannot use more than 1 filter worker because the following plugins don't work with more than one worker: multiline
```

**Comment by acchen97** [comment]
Resolved.
