### ISSUE TITLE
Repeated `broken pipe` errors from forwarder.

### ISSUE THREAD

**Issue by shearn89** [elastic/logstash-forwarder#361]
I have logstash-forwarder reading files and sending to Logstash using SSL certificates. The forwarder that's on the same box as the Logstash instance works fine, but the forwarder on another box seems to constantly lose it's connection:

    Loading client ssl certificate: /etc/logstash/forwarder.crt and /etc/logstash/forwarder.key
    Setting trusted CA from file: /etc/logstash/forwarder.crt
    Connecting to [192.168.1.101]:2003 (logging.local.net)
    Connected to 192.168.1.101
    Registrar received 1 events
    Socket error, will reconnect: write tcp 192.168.1.101:2003: broken pipe

This repeats over and over again, sometimes almost my 'timeout' value apart, mostly much quicker (a second or three).

If I restart the forwarder, sometimes I get instead the error:

    Read error looking for ack: EOF

Any help would be much appreciated!

**Comment by jordansissel** [comment]
What service logstash-forwarder talking to? Is that service online? Is the network healthy?

**Comment by shearn89** [comment]
Firewall has port 2003 open on both ends, logstash-forwarder on `.102` is talking to logstash and it is online. On the logstash node (`.101`), the forwarder works fine. I can ping and ssh fine between both boxes in both directions.

**Comment by jordansissel** [comment]
How are oyu checking if Logstash is online? Is your firewall stateful and dropping stale/idle connections?

**Comment by shearn89** [comment]
I did `service logstash status`, which reports it's online. The firewall is `iptables`.
Looking at the output of `netstat -pant`, there are a large number of connections from one of my other nodes to the Logstash port. If I stop the forwarder process on this node, the number of connections drops back down to a normal level and the errors disappear...

I think maybe I have some network config wrong?

**Comment by jordansissel** [comment]
Sounds like there's a connection leak; could be a known issue that we'll fix shortly, but I need more information.

Are there no other logs from logstash-forwarder?

**Comment by shearn89** [comment]
Nope, the log is pretty sparse: date/time/message, but not even any level names such as error/warning/debug. Is there a setting to bump up the log level?

**Comment by jordansissel** [comment]
Nope; default is "log everything"

**Comment by jordansissel** [comment]
Any chance you can attach the last 100 (or 1000) lines around your error?

**Comment by jordansissel** [comment]
Specifically the first time you see the error during the program's life.

**Comment by shearn89** [comment]
It's on a seperate system with no internet access unfortunately. I can see the usual config load, starting harvesters, "registrar will re-save state..." messages, then "All prospectors initialised with 5 states to persist", followed very quickly by the `broken pipe` message, on the very first time it tries to send to Logstash:

    Started harvester...
    Loading client ssl...
    Setting trusted CA...
    connecting to [192.168.1.101]:2003 (logging.local.net)
    Connected to 192.168.1.101
    Socket error, will reconnect... broken pipe
    # Same setting/connecting/connected messages, then
    Read error looking for ack: EOF

**Comment by jordansissel** [comment]
Can you 'telnet 192.168.1.101 2003' ? Does it connect? How about `openssl s_client -connect 192.168.1.101 2003` ?

**Comment by shearn89** [comment]
I've flushed all the routes etc on the gateway node, I can telnet and run the openssl command apparently fine. If I restart the forwarder that I previously stopped, all seems well.

Could I have accidentally looped something with the routing and effectively fork-bombed my network sockets? (if that makes sense)

**Comment by jordansissel** [comment]
When this happens, can you post here the output of `lsof -nPp XXXXXXXX` where `XXXXXXXX` is the pid of logstash-forwarder?

**Comment by jordansissel** [comment]
Anonymizing the result is OK.

**Comment by shearn89** [comment]
If it happens again, at the moment all is working fine (and I'm not sure how to get it back to the error state). I'll keep an eye on it this afternoon.

**Comment by efremmoraes** [comment]
Hi, I have the same problem as OP:

openssl s_client works fine. Telnet is ok and and doesn't drop. 

The thing is that, despite the error messages, logstash seems to work fine. All these messages get saved.

I'm testing on localhost:

```
Feb  9 21:24:24 logs logstash-forwarder[1683]: 2015/02/09 21:24:24.967761 Connecting to [127.0.0.1]:5000 (logs.eramo.com.br)
Feb  9 21:24:25 logs logstash-forwarder[1683]: 2015/02/09 21:24:25.019817 Connected to 127.0.0.1
Feb  9 21:24:25 logs logstash-forwarder[1683]: 2015/02/09 21:24:25.020894 Registrar: processing 5 events
Feb  9 21:24:31 logs logstash-forwarder[1683]: 2015/02/09 21:24:31.467147 Socket error, will reconnect: write tcp 127.0.0.1:5000: broken pipe
Feb  9 21:24:32 logs logstash-forwarder[1683]: 2015/02/09 21:24:32.467471 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
Feb  9 21:24:32 logs logstash-forwarder[1683]: 2015/02/09 21:24:32.467846 Connecting to [127.0.0.1]:5000 (logs.eramo.com.br)
Feb  9 21:24:32 logs logstash-forwarder[1683]: 2015/02/09 21:24:32.515807 Connected to 127.0.0.1
Feb  9 21:24:32 logs logstash-forwarder[1683]: 2015/02/09 21:24:32.516832 Registrar: processing 5 events
```

And here is the lsof:

```
lsof -nPp 1683
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF   NODE NAME
logstash- 1683 root  cwd    DIR               0,16      740   6098 /run
logstash- 1683 root  rtd    DIR              202,1     4096      2 /
logstash- 1683 root  txt    REG              202,1  6013552 156803 /opt/logstash-forwarder/logstash-forwarder
logstash- 1683 root  mem    REG              202,1    47712 396047 /lib/x86_64-linux-gnu/libnss_files-2.19.so
logstash- 1683 root  mem    REG              202,1  1845024 396013 /lib/x86_64-linux-gnu/libc-2.19.so
logstash- 1683 root  mem    REG              202,1   141574 396066 /lib/x86_64-linux-gnu/libpthread-2.19.so
logstash- 1683 root  mem    REG              202,1   149120 396003 /lib/x86_64-linux-gnu/ld-2.19.so
logstash- 1683 root    0u   CHR                1,3      0t0   5430 /dev/null
logstash- 1683 root    1u   CHR                1,3      0t0   5430 /dev/null
logstash- 1683 root    2u   CHR                1,3      0t0   5430 /dev/null
logstash- 1683 root    3u  unix 0xffff88003d5f4d00      0t0  11759 socket
logstash- 1683 root    4u  0000                0,9        0   5385 anon_inode
logstash- 1683 root    5r   REG              202,1   599381 149598 /var/log/syslog
logstash- 1683 root    6r   REG               0,16      191  11701 /run/.logstash-forwarder (deleted)
logstash- 1683 root    7r   REG              202,1    38149 149602 /var/log/auth.log
logstash- 1683 root    8u  IPv4              12083      0t0    TCP 127.0.0.1:34514->127.0.0.1:5000 (CLOSE_WAIT)
logstash- 1683 root    9r   CHR                1,9      0t0   5435 /dev/urandom
```

As it is working, I also get ESTABLISHED:

```
logstash- 1683 root    8u  IPv4              13100      0t0    TCP 127.0.0.1:34679->127.0.0.1:5000 (ESTABLISHED)
```

The config file:

```
{
  "network": {
    "servers": [ "XXXXXXXX:5000" ],
    "timeout": 15,
    "ssl ca": "/etc/pki/tls/certs/logstash-forwarder.crt"
  },
  "files": [
    {
      "paths": [
        "/var/log/syslog",
        "/var/log/auth.log"
       ],
      "fields": { "type": "syslog" }
    }
   ]
}
```

**Comment by jordansissel** [comment]
> Socket error, will reconnect: write tcp 192.168.1.101:2003: broken pipe

This means the write was interrupted in flight. Either Logstash (the receiver) closed it because logstash was shutdown while reading, or some kind of network problem occurred to cause this.

Please describe the network path taken between lsf and logstash including any interference devices such as networked or local firewalls.

**Comment by leitu** [comment]
Same issue here. the telnet works fine, we didn't have vlan tagged, all in one subnent, no package dropped.
but before we got Socker error, we were having *Read error looking for ack: EOF*

**Comment by rchman** [comment]
I was having a similar issue. It was due to one machine having an old certificate and the logstash host then deciding to disconnect everyone, including the local logstash-forwarded. Finding the old cert and updating it resolved my issue.

This just repeated over and over:

Feb 23 17:08:43 lg1 :43-08:00 ash-forwarder[22493]: 2015/02/23 17:08:43.184108 Registrar received 5 events
Feb 23 17:08:49 lg1 :49-08:00 ash-forwarder[22493]: 2015/02/23 17:08:49.625239 Socket error, will reconnect: write tcp ipaddress:5000: broken pipe
Feb 23 17:08:50 lg1 :50-08:00 ash-forwarder[22493]: 2015/02/23 17:08:50.625656 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
Feb 23 17:08:50 lg1 :50-08:00 ash-forwarder[22493]: 2015/02/23 17:08:50.627188 Connecting to ipaddress:5000 (ipaddress) 
Feb 23 17:08:50 lg1 :50-08:00 ash-forwarder[22493]: 2015/02/23 17:08:50.682474 Connected to ipaddress
Feb 23 17:08:50 lg1 :50-08:00 ash-forwarder[22493]: 2015/02/23 17:08:50.683530 Registrar received 5 events

**Comment by eamocanu** [comment]
You might try adding your logstash server to /etc/hosts

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better! 

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
