### ISSUE TITLE
DNS lookup failure error

### ISSUE THREAD

**Issue by BeniGal** [elastic/logstash-forwarder#371]
I have Logstash forwarder compiled for Android (linux/arm) and placed on a rooted Nexus 7 to /data/local/tmp folder. There is a logcat.log from the device' logcat output.

My logstash-forwarder.conf looks like:
```
{
  "network": {
    "servers": [ "1.2.3.4:5043" ],
    "ssl certificate": "./logstash-forwarder.crt",
    "ssl key": "./logstash-forwarder.key",
    "ssl ca": "./logstash-forwarder.crt",
	"timeout": 15
  },
  "files": [
    {
      "paths": [ 
        "/sdcard/logcat.log"
      ],
      "fields": { "type": "nexus7" }
    }
  ]
}
```

But after I start it, I have the following error:
```
2015/02/11 10:04:41.210977 DNS lookup failure "1.2.3.4": lookup 1.2.3.4: invalid domain name
```

What could be the problem?

The whole output:
```
2015/02/11 10:49:21.444080 	--- options -------
2015/02/11 10:49:21.446756 	config-arg:          logstash-forwarder.conf
2015/02/11 10:49:21.449657 	idle-timeout:        5s
2015/02/11 10:49:21.451800 	spool-size:          1024
2015/02/11 10:49:21.454327 	harvester-buff-size: 16384
2015/02/11 10:49:21.456449 	--- flags ---------
2015/02/11 10:49:21.458571 	tail (on-rotation):  false
2015/02/11 10:49:21.460643 	log-to-syslog:          false
2015/02/11 10:49:21.462367 	quiet:             false
2015/02/11 10:49:21.464993 {
  "network": {
    "servers": [ "1.2.3.4:5043" ],
    "ssl certificate": "./logstash-forwarder.crt",
    "ssl key": "./logstash-forwarder.key",
    "ssl ca": "./logstash-forwarder.crt",
	"timeout": 15
  },
  "files": [
    {
      "paths": [ 
        "/sdcard/logcat.log"
      ],
      "fields": { "type": "nexus7" }
    }
  ]
}


2015/02/11 10:49:21.483965 Waiting for 1 prospectors to initialise
2015/02/11 10:49:21.486122 Launching harvester on new file: /sdcard/logcat.log
2015/02/11 10:49:21.490919 harvest: "/sdcard/logcat.log" (offset snapshot:0)
2015/02/11 10:49:21.493317 All prospectors initialised with 0 states to persist
2015/02/11 10:49:21.494477 Loading client ssl certificate: ./logstash-forwarder.crt and ./logstash-forwarder.key
2015/02/11 10:49:23.821942 Setting trusted CA from file: ./logstash-forwarder.crt
2015/02/11 10:49:23.826473 DNS lookup failure "1.2.3.4": lookup 1.2.3.4: invalid domain name
2015/02/11 10:49:24.827477 DNS lookup failure "1.2.3.4": lookup 1.2.3.4: invalid domain name
```

**Comment by BeniGal** [comment]
On a rooted Samsung Galaxy Core Duos it makes the same thing.

**Comment by driskell** [comment]
Logstash-forwarder performs DNS lookups of all servers (even IP addresses.) Most DNS servers will actually realise it's an IP and return the IP back. Some don't and fail the lookup. Looks like this is one of those occasions.

Code point is here:
https://github.com/elasticsearch/logstash-forwarder/blob/master/publisher1.go#L176

**Comment by jordansissel** [comment]
Hmm, I suppose we could assume that a valid IPv4/v6 address doesn't need looking-up.

**Comment by Yzord** [comment]
I have the same problem with building a logstash-forwarder on a RHEL5 i386 machine (with the logstash-forwarder_linux_386 executable). Everything went fine but when i start the forwarder i get this in the nohup.out:

2015/04/20 11:13:51.831804 Waiting for 1 prospectors to initialise
2015/04/20 11:13:51.831865 Launching harvester on new file: /var/log/maillog
2015/04/20 11:13:51.831896 Launching harvester on new file: /var/log/secure
2015/04/20 11:13:51.831976 harvest: "/var/log/maillog" (offset snapshot:0)
2015/04/20 11:13:51.832374 harvest: "/var/log/secure" (offset snapshot:0)
2015/04/20 11:13:51.832422 All prospectors initialised with 0 states to persist
2015/04/20 11:13:51.832553 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
2015/04/20 11:13:51.833111 DNS lookup failure "1.2.3.4.": lookup 1.2.3.4.: invalid domain name
2015/04/20 11:13:52.835969 DNS lookup failure "1.2.3.4.": lookup 1.2.3.4.: invalid domain name

Reversed DNS is working both ways. Also edited the /etc/hosts but that didn't help. Any idea how i can fix this? Hope there is a fix for it.

**Comment by driskell** [comment]
What go version are people compiling with when they get this error? And with what compile options if any? And what system?

I'm curious as checking Go source this seems to only happen if cgo compilation is disabled (so it uses pure Go resolver instead of glib) and an invalid domain is given. But in latest Go the given IP is not invalid hmmm.

Skipping lookup if valid IP (net.ParseIP) will fix this I'm just curious as to underlying cause.

**Comment by driskell** [comment]
Ah I read the code again and yes an IP is in fact not valid.

When compiled normally "cgo" is enabled and as such getaddrinfo is used which allows IP address to be given.

When "cgo" is disabled, which is implied if cross compiling, the pure Go resolver is used instead which calls dnsclient.go:isDomainName which returns false - an IP is not a valid domain name. Resulting in given error.

If ppl need a workaround until a fix is applied upstream you just need to work out a way to build normally with "cgo" enabled. That means cross compiling is not allowed. Not sure what else might cause it to disable.

Failing that - use a hostname and optionally /etc/hosts as chances are using IP will cause certificate troubles anyway due to the IPSAN issues.

**Comment by Yzord** [comment]
Hmm, i use it on a RHEL5 32bit system. Didn't knew that it was not supported. Does that mean it won't work at all?

**Comment by driskell** [comment]
I noticed in your last comment it said:
2015/04/20 11:13:51.833111 DNS lookup failure "1.2.3.4.": lookup 1.2.3.4.: invalid domain name
2015/04/20 11:13:52.835969 DNS lookup failure "1.2.3.4.": lookup 1.2.3.4.: invalid domain name

"1.2.3.4." ends in a dot. Not sure if that was accidental when redacting real IP. But that would potentially explain an invalid domain name.

For RHEL5 yes it's unsupported by Go. However, I've been able to compile and run it before on that system so I don't think it explains it. One issue I did have on RHEL5 though is timestamps were screwed by hundreds of years on SOME x86_64 systems (not all)

**Comment by Yzord** [comment]
The dot extra is an error of mine...just checked the logs and it does not have the extra dot.

I'm going to be honest...i just installed the 32bit version all by hand without compiling it. I knew the structure and permissions of all folders and files. Reason was because Golang is not available for RHEL5 so i had to do it by hand.

My system is a RHEL5 32bit version
No compiling (set everything by hand, which isn't that much)

All my configs and certs are IP based...i guess i cannot run a second cert next to it with hostname?

**Comment by driskell** [comment]
Where did you get the binary from? Who compiled it and how?

**Comment by Yzord** [comment]
Just downloaded it from elastic.co, but it wasn't a rpm or tar.gz, but the executable. So i placed it in /opt/logstash-forwarder/bin, made it executable and edited the configs to the executable (logstash-forwarder_linux_386). I opened the 64bit rpm to see what the structure was and checked on the 64bit clients what the permissions of all those files were. Made a init.d script so i could start it as a service and up it goes...only ended everything with the line we are discussing now.

**Comment by eirc** [comment]
Here's an amazing workaround for this: add a hostsfile entry with the ip on both sides! This will allow it to "properly" resolve the ip to itself.

**Comment by AngelKyriako** [comment]
Just mentioning this in case it helps someone until the issue is resolved.

I did what @eirc recommended with a hostname instead of ip (hostname hostname in the /etc/hosts file) and it worked fine for my case.

**Comment by spemble** [comment]
This is a problem for me as well. I tried adding an 'IP IP' entry in /etc/hosts but that resulted in a tls handshake error - 'cert signed by unknown auth.'

**Comment by Yzord** [comment]
I can confirm that editing the /etc/hosts file does work. it all depends how you made the certificate (IP based or hostname based). Mine was IP based and i have added the following:

XX.XX.XX.XX   elk.domain.nl (ip of ELK server)
elk.domain.nl  XX.XX.XX.XX (ip of ELK server)
XX.XX.XX.XX   XX.XX.XX.XX (both ip of ELK server)

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better! 

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
