### ISSUE TITLE
Specify the encoding in the Lumberjack protocol

### ISSUE THREAD

**Issue by LordMike** [elastic/logstash-forwarder#378]
It should be specified in the protocol.md file which encoding all strings are written in. I've read some sources indicating its UTF8 - if so, please specify that :).

**Comment by jordansissel** [comment]
@LordMike are you implementing your own lumberjack protocol? What's the context, here?

**Comment by LordMike** [comment]
I was actually looking into it becuase I was trying to do a C# client. I'm in the process of setting up logging at my workplace and we have some custom apps, servers and such that need to ship logs. And as Lumberjack was the only protocol I could find which had the simplicity and reliability I'd like, I gave it a go.

But I was never able to send a message to Logstash as it kept crashing - but that's another story. But the protocol definition is lacking a specification of which encoding strings have.

**Comment by jordansissel** [comment]
I would caution that the lumberjack protocol may change at any time. It is still an experiment.

The protocol itself probably shouldn't have used the term "string". Poor choice on my part, I suppose. logstash-forwarder reads bytes off of disk and sends them over the wire. Encoding isn't a concern for the protocol at this point. Logstash acts on text encoding concerns after it's received events from the lumberjack protocol.

**Comment by jordansissel** [comment]
> But I was never able to send a message to Logstash as it kept crashing

Is this related to encoding?

> I was trying to do a C# client.

Are you sending anything other than UTF-8? What about encoding gave you trouble?

**Comment by LordMike** [comment]
I am trying to reproduce now.

**Comment by LordMike** [comment]
$ /opt/logstash/bin/logstash agent -f lumberjack.conf --verbose
    Using milestone 1 input plugin 'lumberjack'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones {:level=>:warn}
    Starting lumberjack input listener {:address=>"0.0.0.0:2500", :level=>:info}
    Pipeline started {:level=>:info}
    NoMethodError: undefined method `force_encoding' for nil:NilClass
           convert at /opt/logstash/lib/logstash/util/charset.rb:14
            decode at /opt/logstash/lib/logstash/codecs/plain.rb:36
               run at /opt/logstash/lib/logstash/inputs/lumberjack.rb:47
              call at org/jruby/RubyProc.java:271
              data at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:241
               run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:223
    data_field_value at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:182
              feed at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:93
               run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:220
               run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:59


My config:

    input {
       lumberjack {
         port => 2500
         ssl_certificate => "/etc/logstash/graylog.mbwarez.dk.crt"
         ssl_key => "/etc/logstash/graylog.mbwarez.dk.key"
         type => lumberjack
       }
    }
    
    output {
      stdout { codec => rubydebug }
    }

Message in Hex:

    01440000000000000001000000076D6573736167650000000B68656C6C6F20776F726C64


Which should be a data frame with 1 pair with the content "message:hello world".

**Comment by jordansissel** [comment]
The "1" is not byte 0x01 but literally "1" the ascii letter, aka hex 0x31

**Comment by jordansissel** [comment]
Sample code: 
* https://github.com/elasticsearch/logstash-forwarder/blob/master/lib/lumberjack/client.rb#L132
* https://github.com/elasticsearch/logstash-forwarder/blob/master/publisher1.go#L223-L226

**Comment by LordMike** [comment]
Seriously? :|

**Comment by jordansissel** [comment]
@LordMike best case, maybe ask this on the logstash discuss forum on discuss.elastic.co or follow up with the beats folks on this, since logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
