### ISSUE TITLE
Double zlib deflate in client.rb

### ISSUE THREAD

**Issue by ekho** [elastic/logstash-forwarder#379]
in class `Socket` in method `write_hash` called `Encoder.to_compressed_frame` which returns frame encoded with `Zlib::Deflate.deflate`
Then method `write_hash` calls method `write` which encodes frame again.

Is it right?

**Comment by jordansissel** [comment]
If this were true, wouldn't this cause a crash?

**Comment by ph** [comment]
This was true, I have fixed it in https://github.com/elastic/ruby-lumberjack/pull/9
