### ISSUE TITLE
Document cleaner way to build logstash-forwarder on Debian

### ISSUE THREAD

**Issue by gebi** [elastic/logstash-forwarder#392]
Hi,

It would be nice if you can document how to build logstash-forwarder on debian without installing gems into the system.

This list of commands build the logstash-forwarder debian package on debian sid and most probably ubuntu together with #391 

    apt-get install bundler gcc gcc-4.9 ruby ruby2.1-dev
    git clone https://github.com/elasticsearch/logstash-forwarder
    cd logstash-forwarder
    mkdir vendor/bundle
    bundle install --path vendor/bundle
    make deb

**Comment by jordansissel** [comment]
> apt-get install bundler gcc gcc-4.9 ruby ruby2.1-dev

This fails under Ubuntu 14.04:
'ruby' is Ruby 1.9.3 on Ubuntu 14.04, and `ruby2.1-dev` doesn't exist in this distro version.

> git clone https://github.com/elasticsearch/logstash-forwarder

Probably we should have 'git' in in the `apt-get install` line also?

**Comment by gebi** [comment]
Yes maybe git too but that should be obvious for an admin, so imho no need to mention it.

For the exact versions, i've only added them to make it clear what versions i've used here, sorry.
`apt-get install bundler gcc ruby-dev` should be enough.

Except on debian sid here it's not, because you get a very strange error regarding missing libs and i had to explicitely update gcc and install gcc-4.9 to make it work.

**Comment by jordansissel** [comment]
> should be obvious

ruby-dev is obvious to me, so there's evidence that _obvious_ varies greatly from person to person :)

Maybe we should have a separate file (maybe in the github project wiki?) that describes all the different setup/build instructions for varying distributions?

**Comment by gebi** [comment]
Would be an option. IMHO only one thing would be really important, namely build instructions who's commands that do not mess with the system of the user (eg. bundle install with --path, and the needed bundle exec make deb)

As for debian it would be nice to include an additional note that you have to install gcc which is used by ruby-dev _and_ it needs to be the default gcc (so you have to install gcc and gcc-x.x matching to your ruby-dev).

thx for your patience :)!

**Comment by dedemorton** [comment]
Please accept my apologies for the delayed response to your issue. Logstash-forwarder is now deprecated, so we won't be updating the documentation.

We recommend that customers migrate to Filebeat. Please see the product documentation to get started with Filebeat: https://www.elastic.co/guide/en/beats/filebeat/current/index.html

And take a look at the following topic for information about migrating from logstash-forwarder and Filebeat: https://www.elastic.co/guide/en/beats/filebeat/current/_migrating_from_logstash_forwarder_to_filebeat.html
