### ISSUE TITLE
Openssl command from documentation produces unusable certificates

### ISSUE THREAD

**Issue by gebi** [elastic/logstash-forwarder#399]
Hi,

The openssl command from https://github.com/elasticsearch/logstash-forwarder/blob/master/README.md#generating-an-ssl-certificate produces a certificate without a `DN`, which makes the certificate validation of go reject it.

```
openssl req -x509 -batch -nodes -newkey rsa:2048 -keyout logstash-forwarder.key -out logstash-forwarder.crt -days 365
```

The correct command would be without `-batch` and input the machines hostname used to connect as DN (all other values could be left at their default values, "Internet Widgits Pty Ltd" ftw):
```
openssl req -x509 -nodes -newkey rsa:2048 -keyout logstash-forwarder.key -out logstash-forwarder.crt -days 365
```

**Comment by jordansissel** [comment]
Hm, I don't know what happened. It used to have `-subj /CN=example.com` but seems to be missing that now.

**Comment by tomsommer** [comment]
The openssl command is two places in the documentation, only one uses the CN=

**Comment by jordansissel** [comment]
@tomsommer *facepalm* I totally missed that. haha

**Comment by jordansissel** [comment]
#428 up for review.

**Comment by jordansissel** [comment]
#428 was merged.
