### ISSUE TITLE
Repeated "Read Error looking for ACK" Error Messages

### ISSUE THREAD

**Issue by ninjada** [elastic/logstash-forwarder#421]
Hi,

My logstash staging environment was running ok for sometime. However, after scaling up the number of servers and thus logs being harvested in testing for a pre-production run, I've started seeing repeated read errors on logstash-forwarder's log. 

Also, after some time, the logstash and elasticsearch server will crash with java heapsize errors.. 

Note: atm, i'm running the ELK stack on one node, but it is a big server (32GB RAM) and there are only 4-5 servers pushing logs to it via logstash-forwarder..

Logstash-forwarder will report this, generally at the same time on all forwarding servers:
 
2015/03/10 13:33:54.468798 Read error looking for ack: read tcp 192.168.0.100:5000: i/o timeout

It'll wait for some time, and begin processing again, unless the ELK stack falls over at some level..

an example of my logstash-forwarder config and command line:

cmd line: -config /etc/logstash-forwarder -spool-size 100'

config: https://gist.github.com/ninjada/43a5d3d5485526518c8e

Those are the main types of logs, aside from that theres 2 servers harvesting varnishncsa.log which are the most intensive.

I've been running logstash-forwarder-0.4.0-1 built myself about 3-4 weeks ago. I've just built the latest version as of this morning (same version, but has a fair few changes) and tried it on one of the servers

IOwait on the logstash server seems fine, so I can't seem to nail down what's causing this. 

Any ideas?

**Comment by driskell** [comment]
> On 10 Mar 2015, at 03:03, ninjada <notifications@github.com> wrote:
> My logstash staging environment was running ok for sometime. However, after scaling up the number of servers and logs being harvested for a pre-production run, I've started seeing repeated read errors on logstash-forwarder's log. Also, after some time, the logstash and elasticsearch server will crash with java heapsize errors.. Note: atm, i'm running the ELK stack on one node, but it is a big server (32GB RAM) and there are only 4-5 servers pushing logs to it..
> 
> Logstash-forwarder will report this, generally at the same time on all forwarding servers:
> 
> 2015/03/10 13:33:54.468798 Read error looking for ack: read tcp 192.168.0.100:5000: i/o timeout
> 
> It'll wait for some time, and begin processing again..
> 
ACK read I/O timeout is a known issue with LSF. When Logstash is under pressure and gets busy, essentially it starts to DDoS Logstash. If Logstash doesn't respond in time (which it won't if it's really busy) it then resends the logs - making it worse.

Generally only fix is more Logstash resource and/or longer network timeout is LSF but if you hit another spike same can happen.

Hopefully there'll be a fix soon (it's a protocol implementation problem) but it might be they wait until LSF is replaced as per roadmap.

Only other advice I can offer is to use another shipper. I forked LSF a year ago and created Log Courier which fixes the IO issue - it just backs off gracefully and shipping slows slightly.

Jason

**Comment by driskell** [comment]
Reducing spool size as well as increasing network timeout will help too - I can see you've already done that bit though.

**Comment by jordansissel** [comment]
This kind of thing is probably best to ask on discuss.elastic.co - sorry for the delays in responding.

"Read error waiting for ack" means taht lsf gave upw aiting for Logstash to acknowledge successful handling of the current batch of events. This usually means something downstream of lsf (network, logstash, elasticsearch, etc) is down or unable to keep up with your event throughput.

Let's follow up on https://discuss.elastic.co/ with some more details about your entire stack (lsf/logstash/es/disk/network/etc) and hopefuly we can move you forward from there if you're still having troubles.
