### ISSUE TITLE
gofmt -w -tabs=false -tabwidth=2

### ISSUE THREAD

**Issue by pierrre** [elastic/logstash-forwarder#423]
Why?
Tabs is the default formatting in Go!
http://golang.org/doc/effective_go.html#formatting

**Comment by driskell** [comment]
Why not? Is there an issue?

**Comment by jordansissel** [comment]
>  Tabs is the default formatting in Go!

Sorry, I am not having this argument.

**Comment by jordansissel** [comment]
(Apologies for the brevity of the previous comment)

I am aware of gofmt's defaults, but indentation-byte-sequence arguments are pretty far down on the list of things I have energy to discuss.

Thank you for your interest in the style of this project. :)
