### ISSUE TITLE
Deb init script doesn't work

### ISSUE THREAD

**Issue by rabidscorpio** [elastic/logstash-forwarder#425]
So the deb package that's downloadable from elasticsearch.org doesn't work at all. It says it's starting but it doesn't actually run and there's no error when the init script runs, it says ```[ok]```. in the error log, there's this:
```
chroot: invalid option -- '-'
Try `chroot --help' for more information.
```

**Comment by torrancew** [comment]
@rabidscorpio what version of logstash-forwarder are you running? Also, what distribution are you running on? I have no problems here with LSF 0.4.0, on Debian 7.

**Comment by rabidscorpio** [comment]
This is with Ubuntu 14.04 and logstash-forwarder 0.4.0.

**Comment by jordansissel** [comment]
@rabidscorpio thank you for reporting. I will test.

**Comment by jordansissel** [comment]
@rabidscorpio I cannot reproduce on Ubuntu 14.04

Here's the result from a fresh Ubuntu 14.04 box on DigitalOcean:

```
root@ubuntu:~# wget https://download.elasticsearch.org/logstash-forwarder/binaries/logstash-forwarder_0.4.0_amd64.deb
...
2015-03-15 00:23:24 (1.41 MB/s) - ‘logstash-forwarder_0.4.0_amd64.deb’ saved [1749944/1749944]

root@ubuntu:~# sudo dpkg -i logstash-forwarder_0.4.0_amd64.deb
Selecting previously unselected package logstash-forwarder.
(Reading database ... 146178 files and directories currently installed.)
Preparing to unpack logstash-forwarder_0.4.0_amd64.deb ...
Unpacking logstash-forwarder (0.4.0) ...
Setting up logstash-forwarder (0.4.0) ...
 Adding system startup for /etc/init.d/logstash-forwarder ...
   /etc/rc0.d/K20logstash-forwarder -> ../init.d/logstash-forwarder
   /etc/rc1.d/K20logstash-forwarder -> ../init.d/logstash-forwarder
   /etc/rc6.d/K20logstash-forwarder -> ../init.d/logstash-forwarder
   /etc/rc2.d/S20logstash-forwarder -> ../init.d/logstash-forwarder
   /etc/rc3.d/S20logstash-forwarder -> ../init.d/logstash-forwarder
   /etc/rc4.d/S20logstash-forwarder -> ../init.d/logstash-forwarder
   /etc/rc5.d/S20logstash-forwarder -> ../init.d/logstash-forwarder
Logs for logstash-forwarder will be in /var/log/logstash-forwarder/
Processing triggers for ureadahead (0.100.0-16) ...
root@ubuntu:~# sudo /etc/init.d/logstash-forwarder start
logstash-forwarder started
root@ubuntu:~# tail -f /var/log/logstash-forwarder/logstash-forwarder.*
==> /var/log/logstash-forwarder/logstash-forwarder.err <==
    #}, {
      #"paths": [
        #"/var/log/apache/httpd-*.log"
      #],
      #"fields": { "type": "apache" }
    #}
  ]
}

2015/03/15 00:23:40.387727 No paths given. What files do you want me to watch?

==> /var/log/logstash-forwarder/logstash-forwarder.log <==
```

**Comment by jordansissel** [comment]
@rabidscorpio Can you attach the output of `lsb_release -a` and `dpkg -S /usr/sbin/chroot` ?

```
root@ubuntu:~# dpkg -S /usr/sbin/chroot
coreutils: /usr/sbin/chroot

root@ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
```

**Comment by insertjokehere** [comment]
I'm seeing the same issue on Debian Wheezy because I am deploying logstash-forwarder with elastic/puppet-logstashforwarder, which writes a defaults file with doesn't contain any of the settings the new init script needs

**Comment by jordansissel** [comment]
@insertjokehere This sounds like a bug in the puppet-logstashforwarder, then? That repository is unmaintained - the last commit was over a year ago. I recommend you not use it *or* work to improve it such that it functions again.

**Comment by actinide** [comment]
I was having the same issue on one of my Ubuntu 14.04 machines, and tracked it down to the chroot --userspec line in the init script. Unfortunately, that's as far as I've gotten. I'll update if I make any progress.

**Comment by rabidscorpio** [comment]
Oh, so I'm actually using 10.04, not 14.04:

```
root@ubuntu:~# -S /usr/sbin/chroot
coreutils: /usr/sbin/chroot

root@ubuntu:~# lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 10.04.4 LTS
Release:	10.04
Codename:	lucid
```

**Comment by thalesac** [comment]
@rabidscorpio I had the same problem. The chroot version doesn't support this parameter. A workaround is to edit /etc/init.d/logstash-forwarder and remove the parameter that forces the execution with the logstash user. Replace the line with:
> chroot "$chroot" sh -c "

Bear in mind that it will execute as root, which is not a good idea, but will work.

**Comment by hrchu** [comment]
I face the same issue in ubuntu 10.04 + logstash 1.5.0

I seems the issue from  https://github.com/jordansissel/pleaserun/issues/49

My workaround is 
```
nice -n ${LS_NICE} su -s /bin/sh ${LS_USER} -c "
```

**Comment by fninja** [comment]
Same issue on CentOS5.
@hrchu thanks for your workaround!!!

This really sux and it shouldn't happen in a decent .rpm / .deb .
From all bugs, the worst ones are those that stop you from actually even trying to use the application, i think. And logstash is such a wonderful one.
I think your workaround is actually a fix and deserves recommendation.

BTW my problem is with logstash, not logstash-forwarder. or are they the same?
```
$ cat /etc/redhat-release
  CentOS release 5.6 (Final)
$ /opt/logstash/bin/logstash --version
  logstash 1.5.1
```

**Comment by bflad** [comment]
This workaround worked for me on RHEL 5. Thanks!

**Comment by jordansissel** [comment]
Ubuntu 10.04 and RHEL5 are not supported by us at this time. We do not test on these very old distributions, so breakages are possible. 

RHEL6 and Ubuntu 12.04 are the oldest of their respective distributions that we support.

**Comment by jordansissel** [comment]
So far most reports seem to be about one (or both) of two situations:

1) Using an unsupported/untested operating system such as Ubuntu 10.04 or RHEL5
2) Using puppet-logstashforwarder

Both of these scenarios (separate or together) are not supported at this time. Folks wishing support for older or unsupported operating systems can maintain forks if they wish. Please do not use puppet-logstashforwarder at this time as it is abandoned and unmaintained.

Sorry for any confusion or upset.

**Comment by jordansissel** [comment]
So far most reports seem to be about one (or both) of two situations:

1) Using an unsupported/untested operating system such as Ubuntu 10.04 or RHEL5
2) Using puppet-logstashforwarder

Both of these scenarios (separate or together) are not supported at this time. Folks wishing support for older operating systems can maintain forks if they wish. Please do not use puppet-logstashforwarder at this time as it is abandoned and unmaintained.

Sorry for any confusion or upset.

**Comment by jordansissel** [comment]
First, sorry if y'all are still having problems. For everyone here, I appreciate and want to thank you for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?

**Comment by witkacy26** [comment]
quick (far from perfect) solution for ubuntu 10.04, logstash-forwarder 0.4.0:

   * comment out 'chroot' part of start() section
   * substitute it with chroot-free version: <br>
   `"$program" $args >> /var/log/logstash-forwarder/logstash-forwarder.log 2>> /var/log/logstash-forwarder/logstash-forwarder.err &`
