### ISSUE TITLE
Read error looking for ack: WSARecv tcp to x.x.x.x: 58848: i/o timeout

### ISSUE THREAD

**Issue by ramreddy26** [elastic/logstash-forwarder#431]
Hi,

Since last few days logstash-forwarder shippers are throwing below errors, it was working previously without any issue. I tried upgrading logstash to 1.5.0rc2 version from 1.4.2, but still I get the same error.  I use logstash-forwarder version 0.3.0, elasticsearch 1.4.4, logstash 1.4.2/1.5.0rc2. Could you help me to fix this issue?

2015/03/17 14:46:08.443268 Connected to x.x.x.x
2015/03/17 14:46:23.444268 Read error looking for ack: WSARecv tcp to x.x.x.x:
58848: i/o timeout
2015/03/17 14:46:38.642268 Setting trusted CA from file: C://ProgramData//Puppet
Labs//puppet//etc//ssl//certs//ca.pem
2015/03/17 14:46:38.643268 Connecting to [to x.x.x.x]:5043 

I see below errors in logstash log file, I tried increasing cap size but no luck

Error: Your application used more memory than the safety cap of 500M.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace
Sending logstash logs to /opt/logstash/logstash.log.

**Comment by richardgoetz** [comment]
I have exactly same problems. It worked and then just stopped. 
I have Elasticsearch 1.3.2 - 1.5 Logstash 1.4 and 1.5 and Logstash Forwarder. 
Is there way to get more debug info into logs? It does seem like issue with something happening in transport - it will ship logs to logstash server but then stops - nothing in logs it just stops. 

2015/03/28 14:59:59.772172 Registrar received 500 events
on Logstash Forwarder 

Logstash starts ok 
INFO: [logstash-chilog01-12211-15630] started 
But then eventually
:message=>"retrying failed action with response code: 503", :level=>:warn}

**Comment by mateodelnorte** [comment]
Having the same problem. Anybody have any insight?

**Comment by ramreddy26** [comment]
I couldn't find a solution, so I switched to log-courier and its working
fine now.

Thanks,

Ram

**Comment by juniorh** [comment]
I have similar issue with logstash 1.5.1 and logstash-forwarder 0.4.0. I run logstash-forwarder with args
> logstash-forwarder -config /etc/logstash-forwarder.conf -spool-size 16384 -log-to-syslog -tail

Just try to increase 'timeout' parameter in logstash-forwarder.conf then the issue is done

**Comment by ph** [comment]
This look like a slow down or a stalled pipeline, increasing the timeout on the LSF will give more time to logstash to resolve the situation. Adding more capacity on the logstash side will also help on this issue.
You should look at your logstash log to see if there is any errors.

Feel free to create a new issue or reopen this one.
