### ISSUE TITLE
Logstash-Forwarder on Windows: documentation

### ISSUE THREAD

**Issue by TimmGr** [elastic/logstash-forwarder#432]
Hello logstash-forwarder-awesome-crew,

I have been busy setting up logstash-forwarder on Ubuntu as well as on Windows. But while doing that I was struggling to find all info needed. Which is unfortunate because it seems all the info is around somewhere. Just not in the doc.

Let me explain my experiences: 
First we start at: https://www.elastic.co/downloads/logstash and scroll to lsf
Then when we follow the three step installation and fail, because the last step is: 
Run logstash-forwarder-config forwarder.conf
and not:
Run logstash-forwarder -config forwarder.conf

Also while configuring lsf on windows I was totally unaware of the need of using // instead of /. I found that only here: https://logstash.jira.com/browse/LOGSTASH-1856 in the second comment.

In hindsight both problems seem trivial but at the time, being a new user, this was an obstacle.

Also, where is the default log location on windows? On Ubuntu: tail -f /var/log/logstash-forwarder/logstash-forwarder.* works just fine. 
(Maybe that is also an input to https://github.com/elastic/logstash-forwarder/issues/395 : Where and how to log?)

Also I configured lsf to start silently in the background on windows. I used a vbs script for that, but in my opinion that would be sweet to have out of the box, even though I realize that is not top priority.

One other point: the quickest installation guide I found for Ubuntu was here: https://github.com/elastic/logstash-forwarder/issues/425
Maybe you want to put that somewhere more prominent.

I hope you find my "newb"-thoughts interessting.

Best wishes,
Timm

**Comment by usahitya** [comment]
Is Logstash Forwarder 0.4.0 works with Windows2008R2 server. whether it have any documentation like how to install it?

**Comment by ruflin** [comment]
@usahitya Logstash-forwarder is now replaced by Filebeat which also works under windows. Here is the getting started guide: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html

@TimmGr Thanks for sharing your insights on this. We now also provide a windows package whick tackles some of the above problems. I will close this issue. For further discussions please open an issue in filebeat: https://github.com/elastic/filebeat

**Comment by ShraddhaBandhakavi** [comment]
@ruflin In Getting started guide there is no point mentioned about Windows.

**Comment by ruflin** [comment]
@ShraddhaBandhakavi Thats a good point. The Windows binary can be found here: https://www.elastic.co/downloads/beats/filebeat

I opened https://github.com/elastic/filebeat/issues/295 so we better document this.
