### ISSUE TITLE
Log forwarder not responding

### ISSUE THREAD

**Issue by OElesin** [elastic/logstash-forwarder#436]
Having built the forwarder with go, when I run the command:
logstash-forwarder -config logstash-forwarder.conf 

I get this response:

lumberjack/logstash-forwarder -config logstash-forwarder.conf 
2015/04/10 11:55:12.133944 	--- options -------
2015/04/10 11:55:12.134058 	config-arg:          logstash-forwarder.conf
2015/04/10 11:55:12.134079 	idle-timeout:        5s
2015/04/10 11:55:12.134093 	spool-size:          1024
2015/04/10 11:55:12.134107 	harvester-buff-size: 16384
2015/04/10 11:55:12.134137 	--- flags ---------
2015/04/10 11:55:12.134150 	tail (on-rotation):  false
2015/04/10 11:55:12.134163 	log-to-syslog:          false
2015/04/10 11:55:12.134176 	quiet:             false
2015/04/10 11:55:12.134245 {
  "network": {
  "servers": ["192.168.1.139:4545"],
  "ssl certificate": "/root/logstash/logstash.pub",
  "ssl key": "/root/logstash/logstash.key",
  "ssl ca": "/root/logstash/logstash.pub"
  },
  "files": [
  {
    "paths": [ "/root/logstash/myfile.json"],
  
  }
 ]
}

2015/04/10 11:55:12.134735 Failed unmarshalling json: invalid character '}' looking for beginning of object key string
2015/04/10 11:55:12.134784 Could not load config file logstash-forwarder.conf: invalid character '}' looking for beginning of object key string

**Comment by driskell** [comment]
You have a comma on the end of the "paths" line. It needs removing since it has closing } straight after. It's strict JSON so not like in a browser.

You'll want something like this:

```
{
  "network": {
    "servers": ["192.168.1.139:4545"],
    "ssl certificate": "/root/logstash/logstash.pub",
    "ssl key": "/root/logstash/logstash.key",
    "ssl ca": "/root/logstash/logstash.pub"
  },
  "files": [
    {
      "paths": [ "/root/logstash/myfile.json"]
    }
  ]
}
```

**Comment by OElesin** [comment]
Thanks that worked. But I keep getting this error:

2015/04/10 13:16:44.275447 Waiting for 1 prospectors to initialise
2015/04/10 13:16:44.275660 Launching harvester on new file: /root/logstash/myfile.json
2015/04/10 13:16:44.275793 harvest: "/root/logstash/myfile.json" (offset snapshot:0)
2015/04/10 13:16:44.276118 All prospectors initialised with 0 states to persist
2015/04/10 13:16:44.276610 Loading client ssl certificate: /root/logstash/logstash.pub and /root/logstash/logstash.key
2015/04/10 13:16:44.291773 Failed loading client ssl certificate: crypto/tls: failed to parse key PEM data

Can you help?
