### ISSUE TITLE
Bug in logstash-forwarder_linux_386

### ISSUE THREAD

**Issue by Yzord** [elastic/logstash-forwarder#441]
I think i have found a bug in the logstash-forwarder i386 version.

In my logstash-forwarder config i use an IP for the LS server, but when i execute logstash-forwarder it thinks it is an hostname.

2015/04/20 14:26:32.674411 DNS lookup failure "1.2.3.4": lookup 1.2.3.4: invalid domain name

All my other clients (64bits) are working ok, only the 32bits clients are doing this. Is there a way around so that it thinks it is an IP?

**Comment by magnusbaeck** [comment]
This looks like a duplicate of #371.

**Comment by Yzord** [comment]
Yup, it looks like it...glad that it is recognized as a bug :)

**Comment by torrancew** [comment]
@Yzord if it's definitely the same error, could you close this one and note in #371 that you're impacted by it?
