### ISSUE TITLE
logstash data to es ,  logstash auto stop work ,but process is exist

### ISSUE THREAD

**Issue by rfyiamcool** [elastic/logstash-forwarder#447]
ruifengyun@bj-log-1 ~]$ netstat -tn | egrep "192.168.1.103" | grep CLOSE_WAIT
tcp        0      0 ::ffff:192.168.1.50:41079   ::ffff:192.168.1.103:9000   CLOSE_WAIT
tcp        0      0 ::ffff:192.168.1.50:41076   ::ffff:192.168.1.103:9000   CLOSE_WAIT
tcp        0      0 ::ffff:192.168.1.50:41082   ::ffff:192.168.1.103:9000   CLOSE_WAIT

**Comment by jordansissel** [comment]
@rfyiamcool I'm not sure what you are asking. Can you provide more details about your problem?

**Comment by ruflin** [comment]
Closing as no more information provided recently.
