### ISSUE TITLE
Reindex file

### ISSUE THREAD

**Issue by silviupanaite** [elastic/logstash-forwarder#449]
Logstash dropped some entries due to an error. I fixt it but how can I force logstash-forwarder to reparse that file?

Or is there a solution to my problem?

**Comment by hvisage** [comment]
The method would be to add the "beginning" option to the logstash-forwarder.conf file.
Then remove the relavent .logstash-forwarder file from the home directory or working directory of the logstash-forwarder process.

The other technique I use, is to setup a stdin feeder config file with all the needed settings for that file, but the path to point to "-", then you start something like:
cat file | logstash-forwarder --config /etc/logstash-forwarder-feeder.conf -quiet=false
And once it pushed everything up (the last message not a round 1024 or something) then you can kill the logstash-forwarder.
Also the reason I have opened #448

**Comment by silviupanaite** [comment]
Thanks for the response. 
I'll try that.
