### ISSUE TITLE
long lines read cause mistaken EOF when harvester buffer is full

### ISSUE THREAD

**Issue by riddley** [elastic/logstash-forwarder#45]
Discovered when reading a file with very long lines as STDIN.

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by riddley** [comment]
I don't know. I don't work there anymore and don't have time to test. Sorry.

**Comment by jordansissel** [comment]
I wasn't able to reproduce this. We can reopen later if it's rediscovered.
