### ISSUE TITLE
Logstash Forwarder resend 24hour of logs in one shot upon a single entry 

### ISSUE THREAD

**Issue by djsly** [elastic/logstash-forwarder#458]
Hello, 

we saw a huge spike of incoming logs from a service that isn't taking traffic for while. 

We realized that the log file received a single new entry after over 2 days of inactivity. 

Logstash-fowarder then resent the whole file (almost) file has now 119876 entries

```
logstash-forwarder[31848]: 2015/05/04 16:31:00.928225 File rename was detected: /logs/pcs/ncs_pcs_current -> /logs/pcs/ncs_pcs_0017
logstash-forwarder[31848]: 2015/05/04 16:31:00.928276 Launching harvester on rotated file: /logs/pcs/ncs_pcs_current
logstash-forwarder[31848]: 2015/05/04 16:31:00.928414 Started harvester at end of file (current offset now 11902): /logs/pcs/ncs_pcs_current
logstash-forwarder[31848]: 2015/05/05 18:31:32.956815 Stopping harvest of /logs/pcs/ncs_pcs_current; last change was 24h0m5.135114078s ago
logstash-forwarder[31848]: 2015/05/05 19:07:15.386066 Stopping harvest of /logs/pcs/ncs_pcs_current; last change was 24h0m5.076505515s ago
logstash-forwarder[31848]: 2015/05/06 19:52:25.052580 Stopping harvest of /logs/pcs/ncs_pcs_current; last change was 24h0m5.181655248s ago
logstash-forwarder[31848]: 2015/05/07 17:20:16.831637 Resuming harvester on an old file that was just modified: /logs/pcs/ncs_pcs_current
logstash-forwarder[31848]: 2015/05/07 17:20:16.831801 Started harvester at position 11902 (current offset now 11902): /logs/pcs/ncs_pcs_current
```

my config is looks like this 
```
  "files": [
	{
      "paths": [
        "/logs/*/*"
      ],
      "fields": { "type": "log4j" , "product": "ncs" }
    },
    {
      "paths": [
        "/var/log/cassandra/*"
      ],
      "fields": { "type": "log4j" , "product": "cassandra" }
    }
  ]
```

so log4j actually rotated the ncs_pcs_current file into ncs_pcs_0017. last modified time for the rotated file is : 
```
-rw-r----- 1 root root 67108989 May  4 16:30 ncs_pcs_0017
```
now where I'm lost is with the following line
```
    Started harvester at end of file (current offset now 11902): /logs/pcs/ncs_pcs_current
```
It looks like it thinks that the new file needs to start at 11902
```
    11902 INFO  2015-05-04 17:47:52,151
```
I had logging present in the ncs_pcs_current file up till the following time
```
    199872 INFO  2015-05-05 19:52:19,785
```
therefore the following watchdog make sense
```
    logstash-forwarder[31848]: 2015/05/06 19:52:25.052580 Stopping harvest of /logs/pcs/ncs_pcs_current; last change was 24h0m5.181655248s ago
```
But the previous two dont
```
    logstash-forwarder[31848]: 2015/05/04 16:31:00.928414 Started harvester at end of file (current offset now 11902): /logs/pcs/ncs_pcs_current
    logstash-forwarder[31848]: 2015/05/05 18:31:32.956815 Stopping harvest of /logs/pcs/ncs_pcs_current; last change was 24h0m5.135114078s ago
```
Those seem to be from the previous logs ncs_pcs_0017

When the resume starts again, the replay of the whole _current file occurs...

From what I get from this analysis is that I should maybe be only looking at the         "/logs/*/*_current" but I would like to still share my issue in case this hide a fundamental issue.

Running version 

```
Installed Packages
Name        : logstash-forwarder
Arch        : x86_64
Version     : 0.3.1
```

**Comment by driskell** [comment]
The original 0.3.1 package had many issues like this. It'll be hard to tell if issue still present but I'm inclined to say it isn't.

The new 0.4.0 has major improvements so best try that.

**Comment by djsly** [comment]
Thanks

I did see the following issues after

https://github.com/elastic/logstash-forwarder/issues/77
https://github.com/elastic/logstash-forwarder/issues/101
https://github.com/elastic/logstash-forwarder/issues/131
https://github.com/elastic/logstash-forwarder/pull/164

After updating to 0.4.0, Im having the following issue now

https://github.com/elastic/logstash-forwarder/issues/293

I will have to try to update log stash to 1.5.0.rc4 to see if this gets fix
for me as well.

**Comment by djsly** [comment]
Question about the internal logic. 

If I restart the forwarder or even start it for the first time. 

and I tell him to monitor the following files /logs/* where the folder contains  
log_123 
log_124
log_125
log_current

will all 4 logs be read, entirely ? or shouldn't only new entry be parsed ?

Also if I restart the forwarder every hour lets say, whats the logic being the decision it takes to replay or not files ?

I tried to look for some documentation but couldn't, if you have a link feel free to share it : )

Thanks !

**Comment by driskell** [comment]
Yes, /logs/* will match them all and ingest them.

It will try to resume where possible. Otherwise, it will obey what you set in "-tail" command line parameter (default is true - follow from end - and in 0.3.2 it was called "-from-beginning" and default was false, so essentially same behaviour.)

Why restart hourly though?

**Comment by djsly** [comment]
:) I'm not restarting it every hour hehe, just wanted to make it explicit
that I was asking about 'what if I restart it'

**Comment by djsly** [comment]
FYI: going to 1.5.0.rc4 fixed the EOF error on the client side.

This Bug could be marked as closed.
