### ISSUE TITLE
logstash-forwarder Connecting to [x.x.x.x]:5000 Failure connecting to x.x.x.x: dial tcp x.x.x.x no route to host

### ISSUE THREAD

**Issue by macarrami** [elastic/logstash-forwarder#459]
Hi friends.
I installed logstash & logstash forwarder with kibana on my centos 6.5 servers. When logstash and logstash forwarder are running on the same machine everything is ok :) . The problem is when I have tried to send the logs from another server. Logstash and logstash-forwarder are running but the logs dont arrive at logstash :( . Taking a look on the logstash forwarder logs (.err) these msg appear:

 Connecting to [X.X.X.X]:5000 (X.X.X.X) 
 Failure connecting to X.X.X.X: dial tcp X.X.X.X:5000: no route to host. 

Regarding the ports firewall, after do # netstat -tulpn | less to check the ports I found:
tcp        0      0 :::5000                     :::*                        LISTEN      6697/java       

I am a beginner in linux,centos...   (so sorry, I know but as it says "never is too late is the purpose is good"   :)  ), so I have many problems to debug, PLEASE, could you help me???? 

Thanks in advance!!!

**Comment by Sammel** [comment]
I have a same problem, too!!!

**Comment by lefeverd** [comment]
Me too... It seems that when forwarding from a remote host is a problem

**Comment by lefeverd** [comment]
I could resolve it by changing the port from 5049 to 5898 (you could try with any other port) in the logstash-forwarder input configuration.

**Comment by suyograo** [comment]
Please make sure the port you configured for LSF is open and accessible. You can check this by using `netcat` tool to send data to this port

**Comment by etichi** [comment]
It was a firewall issue on my server. check that too.
