### ISSUE TITLE
Add option to set the idleTimeout option from the CLI

### ISSUE THREAD

**Issue by EdHurtig** [elastic/logstash-forwarder#460]
I would like to lower the idleTimeout to about 2 seconds for some of our servers to reduce the latency between write and appearance in Logstash.  I was excited to find the idleTimeout option in the code but couldn't find a way of setting the option from the CLI or the config file.

Please correct me if I missed a way of setting this option.

**Comment by driskell** [comment]
It's a command line option: --idle-timeout=2

**Comment by EdHurtig** [comment]
Huh...

```
/opt/logstash-forwarder/bin/logstash-forwarder --config=/etc/logstash-forwarder/logstash-forwarder.conf --idle-timeout=2

flag provided but not defined: -idle-timeout
Usage of /opt/logstash-forwarder/bin/logstash-forwarder:
  -config="": path to logstash-forwarder configuration file or directory
  -cpuprofile="": path to cpu profile output - note: exits on profile end.
  -harvest-buffer-size=16384: harvester reader buffer size
  -hb=16384: harvester reader buffer size
  -log-to-syslog=false: log to syslog instead of stdout
  -quiet=false: operate in quiet mode - only emit errors to log
  -spool-size=1024: event count spool threshold - forces network flush
  -sv=1024: event count spool threshold - forces network flush
  -syslog=false: log to syslog instead of stdout
  -t=false: always tail on log rotation -note: may skip entries
  -tail=false: always tail on log rotation -note: may skip entries
  -version=false: output the version of this program
```

```
/opt/logstash-forwarder/bin/logstash-forwarder --version
0.4.0
```

**Comment by EdHurtig** [comment]
This LF was built off of the [0.4.0 tag](https://github.com/elastic/logstash-forwarder/tree/v0.4.0)... nothing since then though

**Comment by driskell** [comment]
Ah sorry. `-idle-timeout=2`
I forget it's one hyphen not two!

**Comment by driskell** [comment]
Oh sorry. It's actually not configurable without modifying source. Fairly sure it used to be! But I guess is a feature request now.

**Comment by EdHurtig** [comment]
Ok well then I will finish out my changes later this week to get this added in.

**Comment by driskell** [comment]
time.ParseDuration on setting option will do it. It turns "2s" and "1h" for example into a time.Duration

**Comment by EdHurtig** [comment]
Sweet that is the only piece remaining I think... tests will tell : ). Thanks a ton!

**Comment by mcbain** [comment]
Since the file idle option is named "dead time" does this mean, any log event after the configured time will not processed anymore?

**Comment by driskell** [comment]
@Mcbain it will see the modification time of file has changed and reopen it.

**Comment by EdHurtig** [comment]
@mcbain If you read through [spooler.go](https://github.com/elastic/logstash-forwarder/blob/3b718f0d3ed6da36ac7792b45b8541f263cadb59/spooler.go) the idle timeout defines the time that an event can be held in the spooler before being sent to the Logstash server.

**Comment by jordansissel** [comment]
Not in favor of another flag; I wish I hadn't used both flag and config file (they're the same concept but different syntaxes). If anything, this should be a setting in the config file under networking.

**Comment by EdHurtig** [comment]
@jordansissel I personally agree with that assessment and was thinking the same, but since there was a history of Idle timeout on the CLI it seemed like the way to go

**Comment by EdHurtig** [comment]
I would be totally in favor of adding an option in the config file if that's approved

**Comment by ruflin** [comment]
This is now available as a config option in filebeat (future replacement of logstash-fowarder): https://github.com/elastic/filebeat/blob/master/etc/filebeat.yml#L68

@EdHurtig I will close this issue. Please reopen if this will not solve the issue.
