### ISSUE TITLE
registry rotate fails on linux?

### ISSUE THREAD

**Issue by allenmchan** [elastic/logstash-forwarder#466]
I am getting this error in the logs. Running the latest and greatest 0.4.0
From googling i see that this is supposed to be for windows. Why do i get this error messages on linux?

    2015/05/22 17:38:37.884314 registry rotate: rename of .logstash-forwarder.new to .logstash-forwarder - rename .logstash-forwarder.new .logstash-forwarder: no such file or directory
    2015/05/22 17:38:37.884330 WARNING: (continuing) update of registry returned error: rename .logstash-forwarder.new .logstash-forwarder: no such file or directory

**Comment by driskell** [comment]
Registry is written to the working directory (the one you were in when you started forwarder). For rpm Deb I believe it's somewhere in /var/lib

If the user you run forwarder as does not have access to write to the folder you might get this error. Can you check permissions?

**Comment by allenmchan** [comment]
There is a .logstash-forwarder file in /opt/logstash-forwarder. Why is logstash-forwarder trying to rotate this file? It kind of doesnt make sense. 

    $ locate .logstash-forwarder
    /opt/logstash-forwarder/.logstash-forwarder

There is a /var/lib/logstash-forwarder folder but it is empty

    $ ls -lah /var/lib/logstash-forwarder/
    total 12K
    drwxrwxr-x  2 logstash-forwarder logstash-forwarder 4.0K Mar  4 12:32 .
    drwxr-xr-x 21 root               root               4.0K Apr 23 22:26 ..

**Comment by allenmchan** [comment]
The other suspicious thing is that the word "rotate" only appears in "registrar_other.go" and "registrar_windows.go". The regular "registrar.go" file has no mention of rotation.

**Comment by driskell** [comment]
It saves progress to that file so it can resume. To prevent corrupting the file it creates a new one first and then replaces the old.

Yes only other and windows registrar files will mention it - those files are where the movement happens.

How are you running forwarder? As what user? What is the ownership of /opt/logstash-forwarder?

**Comment by allenmchan** [comment]
using /etc/init.d file as root. 

    chroot "$chroot"  su logstash-forwarder -c "
    cd /opt/logstash-forwarder
    exec \"$program\" $args" > /var/log/logstash-forwarder/$name.log 2> /var/log/logstash-forwarder/$name.err &

dir is owned by logstash-forwarder user

    $ ls -lah /opt/logstash-forwarder/
    total 32K
    drwxr-xr-x 3 logstash-forwarder logstash-forwarder 4.0K May 23 20:40 .
    drwxr-xr-x 6 root               root               4.0K Apr  9 13:56 ..
    -rw-r--r-- 1 logstash-forwarder logstash-forwarder   33 Sep 16  2014 .bash_logout
    -rw-r--r-- 1 logstash-forwarder logstash-forwarder  176 Sep 16  2014 .bash_profile
    -rw-r--r-- 1 logstash-forwarder logstash-forwarder  124 Sep 16  2014 .bashrc
    drwxr-xr-x 2 logstash-forwarder logstash-forwarder 4.0K Apr 23 22:26 bin
    -rw-r--r-- 1 logstash-forwarder logstash-forwarder  469 May 23 20:40 .logstash-forwarder

**Comment by drocsid** [comment]
The irony, this is broken in windows:

https://github.com/elastic/logstash-forwarder/issues/484

**Comment by ruflin** [comment]
This issue should be fixed in filebeat (the next version of logstash-forwarder): https://github.com/elastic/filebeat

Please reopen an issue in filebeat directly in case this issue should occur again.
