### ISSUE TITLE
Always Shipping all Lines of File

### ISSUE THREAD

**Issue by 00WCEnte** [elastic/logstash-forwarder#468]
Hi
if a service append a new Line to a Log-File, my Logstash Forwarder is shipping all old Lines. He should only ship the new Entry.
My Logfile of Logstash Forwarder

    2015/06/03 14:55:31.820711 Registrar: processing 1024 events
    2015/06/03 14:55:35.754922 Registrar: processing 1024 events
    2015/06/03 14:55:39.582545 Registrar: processing 1024 events
    2015/06/03 14:55:42.611778 Registrar: processing 1024 events
    2015/06/03 14:55:46.014887 Registrar: processing 1024 events
    2015/06/03 14:55:48.411491 Registrar: processing 1024 events
    2015/06/03 14:55:50.763360 Registrar: processing 1024 events
    2015/06/03 14:55:53.399806 Registrar: processing 1024 events
    2015/06/03 14:55:55.484494 Registrar: processing 1024 events
    2015/06/03 14:55:58.666032 Registrar: processing 1024 events
    2015/06/03 14:56:01.510382 Registrar: processing 312 events
    2015/06/03 14:56:55.828544 Launching harvester on rotated file: /var/log/parallels.log
    2015/06/03 14:56:55.828620 harvest: "/var/log/parallels.log" (offset snapshot:0)
    2015/06/03 14:56:58.952266 Registrar: processing 1024 events
    2015/06/03 14:57:00.926858 Registrar: processing 1024 events
    2015/06/03 14:57:02.758036 Registrar: processing 1024 events
    2015/06/03 14:57:06.014444 Registrar: processing 1024 events
    2015/06/03 14:57:08.047190 Registrar: processing 1024 events
    2015/06/03 14:57:09.722073 Registrar: processing 1024 events
    2015/06/03 14:57:11.150989 Registrar: processing 1024 events
    2015/06/03 14:57:12.873296 Registrar: processing 1024 events
    2015/06/03 14:57:14.316187 Registrar: processing 1024 events
    2015/06/03 14:57:16.076463 Registrar: processing 1024 events
    2015/06/03 14:57:18.857244 Registrar: processing 313 events

My Config

    {
      "network": {
        "servers": [ "logstash:5000" ],
        "timeout": 15,
        "ssl ca": "/tmp/logstash-forwarder.crt",
        "ssl key": "/tmp/logstash-forwarder.key"
      },
      "files": [
        {
          "paths": [
            "/var/log/parallels.log"
           ],
          "fields": { "type": "log-file" }
        }
       ]
    }

Can someone help me?

**Comment by driskell** [comment]
How did you add a new line? It looks like rather than adding a new line, the log file was replaced with a new one containing all previous entries and the new line, thus it sees it all as new.

**Comment by 00WCEnte** [comment]
ok my fault. if i append with >> he is processing only one event. Sorry!
