### ISSUE TITLE
too many open files error with forwarder

### ISSUE THREAD

**Issue by RanjitShinde1** [elastic/logstash-forwarder#472]
Hi , 
I am using forwarder to process impression logs.
My forwarder file contains  : 
"files": [
    {
      "paths": [ "/usr/share/tomcat/impression_logs/archives/impressions*.log"]
    }
  ]

After dome time forwarder stops processing logs and gives below error:

2015/06/15 04:47:07.825153 Launching harvester on new file: /usr/share/tomcat/impression_logs/archives/impressions.2015-06-15-04-46.0.log
2015/06/15 04:47:07.825222 harvest: "/usr/share/tomcat/impression_logs/archives/impressions.2015-06-15-04-46.0.log" (offset snapshot:0)
2015/06/15 04:47:10.246291 Registrar: processing 14 events
2015/06/15 04:47:10.254400 Failed to create tempfile (.logstash-forwarder.new) for writing: open .logstash-forwarder.new: too many open files
2015/06/15 04:47:10.254416 WARNING: (continuing) update of registry returned error: open .logstash-forwarder.new: too many open files

I guess forwarder keep watch on all files for 24 Hours, is their any way to reduce that time?

**Comment by RanjitShinde1** [comment]
This works using:
 {
      "paths": [ "/usr/share/tomcat/impression_logs/archives/impressions*.log"],
       "dead time": "1h"
    }
set dead time attribute

**Comment by jordansissel** [comment]
> I guess forwarder keep watch on all files for 24 Hours, is their any way to reduce that time?


If you have lots of files lsf could watch, then you'll need to increase the open file count limit that logstash-forwarder is given. The default on most linux systems is 1024, you can raise this with `ulimit -n 10000` and raises it to 10,000. Raising requires root privileges.
