### ISSUE TITLE
Ability to execute commands

### ISSUE THREAD

**Issue by AtzeDeVries** [elastic/logstash-forwarder#478]
It would be nice if logstash forwarder could execute a command like the logstash exec{} input. 
At a certain server i wish not to use de full client but need info from a command. 
If i use cron to execute the command the timestamp is uncertain.

**Comment by tbragin** [comment]
This is potentially a good idea for a new beat - we should love it to the libbeat repo: https://github.com/elastic/libbeat/issues

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by https://github.com/elastic/filebeat/. If this is still an issue with filebeat, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
