### ISSUE TITLE
Refactor Publishv1 function

### ISSUE THREAD

**Issue by otm** [elastic/logstash-forwarder#479]
I have a use case where I would like to use a different way to send messages (in my case Kinesis). What I would like to do is refactor the function Publishv1 by creating an `publisher` interface. Then it would be easy to swap out the publisher if one does not wish to use lumberjack. 

If this is interesting I could contribute the code as the rewrite is minimal.

That is, in logstash-forwarder.go it would look something like this.
```
type publisher interface {
	Run(chan []*FileEvent, chan []*FileEvent)
}

// instead of calling "go Publishv1(...)"
var publish publisher
publish = NewLumberjackPublisher(config.Network)
go publish.Run(publisher_chan, registrar_chan)
```

Maybe the interface should look like the one bellow to make sure the channels are used in a correct way.
```
type publisher interface {
	Run(<-chan []*FileEvent, chan<- []*FileEvent)
}
```

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better! 

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
