### ISSUE TITLE
Issue with Forwarder connecting.

### ISSUE THREAD

**Issue by Creibold** [elastic/logstash-forwarder#480]
Hello,

I have recently encountered an issue with my logstash setup. I currently have 4 logstash-forwarders sending over postfix logs to my elasticsearch machine. Up until today, they were working fine. However, I keep seeing this type of activity:

>2015/06/25 16:34:51.974713 Connected to 10.0.0.238
2015/06/25 16:38:11.976066 Read error looking for                                  ack: read tcp 10.0.0.238:5000: i/o timeout
2015/06/25 16:38:11.976138 Setting trusted CA from                                  file: /etc/pki/tls/certs/logstash-forwarder.crt
2015/06/25 16:38:11.976400 Connecting to [10.0.0.2                                 38]:5000 (10.0.0.238)
2015/06/25 16:38:12.029742 Connected to 10.0.0.238
2015/06/25 16:41:32.031308 Read error looking for                                  ack: read tcp 10.0.0.238:5000: i/o timeout
2015/06/25 16:41:32.031373 Setting trusted CA from                                  file: /etc/pki/tls/certs/logstash-forwarder.crt
2015/06/25 16:41:32.031631 Connecting to [10.0.0.2                                 38]:5000 (10.0.0.238)
2015/06/25 16:41:32.084914 Connected to 10.0.0.238
2015/06/25 16:44:52.086317 Read error looking for                                  ack: read tcp 10.0.0.238:5000: i/o timeout
2015/06/25 16:44:52.086412 Setting trusted CA from                                  file: /etc/pki/tls/certs/logstash-forwarder.crt
2015/06/25 16:44:52.086673 Connecting to [10.0.0.2                                 38]:5000 (10.0.0.238)
2015/06/25 16:44:52.140071 Connected to 10.0.0.238

Killing the logstash service on the elasticsearch machine lets some logs through, but it slows down fast and soon I'm back to I/O timeouts.

I also see a lot of open connections with close_wait on my elasticsearch machine, when I perform a `netstat` command - I am not sure if this is related:

>tcp6       1      0 10.0.0.238:5000         10.0.0.131:51083        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:54631        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:39991         CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:52489        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:39729         CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:39984         CLOSE_WAIT
tcp6       0      0 10.0.0.238:60101        10.0.0.238:9301         ESTABLISHED
tcp6       1      0 10.0.0.238:5000         10.0.0.130:52777        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:54056        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.128:48768        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:40217         CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:40005         CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.131:51840        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.131:50850        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.131:51370        CLOSE_WAIT
tcp6       0      0 localhost:50707         localhost:9300          ESTABLISHED
tcp6       1      0 10.0.0.238:5000         10.0.0.130:54563        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:53384        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:40020         CLOSE_WAIT
tcp6       0      0 10.0.0.238:9301         10.0.0.238:60081        ESTABLISHED
tcp6       1      0 10.0.0.238:5000         10.0.0.130:55381        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:53923        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.128:49020        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.131:51555        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:54903        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:40252         CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:53514        CLOSE_WAIT
tcp6       0      0 localhost:9300          localhost:50706         ESTABLISHED
tcp6       1      0 10.0.0.238:5000         10.0.0.131:51428        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.128:49096        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.128:48910        CLOSE_WAIT
tcp6       0      0 localhost:50946         localhost:9200          ESTABLISHED
tcp6       1      0 10.0.0.238:5000         10.0.0.130:55459        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:52357        CLOSE_WAIT
tcp6       0      0 localhost:50227         localhost:9300          ESTABLISHED
tcp6       1      0 10.0.0.238:5000         10.0.0.128:49248        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:39983         CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.128:50411        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.131:51206        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.128:50433        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:54844        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:40219         CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.128:49649        CLOSE_WAIT
tcp6       0      0 10.0.0.238:60079        10.0.0.238:9301         ESTABLISHED
tcp6       1      0 10.0.0.238:5000         10.0.0.128:49913        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.15:40248         CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:55063        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.131:50273        CLOSE_WAIT
tcp6       1      0 10.0.0.238:5000         10.0.0.130:52120        CLOSE_WAIT
tcp6       0      0 localhost:9300          localhost:50705         ESTABLISHED
tcp6       0      0 10.0.0.238:5000         10.0.0.128:50454        ESTABLISHED
tcp6       0      0 localhost:9300          localhost:50230         ESTABLISHED
tcp6       0      0 10.0.0.238:5000         10.0.0.128:50430        ESTABLISHED
tcp6       0      0 localhost:50705         localhost:9300          ESTABLISHED
tcp6       0      0 localhost:50695         localhost:9300          ESTABLISHED

Any help with this would be greatly appreciated, I've been trying to figure it out all day!

Versions used: 
Elasticsearch - 1.5.2
Logstash - 1.5.0

**Comment by jordansissel** [comment]
>  2015/06/25 16:38:12.029742 Connected to 10.0.0.238
> 2015/06/25 16:41:32.031308 Read error looking for ack: read tcp 10.0.0.238:5000: i/o timeout

This usually  means that Logstash got stuck (in a filter or an output) trying to process your data. Are you certain Logstash is functioning correctly? Is it able to output events?

**Comment by Creibold** [comment]
The logstash forwarder does ship logs for a certain amount of time, then I receive the I/O errors:

>2015/06/25 20:05:14.963253 Connected to 10.0.0.238
2015/06/25 20:05:28.691870 Registrar: processing 1024 events
2015/06/25 20:05:34.968679 Registrar: processing 1024 events
2015/06/25 20:05:46.391921 Registrar: processing 1024 events
2015/06/25 20:05:55.426045 Registrar: processing 1024 events
2015/06/25 20:05:59.476915 Registrar: processing 1024 events
2015/06/25 20:06:10.479320 Registrar: processing 1024 events
2015/06/25 20:06:18.846579 Registrar: processing 1024 events
2015/06/25 20:06:47.116176 Registrar: processing 1024 events
2015/06/25 20:07:01.623500 Registrar: processing 1024 events
2015/06/25 20:07:11.106710 Registrar: processing 1024 events
2015/06/25 20:07:15.496984 Registrar: processing 1024 events
2015/06/25 20:07:29.075263 Registrar: processing 1024 events
2015/06/25 20:08:11.100764 Registrar: processing 1024 events
2015/06/25 20:11:31.105790 Read error looking for ack: r                              ead tcp 10.0.0.238:5000: i/o timeout
2015/06/25 20:11:31.105872 Setting trusted CA from file:                               /etc/pki/tls/certs/logstash-forwarder.crt
2015/06/25 20:11:31.106146 Connecting to [10.0.0.238]:50                              00 (10.0.0.238)
2015/06/25 20:11:31.164877 Connected to 10.0.0.238

The forwarder then goes into this cycle of connecting, timing out, connecting, and timing out.

**Comment by driskell** [comment]
It's highly likely logstash can't keep up with the rate of logs. Increase forwarder network timeout and decrease forwarder spool size and eventually you'll hit the right values.
Failing that another option is to try Log Courier which is built to handle situations like this.

**Comment by Creibold** [comment]
Thank you,

I apologize for my ignorance on this subject - how do I set the Spool size? Is it also simply a line added into the conf file? Below is my current config:



>{
  "network": {
    "servers": [ "10.0.0.238:5000" ],
    "timeout": 30,
    "ssl ca": "/etc/pki/tls/certs/logstash-forwarder.crt"
  },
  "files": [
    {
      "paths": [
        "/var/log/maillog"
       ],	
      "fields": { "type": "postfix" }
    }
   ]

**Comment by Creibold** [comment]
Nevermind, I simple used -spool-size=500 with my normal logstash-forwarder command and that seemed to work.

**Comment by Creibold** [comment]
Odd - still having the issue, even when I turn down the spool to under 200. It still eventually times out Also, when I restart elasticsearch, it's very snappy at displaying data I search for, but it eventually gets extremely slow, noticeably when I start up logstash and I see logs shipping. Do you think this is some sort of resource error? I am currently running logstash and elasticsearch on the same machine with only one node - perhaps there is a performance issue when files get too large in ubuntu 14.04 (OS on the machine).?

**Comment by driskell** [comment]
Does CPU usage drop or stay high?

It's either a blocked pipeline happening randomly which means clients timeout and reconnect. (Latest plugin for lumberjack should help - maybe try updating it - `bin/plugin update logstash-input-lumberjack`)
Other cause is just logs coming too fast for the logstash to process them - this is where high timeout values and low spool sizes help.

**Comment by Creibold** [comment]
CPU usage is generally High, and sometimes it's over 100% for elasticsearch, but Ubuntu is sitting on an 8-core system with 16 gigs of RAM, I had thought that would be way more than enough. I am also unsure if it's only hitting 1 core or not:

>PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
14588 elastic+  20   0 8858768 1.505g 354404 S 160.9  9.6  50:51.18 java
 1120 root      20   0 1012924 108888  10032 S   1.0  0.7   0:03.29 node

For instance, it's stating it's hitting 160% of CPU but only 9.6% of ram?

I was able to get these numbers when performing a dashboard load in kibana4. 

Onto logstash - that update helped, somewhat. I am now seeing a different error all-together: `Read error looking for ack: EOF`

See here:

>2015/06/26 15:22:48.316360      --- options -------
2015/06/26 15:22:48.316484      config-arg:          /etc/logstash-forwarder.conf
2015/06/26 15:22:48.316530      idle-timeout:        5s
2015/06/26 15:22:48.316558      spool-size:          200
2015/06/26 15:22:48.316581      harvester-buff-size: 16384
2015/06/26 15:22:48.316603      --- flags ---------
2015/06/26 15:22:48.316626      tail (on-rotation):  false
2015/06/26 15:22:48.316648      log-to-syslog:          false
2015/06/26 15:22:48.316668      quiet:             false
2015/06/26 15:22:48.316718 {
  "network": {
    "servers": [ "10.0.0.238:5000" ],
    "timeout": 30,
    "ssl ca": "/etc/pki/tls/certs/logstash-forwarder.crt"
  },
  "files": [
    {
      "paths": [
        "/var/log/maillog"
       ],
      "fields": { "type": "postfix" }
    }
   ]
}


>2015/06/26 15:22:48.317246 Loading registrar data from /usr/local/logstash-forwarder/.logstash-forwarder
2015/06/26 15:22:48.317321 Waiting for 1 prospectors to initialise
2015/06/26 15:22:48.317395 Resuming harvester on a previously harvested file: /var/log/maillog
2015/06/26 15:22:48.317438 Registrar will re-save state for /var/log/maillog
2015/06/26 15:22:48.317463 All prospectors initialised with 1 states to persist
2015/06/26 15:22:48.317512 harvest: "/var/log/maillog" position:26701268 (offset snapshot:26701268)
2015/06/26 15:22:48.317615 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
2015/06/26 15:22:48.318026 Connecting to [10.0.0.238]:5000 (10.0.0.238)
2015/06/26 15:22:48.372184 Connected to 10.0.0.238
2015/06/26 15:22:50.379276 Read error looking for ack: EOF
2015/06/26 15:22:50.379430 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
2015/06/26 15:22:50.379788 Connecting to [10.0.0.238]:5000 (10.0.0.238)
2015/06/26 15:22:50.434245 Connected to 10.0.0.238
2015/06/26 15:22:50.436528 Read error looking for ack: EOF
2015/06/26 15:22:50.436635 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
2015/06/26 15:22:50.436945 Connecting to [10.0.0.238]:5000 (10.0.0.238)

**Comment by jordansissel** [comment]
> Read error looking for ack: EOF

This error means that Logstash (or something on the network between lsf and Logstash) terminated the connection. Check the Logstash logs?

**Comment by Creibold** [comment]
I apologize, I am a bit new to this.

I found this in logstash.err:

>Jun 26, 2015 2:09:08 PM org.elasticsearch.transport.TransportService$Adapter checkForTimeout
WARNING: [logstash-STL-LOG-01-14695-9824] Received response for a request that has timed out, sent [43326ms] ago, timed out [13326ms] ago, action [internal:discovery/zen/fd/master_ping], node [[Mister Fear][RzzCh9B2Tc6zhRSYQ54QJA][STL-LOG-01][inet[/127.0.0.1:9300]]], id [774]

**Comment by driskell** [comment]
I find running logstash manually on the command line just for testing gets better events. Sometimes the log file is buffered so errors get hidden. Can you try running logstash on command line and monitor output directly?

**Comment by Creibold** [comment]
Issue solved.

Turns out the heap size was still on default for elasticsearch, I upped it to 8 gigs and everything worked. It's hard to imagine the machine was able to do so much on only 1 gig of ram.
