### ISSUE TITLE
Filter logs before send to LOGSTASH server

### ISSUE THREAD

**Issue by rhuankarlus** [elastic/logstash-forwarder#482]
It would be awesome if we could filter logs before send it to LOGSTASH central server. So, we could send only WARN or ERROR logs and have no Overhead in clients.

**Comment by nixfloyd** [comment]
I guess this is something more people are interested in

**Comment by gabrielcbnetto** [comment]
This would be interesting.

**Comment by ruflin** [comment]
Would it be sufficient to have a regexp in the config and in case a line matches the regexp, it is sent, otherwise not (or the other way around)?

**Comment by ankitmobicip** [comment]
This is would exactly be what I want! :)

**Comment by ruflin** [comment]
I opened an issue directly in filebeat: https://github.com/elastic/filebeat/issues/78 Please move all future discussions there.
