### ISSUE TITLE
file offset tracking is broken in windows

### ISSUE THREAD

**Issue by drocsid** [elastic/logstash-forwarder#484]
I installed and ran the logstash .40 Windows binary provided by https://www.elastic.co/downloads/logstash . It created a file .logstash-forwarder.new. Then in standard out, I read:

2015/07/08 15:17:04.014059 registry rotate: rename of .logstash-forwarder to .logstash-forwarder.old - rename .logstash-forwarder .logstash-forwarder.old: The system cannot find the file specified.

After restarting the binary again, I saw the same message.

Finally I renamed the file to .logstash-forwarder, and the standard out displayed:

2015/07/08 17:08:26.117925 registry rotate: rename of .logstash-forwarder to .logstash-forwarder.old - rename .logstash-forwarder .logstash-forwarder.old: The process cannot access the file because it is being used by another process.

However I believe the only process that should have the file open is lsf. Then there is another issue with the process handling the file.

It appears there is an issue with offset tracking in logstash-forwarder for Windows. This should be a relatively simple fix, for whoever is responsible for the Windows build.

**Comment by ruflin** [comment]
This should be fixed in filebeat (next version of logstash-forwarder) with https://github.com/elastic/filebeat/pull/43 and https://github.com/elastic/filebeat/pull/45

**Comment by ruflin** [comment]
As the next release of logstash-forwarder will be [filebeat](https://github.com/elastic/filebeat), I will close this issue based on the comment above. In case the issue still exists in filebeat, please reopen or open a new issue directly in the filebeat repo.
