### ISSUE TITLE
Forwarder Support for Windows Event Logs

### ISSUE THREAD

**Issue by sgerlach** [elastic/logstash-forwarder#485]
Trying to find a solution for using logstash forwarder to read and forward windows event logs. I'm not having luck finding supporting documentation so I'm curious if it's even supported at this point. If it's not... feature request? :)

current config seems to not work as follows (windows 2012 server)
{
    "network": {
        "servers": [ "logstash-server"],
        "timeout": 15
    },
    "files": [
        {
          "paths": [
            "c:\\windows\\system32\\winevt\\Logs\\Security.evtx"
           ]
        }
    ]
}

I am aware of nxlog and we are testing it, but trying to test out all solutions.

**Comment by SrikanthKS** [comment]
+1

**Comment by lucashenning** [comment]
+1 I'd love to see this working!

**Comment by chiriaev** [comment]
+1

**Comment by pmonson711** [comment]
:+1:

**Comment by orangey** [comment]
Capturing Windows Event Logs probably requires consumption of the Windows event API, not reading the binary log files. This is done, for example, in [nxLog](http://nxlog-ce.sourceforge.net/download) and I would love to see the same support in logstash-forwarder

**Comment by thebiggestlebowski** [comment]
Thanks for this great tool.  Agree it would be even better if it can grab windows event log data.

**Comment by tbragin** [comment]
Migrated to Filebeat, closing here.
