### ISSUE TITLE
LSF 0.40 RHEL 5 init script issue.

### ISSUE THREAD

**Issue by lmorfitt** [elastic/logstash-forwarder#486]
Hello,
I've downloaded the latest build of LSF from here. Installed it on a RHEL 5 box.

The service will not start due to a issue with the chroot version.

```bash

bash -x /etc/init.d/logstash-forwarder start
+ PATH=/sbin:/usr/sbin:/bin:/usr/bin
+ export PATH
+ name=logstash-forwarder
+ program=/opt/logstash-forwarder/bin/logstash-forwarder
+ args='-config /etc/logstash-forwarder.conf'
+ pidfile=/var/run/logstash-forwarder.pid
+ '[' -r /etc/default/logstash-forwarder ']'
+ . /etc/default/logstash-forwarder
++ user=root
++ group=root
++ chroot=/
++ chdir=/var/lib/logstash-forwarder
++ nice=
+ '[' -r /etc/sysconfig/logstash-forwarder ']'
+ case "$1" in
+ trace 'Attempting '\''start'\'' on logstash-forwarder'
+ logger -t /etc/init.d/logstash-forwarder 'Attempting '\''start'\'' on logstash-forwarder'
+ case "$1" in
+ status
+ '[' -f /var/run/logstash-forwarder.pid ']'
++ cat /var/run/logstash-forwarder.pid
+ pid=5505
+ ps -p 5505
+ return 2
+ code=2
+ '[' 2 -eq 0 ']'
+ start
+ chroot --userspec root:root / sh -c '
    
    cd "/var/lib/logstash-forwarder"
    exec "/opt/logstash-forwarder/bin/logstash-forwarder" -config /etc/logstash-forwarder.conf
  '
+ echo 5568
+ emit 'logstash-forwarder started'
+ trace 'logstash-forwarder started'
+ logger -t /etc/init.d/logstash-forwarder 'logstash-forwarder started'
+ echo 'logstash-forwarder started'
logstash-forwarder started
+ return 0
+ exit 0

```

However I see the below in the log file

```log
cat /var/log/logstash-forwarder/logstash-forwarder.err 
chroot: invalid option -- -
Try `chroot --help' for more information.
chroot: invalid option -- -
Try `chroot --help' for more information.
```

As far as I can tell the init script is expecting a specific version of chroot, which allows the use of 'chroot --userspec root:root' 

This is not available on RHEL5 and variants. 

```bash

chroot --help
Usage: chroot NEWROOT [COMMAND...]
  or:  chroot OPTION
Run COMMAND with root directory set to NEWROOT.

      --help     display this help and exit
      --version  output version information and exit

If no command is given, run ``${SHELL} -i'' (default: /bin/sh).

Report bugs to <bug-coreutils@gnu.org>.

 chroot --version
chroot (GNU coreutils) 5.97

```

thoughts please.

thanks,
Luke

**Comment by jordansissel** [comment]
RHEL 5 was released 8 years ago and is not well-supported at this time. Some options:

- You may have to roll your own init script or modify the one our RPM provides.
- or, Upgrade your version of chroot
- or, Add a new sysv implementation for [pleaserun](https://github.com/jordansissel/pleaserun) that targets RHEL 5(*)

(*) Pleaserun is used to generate the init script

**Comment by lmorfitt** [comment]
I agree RHEL 5 is a little dated at this point. I do feel that it is still used within large infrastructure environments. I still have some RHEL4 boxes which I need to replace( no LSF needed). The issue in both of these cases is that the client does not see the benefit of replacing them and thus will keep them as long as possible.

I need to stick with a platform with vendor support so moving of out of tree chroot installation is not a option at this time.

The quick hack was as follows. 

replace the below segment

```bash
chroot --userspec root:root / sh -c '

    cd "/var/lib/logstash-forwarder"
    exec "/opt/logstash-forwarder/bin/logstash-forwarder" -config /etc/logstash-forwarder.conf
  '
``` 

with

```bash
 sh -c '

    cd "/var/lib/logstash-forwarder"
    exec "/opt/logstash-forwarder/bin/logstash-forwarder" -config /etc/logstash-forwarder.conf
  '
```

Whilst this is not ideal it seems the least intrusive way to implement the change for the few RHEL5 servers we have.

I'm not sure if this can be easily implemented with pleaserun. 

thanks
Luke

**Comment by israelshirk** [comment]
I've had the same issue; we're stuck on RHEL5 for the moment due to many of our clients (public utilities) having severe regulatory burdens which make infrastructure changes rather painful.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better! 

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
