### ISSUE TITLE
tls: oversized record

### ISSUE THREAD

**Issue by daemonza** [elastic/logstash-forwarder#489]
Using the latest logstash-forwarder, I create the SSL certificates using 

```
openssl req -x509 -subj '/CN=*/' -nodes -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt
```

However I keep on getting : 

```
2015/07/16 16:12:56.820092 Failed to tls handshake with 192.168.1.1 tls: oversized record received with length 20527
```

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better! 

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
