### ISSUE TITLE
Using Logstash-forwarder for HP-UX Or AIX

### ISSUE THREAD

**Issue by HWANGDUKRAE** [elastic/logstash-forwarder#492]
I used logstash-forwarder on CentOS Linux, also I want to use on HP-UX, AIX.........
You teach me method complie or execute, If you knows method.......
Or I not used logstash-forwarder on UNIX Systems.
Thank you.

**Comment by jordansissel** [comment]
HP-UX and AIX are not supported by the language logstash-forwarder is written in, so at this time there is no way I know of to get this to work.

**Comment by jordansissel** [comment]
The Go language implementors are not implementing support for AIX, at least right now, so I don't think there's anything for us to do at this time.
