### ISSUE TITLE
Event log forwarded from windows not being parsed by logstash

### ISSUE THREAD

**Issue by SrikanthKS** [elastic/logstash-forwarder#493]
I have a windows server from which event logs are being forwarded by LSF. These are received by LF on a linux box. This is how my config files look like - 

LSF on Windows box - 

        {
            "network": {

               "servers": [ "myServer.com:5100" ],
               "ssl ca": "lumberjack.crt",
	           "timeout": 15
            },

            "files": [
             {
                  "paths": [ "C:\\Windows\\System32\\Winevt\\Logs\\Application.evtx"],
                  "fields": { "type": "json" }
              }
           ]
        }

LF on Linux box - 

        input {
            lumberjack {
                     port => 5100
                     ssl_certificate => "/tmp/lumberjack.crt"
                     ssl_key => "/tmp/lumberjack.key"
                     type => "json"
             }
         }

         filter {
            if [type] == "json" {
               json {
                   source => "message"
          }
         }

         output {
                tcp {
                    host => 'myTarget.com'
                    port => '7090'
                 }
               stdout {
                    codec => rubydebug
                }
            }

When I run logstash, I get the error below - 

         {
       "message" => "\u0000\u0000\u0000\u008Cã»\u0002ôì»\u0002Bmwrhm-\u0000\u001C\u0000\u0000\u0000\u0004\u0000\u0000\u0000",
      "@version" => "1",
    "@timestamp" => "2015-07-22T21:46:04.170Z",
          "type" => "json",
          "file" => "C:\\Windows\\System32\\Winevt\\Logs\\Application.evtx",
          "host" => "myHost",
        "offset" => "315478",
          "tags" => [
        [0] "_jsonparsefailure"
    ]
     }

Please note that I have tried enforcing " codec => plain { charset => "UTF-8" } " in LF config file initially but it didn't really help.

Anything I am doing wrong? Any help will put me out of my misery! Thank you.

**Comment by SrikanthKS** [comment]
More updates - 

I am looking for the right filter to use for Windows event log being forwarded by LSF. I usually see LF on both the ends in which case it's pretty straight forward for sending and receiving the event logs. So please let me know if there is grok/grep pattern that can help LF understand LSF. Thanks!

**Comment by jordansissel** [comment]
lsf doesn't currently support forwarding binary log formats such as the windows event log files.

**Comment by jordansissel** [comment]
Let's discuss this more in #485 since I believe it to be related. I'm closing this in favor of having the discussion over in #485 :)
