### ISSUE TITLE
Enable to configure path for .logstash-forwarder

### ISSUE THREAD

**Issue by timukas** [elastic/logstash-forwarder#496]
Hi,

Currently .logstash-forwarder is created in directory where you start LSF.
This is not very convenient, when you kill and then start LSF from other location.
Would be nice to have a configuration parameter for location of .logstash-forwarder file.

**Comment by palmerabollo** [comment]
I think this issue is duplicated and should be closed. See https://github.com/elastic/logstash-forwarder/issues/450

**Comment by suyograo** [comment]
Duplicate https://github.com/elastic/logstash-forwarder/issues/505

**Comment by suyograo** [comment]
Dup of #450
