### ISSUE TITLE
repository is dead and undocumented

### ISSUE THREAD

**Issue by zabbal** [elastic/logstash-forwarder#500]
While checking why packages.elasticsearch.org appears to be down I've noticed that
http://packages.elasticsearch.org/logstashforwarder/debian
packages link is undocumented in the README - it only appears in the comments to some issues.

This is the crucial information for the maintainability of any production installation and hence it should appear in README (there's even dedicated section about it already, it's just rather empty). And of course documented thing should be working.

**Comment by suyograo** [comment]
The deb repo is available here: https://download.elastic.co/logstash-forwarder/binaries/logstash-forwarder_0.4.0_amd64.deb

Also, 0.4.0 has been pushed to packages.elasticsearch.org

**Comment by zabbal** [comment]
I'm looking for something which I can add to /etc/apt/sources.list.d/ to get updates automatically.

**Comment by ph** [comment]
@zabbal  adding this to a source should work

`deb http://packages.elasticsearch.org/logstash/1.5/debian stable main`

**Comment by zabbal** [comment]
Out of curiosity - why packages.elasticsearch.org does not respond to ping although wget seems to work fine?

**Comment by jordansissel** [comment]
@zabbal because it seems Amazon ELB will ignore ICMP ECHO.

**Comment by zabbal** [comment]
Would be nice to get this documented alongside with the address somewhere more accessible than issue comments. Like readme or wiki page.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
