### ISSUE TITLE
In -quiet mode, logstash-forwarder does not log when it can't connect to any servers

### ISSUE THREAD

**Issue by mjs510** [elastic/logstash-forwarder#501]
If you run logstash-forwarder with -quiet, it does not cause any information to be logged in the situation when it cannot connect to any logstash servers. Here's an example from my logs when not running with -quiet mode:

Aug  3 10:49:58 server0 logstash-forwarder[28201]: 2015/08/03 10:49:58.653284 Connecting to [192.168.0.14]:5043 (logs0) 
Aug  3 10:49:58 server0 logstash-forwarder[28201]: 2015/08/03 10:49:58.672622 Failed to tls handshake with 192.168.0.14 x509: certificate has expired or is not yet valid
Aug  3 10:49:59 server0 logstash-forwarder[28201]: 2015/08/03 10:49:59.673676 Connecting to [192.168.0.51]:5043 (logs1) 
Aug  3 10:49:59 server0 logstash-forwarder[28201]: 2015/08/03 10:49:59.720888 Failed to tls handshake with 192.168.0.51 x509: certificate has expired or is not yet valid
[...]

In fact logstash-forwarder can't connect to any of its servers, so this is crucial information. However, with -quiet, nothing is output and it is not possible to detect from the logs that there is a problem.

logstash-forwarder should either log these messages regardless of -quiet mode, or should maybe log a new error message to say that it's unable to connect to any servers?

**Comment by robinjmurphy** [comment]
+1 This makes things very hard to debug!

Looks like the problem is that the error is logged using `emit`

```go
if err != nil {
    emit("Failed to tls handshake with %s %s\n", address, err)
    time.Sleep(1 * time.Second)
    socket.Close()
    continue
}
```

https://github.com/elastic/logstash-forwarder/blob/master/publisher1.go#L199

And `emit` simply returns if quiet mode is enabled

```go
// REVU: yes, this is a temp hack.
func emit(msgfmt string, args ...interface{}) {
	if options.quiet {
		return
	}
	log.Printf(msgfmt, args...)
}
```
https://github.com/elastic/logstash-forwarder/blob/master/logstash-forwarder.go#L216-L218

**Comment by robinjmurphy** [comment]
I've created a pull request to fix the handshake log. It may be that we need a better solution that creates the concept of a fatal/important error to be logged regardless of quiet mode.

https://github.com/elastic/logstash-forwarder/pull/503

**Comment by Eronarn** [comment]
+1, I've been bitten by this one several times.

**Comment by urso** [comment]
filebeat logger supports log levels. Failed connection attempts will be logged with [error level](https://github.com/elastic/libbeat/blob/master/outputs/lumberjack/transport.go#L127)
