### ISSUE TITLE
Support IPv6 addresses

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash-forwarder#504]
From https://github.com/elastic/logstash/issues/1935

---------------------------------------------------------

I have a logstash server running locally with following host name

2014-10-22 15:06:59 UTC [root@soichi6:/etc/grid-security/logstash]# host soichi.goc
soichi.goc has address 192.168.97.116
soichi.goc has IPv6 address fd2f:6feb:37:1::74

I have installed logstash-forwarder from http://packages.elasticsearch.org/logstashforwarder/centos/logstash-forwarder-0.3.1-1.x86_64.rpm and configured logstash-forwarder.conf as following

{
  "network": {
    "servers": [ "soichi.goc:5000" ],
    "timeout": 15,
    "ssl ca": "/etc/grid-security/logstash/logstash-forwarder.crt"
  },
  "files": [
    {
      "paths": [
        "/var/log/messages",
        "/var/log/secure"
       ],
      "fields": { "type": "syslog" }
    }
   ]
}

When I start the forwarder, I see following log.

2014/10/22 15:04:56.617328 Connecting to fd2f:6feb:37:1::74:5000 (soichi.goc)
2014/10/22 15:04:56.617365 Failure connecting to fd2f:6feb:37:1::74: too many colons in address fd2f:6feb:37:1::74:5000

So, soichi.goc is resolved to the ipv6 address, and logstash-forwarder doesn't seem to like the ipv6 address. Is there any workaround to this?

**Comment by urso** [comment]
Out of the box I would assume go to support IPv6. On startup, the go runtime probes the OS for IPv6 support: https://github.com/golang/go/blob/5a3ff6c8955a5df81f6dd83e143a47bd51266b61/src/net/ipsock_posix.go#L35

can you try ping6 if you can reach your host via ipv6?

logstash-forwarder asks DNS for all known ips and uses one by random. LSF will try to connect to random server with randomly chosen IP (from all IPs known by DNS) until connection is established: https://github.com/elastic/logstash-forwarder/blob/master/publisher1.go#L168

I don't think the error message is critical, as LSF will eventually connect using the IPv4 address and start sending (if DNS returns IPv4 address to LSF).

lumberjack port to libbeat will shuffle all known addresses for a given host and will only fail (with retry) if no known address is reachable.

**Comment by driskell** [comment]
Logstash-forwarder does some IP parsing and in previous versions (included the one you are using) it did not correctly handle IPv6 addresses. When parsing config it splits the host and port, then it looks up the host to find the IP address, then re-attaches the port like: `IP + ":5000"`. This is then passed to Go. For IPv6 it needs to surround the address in square brackets for this to work and it didn't previously do this.

Upgrade to 0.4.0 and things will hopefully start working as the latest versions should have the patches in for IPv6 address handling.

**Comment by urso** [comment]
Thanks for the clarification.

In libbeat we are using:
http://golang.org/pkg/net/#SplitHostPort
http://golang.org/pkg/net/#JoinHostPort

**Comment by soichih** [comment]
Thank you for fixing this problem. I will test this out - hopefully next week!

**Comment by urso** [comment]
Should be fixed in upcoming filebeat release.
