### ISSUE TITLE
.logstash-forwarder needs a default location

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash-forwarder#505]
From https://github.com/elastic/logstash/issues/2209
-----------------------------------------------------------------

It would be useful to have .logstash-fowarder in a default location, such as /var/db/.loststash-forwarder

ref:https://groups.google.com/forum/#!searchin/logstash-users/.logstash-forwarder$20file$20location/logstash-users/DYGt8ngR98c/Ldy29Andg5gJ

A configuration option would set any other location.

**Comment by suyograo** [comment]
Dup of https://github.com/elastic/logstash-forwarder/issues/450

**Comment by ruflin** [comment]
This will be configurable in filebeat. See https://github.com/elastic/filebeat/pull/10

**Comment by jordansissel** [comment]
This is now available in filebeat per https://github.com/elastic/filebeat/pull/10

Logstash-forwarder is being replaced by filebeat, so I'm closing this.
