### ISSUE TITLE
Failed to create tempfile (.logstash-forwarder.new) for writing: open .logstash-forwarder.new: permission denied

### ISSUE THREAD

**Issue by pankajmalhotra** [elastic/logstash-forwarder#507]
I am seeing this in logstash-forwarder.log.
"Failed to create tempfile (.logstash-forwarder.new) for writing: open .logstash-forwarder.new: permission denied"
Please suggest what to do?
Logstash-forwarder: version:-- 0.4.0
Logstash: version:-- 1.5.3

**Comment by yuz11** [comment]
i guess ur linux user hasn't got the write authority to that folder

**Comment by pankajmalhotra** [comment]
Thanks. It was happening because of permissions only.
