### ISSUE TITLE
SSL cert is not working properly

### ISSUE THREAD

**Issue by autumnw** [elastic/logstash-forwarder#509]
A weird issue for me:
I generated the crt and key following the document. Configured correctly on logstash server and forwarder. Even I remove all the conent in crt file in forwarder side, forwarder still can connect to server successfully. Does this mean actually the ssl cert is useless? My OS is centos6.5/6.6, logstash version is 1.5.2.

**Comment by markwalkom** [comment]
What is the error?

**Comment by autumnw** [comment]
There is no any error message. I mean even with the wrong cert configured in forwarder, it still can connect to logstash server successfully. Is it normal or not?

**Comment by urso** [comment]
have you checked your config file to point to correct certificate file?

All certificate parsing and handling is provided by go standard library.

For LSF you can configure 2 certificates: the root CA and the client certificate for client authentication.

The client certificate must be requested by the server during handshake (client authentication must be enabled on server side). If not configured, the server will not ask for the certificate and client continues with handshake procedure.

Still the connection between server and client is validated by the client based on the root CA and connection (unless null cipher is used) will be encrypted.

What does useless mean for you? If you don't need client authentication, then no certificate and key file are required.

Followup: elastic/ruby-lumberjack#16
