### ISSUE TITLE
logstash-forwarder rejects CA certs with common critical extensions

### ISSUE THREAD

**Issue by jvoorhis** [elastic/logstash-forwarder#510]
logstash-forwarder will not parse a CA certificate containing common [name constraints](https://www.openssl.org/docs/apps/x509v3_config.html#Name-Constraints).

For example, given a cert with the following constraints:

```
        X509v3 extensions:
            X509v3 Name Constraints: critical
                Permitted:
                  email:.example.com
                  DNS:.example.com
```

The email constraint is treated as an unhandled critical extension and the cert cannot be used.

**Comment by urso** [comment]
what's the exact error message?

Certificate parsing and validation is provided by the go standard library (no openssl wrapper): https://golang.org/pkg/crypto/x509. The implementation states to support RFC 5280 (https://tools.ietf.org/html/rfc5280#section-4.2.1.10)

Can you provide a certificate for testing?

**Comment by jordansissel** [comment]
Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
