### ISSUE TITLE
logstash-forwarder not able to forward to two different logstash server sets

### ISSUE THREAD

**Issue by ehlerst** [elastic/logstash-forwarder#514]
You cant seem to do something like this:
logfile-a -> logstash-cluster1 -> datawarehouse
logfile-a -> logstash-cluster2 -> ELK short term storage

The reason to do this may be due to logstash hanging if Elasticsearch is un-responsive.

**Comment by ehlerst** [comment]
You also cannot run 2 pids due to the hidden state file not being configurable. 

https://github.com/elastic/logstash-forwarder/blob/master/registrar.go#L31
/var/lib/logstash-forwarder/.logstash-forwarder

**Comment by morya** [comment]
logstash-forwarder read&write .logstash-forwarder from it's $CWD  
if you start logstash-forwader from two different dir with two different set of config file, I think that would be ok for them.

There is an enhancement patch to set work-dir from command-line, but I don't know whether the author of logstash-forwarder will accept it or not...

**Comment by jordansissel** [comment]
> You also cannot run 2 pids

This is not true. The state file uses current-directory, so change directory to wherever you want state to be kept.

SOrry for the delays in responding on this - 
Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
