### ISSUE TITLE
logstash-forwarder RPMs are not signed

### ISSUE THREAD

**Issue by cinglese** [elastic/logstash-forwarder#515]
The latest logstash-forwarder RPM (version 0.4.0) is not signed. This creates issues when installing it using basic Yum installation routines as well as Puppet package resource type.

Output of: rpm -qpi logstash-forwarder-0.4.0-1.x86_64.rpm
Name        : logstash-forwarder           Relocations: /
Version     : 0.4.0                             Vendor: jenkins@metal3
Release     : 1                             Build Date: Wed 04 Mar 2015 08:32:19 PM GMT
Install Date: (not installed)               Build Host: metal3.elasticsearch.org
Group       : default                       Source RPM: logstash-forwarder-0.4.0-1.src.rpm
Size        : 6023492                          License: unknown
Signature   : (none)
Packager    : <jenkins@metal3>
URL         : https://github.com/elasticsearch/logstash-forwarder
Summary     : a log shipping tool
Description :
a log shipping tool

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
