### ISSUE TITLE
logstash-forwarder does not recognize selfsigned certificate

### ISSUE THREAD

**Issue by blazerguns** [elastic/logstash-forwarder#516]
Hi All,

I have so many older issues related to this but I followed the guide carefully and think this might be a genuine bug.

I followed these instructions for certificate and used http://deezx.github.io/blog/2015/05/21/logstash-forwarder-certificate-issues/
openssl req -x509 -subj ‘/CN=n036hd0l0123.s4.chp/’ -batch -nodes -days 365 -newkey rsa:2048 \\
-keyout logstash-forwarder.key -out logstash-forwarder.crt

I used n036hd0l0123.s4.chp as this is logstash server. I didnt care to use more logstash servers so just using only one.

After creating the certificates, I copied them to logstash server (n036hd0l0123.s4.chp)
ssl_certificate => "/etc/pki/tls/certs/n036hd0l0123.s4.chp.crt"
ssl_key => "/etc/pki/tls/private/n036hd0l0123.s4.chp.key"

I copied the n036hd0l0123.s4.chp.crt to the logstash-forwarder machine and put in the same location as above.

When I start the forwarder

bin/logstash-forwarder -config etc/conductor_log.json
2015/08/22 10:05:09.842999      --- options -------
2015/08/22 10:05:09.843309      config-arg:          etc/conductor_log.json
2015/08/22 10:05:09.843328      idle-timeout:        5s
2015/08/22 10:05:09.843337      spool-size:          1024
2015/08/22 10:05:09.843345      harvester-buff-size: 16384
2015/08/22 10:05:09.843353      --- flags ---------
2015/08/22 10:05:09.843361      tail (on-rotation):  false
2015/08/22 10:05:09.843368      log-to-syslog:          false
2015/08/22 10:05:09.843376      quiet:             false
2015/08/22 10:05:09.843649 {
  "network": {
    "servers": [ "n036hd0l0123.s4.chp:5043" ],
    "ssl certificate": "/etc/pki/tls/certs/n036hd0l0123.s4.chp.crt",
    "ssl ca": "/opt/apps/myOwnCA/cacert.pem",
    "ssl strict verify": false,
    "timeout": 15
  },
  "files": [
    {
       "paths": [
         "/workout/conductor/conductor.log"
       ],
       "fields": { "type": "syslog" }
    }
   ]
}

2015/08/22 10:05:09.844685 Waiting for 1 prospectors to initialise
2015/08/22 10:05:09.845810 Launching harvester on new file: /workout/conductor/conductor.log
2015/08/22 10:05:09.846025 harvest: "/workout/conductor/conductor.log" (offset snapshot:0)
2015/08/22 10:05:09.846201 All prospectors initialised with 0 states to persist
2015/08/22 10:05:09.846689 Setting trusted CA from file: /opt/apps/myOwnCA/cacert.pem
2015/08/22 10:05:09.872255 Connecting to [10.1.2.16]:5043 (n036hd0l0123.s4.chp)
2015/08/22 10:05:09.991787 Failed to tls handshake with 10.1.2.16 x509: certificate signed by unknown authority

Ant this error keeps repeating
This seem like genuine bug and I tried various options like
"ssl ca": "/opt/apps/myOwnCA/cacert.pem",
 "ssl strict verify": false,

which should not be needed. Please help.
I am using Logstash Forwarder 0.4.0 and logstash actually works fine with certificates on the logstash server.

**Comment by tbragin** [comment]
It appears that you are using your own CA, rather than using self-signed certs. I was able to get the most basic self-signed cert example to work based on the README. 

My setup:
* Logstash 1.5.3 and LSF (Logstash Forwarder) 0.4.0 both running on localhost
* openssl command to create the certs:
```
openssl req -x509  -batch -nodes -newkey rsa:2048 -keyout lumberjack.key -out lumberjack.crt -subj /CN=localhost
```
* Placed both certs into /Users/tanya/lsf/

Here are my configs:

Logstash 1.5.3 (lumberjack input section):
```
input {
  lumberjack {
    # The port to listen on
    port => 5043

    # The paths to your ssl cert and key
    ssl_certificate => "/Users/tanya/lsf/lumberjack.crt"
    ssl_key => "/Users/tanya/lsf/lumberjack.key"

    # Set this to whatever you want.
    type => "somelogs"
  }
}
...
```

LSF 0.4.0 ("network" section):
```
{
  "network": {
    "servers": [ "localhost:5043" ],
    "ssl ca": "/Users/tanya/lsf/lumberjack.crt",
    "timeout": 15
  },
```

Here is the stdout output on the LSF side:
```
$ ./logstash-forwarder_darwin_amd64 -config lsf.conf
2015/08/31 12:51:39.523196 	--- options -------
2015/08/31 12:51:39.523297 	config-arg:          lsf.conf
2015/08/31 12:51:39.523311 	idle-timeout:        5s
2015/08/31 12:51:39.523316 	spool-size:          1024
2015/08/31 12:51:39.523320 	harvester-buff-size: 16384
2015/08/31 12:51:39.523322 	--- flags ---------
2015/08/31 12:51:39.523326 	tail (on-rotation):  false
2015/08/31 12:51:39.523329 	log-to-syslog:          false
2015/08/31 12:51:39.523332 	quiet:             false
2015/08/31 12:51:39.523385 {
  "network": {
    "servers": [ "localhost:5043" ],
    #"ssl certificate": "/Users/tanya/lsf/lumberjack.crt",
    "ssl ca": "/Users/tanya/lsf/lumberjack.crt",
    "timeout": 15
  },

  "files": [
    { "paths": [ "/Users/tanya/logs"], "fields": { "type": "syslog" }}, 
    { "paths": [ "/var/log/accountpolicy.log"], "fields": { "type": "syslog" }}, 
    { "paths": [ "-" ], "fields": { "type": "stdin" }}
  ]

  #"dead time": "100000000000000000m"

}

2015/08/31 12:51:39.523980 Loading registrar data from /Users/tanya/lsf/.logstash-forwarder
2015/08/31 12:51:39.524027 Waiting for 3 prospectors to initialise
2015/08/31 12:51:39.524107 Skipping file (older than dead time of 24h0m0s): /Users/tanya/logs
2015/08/31 12:51:39.524152 Registrar will re-save state for /var/log/accountpolicy.log
2015/08/31 12:51:39.524246 harvest: "-" (offset snapshot:262397)
2015/08/31 12:51:39.524335 Resuming harvester on a previously harvested file: /var/log/accountpolicy.log
2015/08/31 12:51:39.524402 harvest: "/var/log/accountpolicy.log" position:950 (offset snapshot:950)
2015/08/31 12:51:39.524701 All prospectors initialised with 1 states to persist
2015/08/31 12:51:39.524755 Setting trusted CA from file: /Users/tanya/lsf/lumberjack.crt
2015/08/31 12:51:39.525174 Connecting to [::1]:5043 (localhost) 
2015/08/31 12:51:39.607500 Connected to ::1
2015/08/31 12:51:40.351159 Registrar: processing 10 events
```

**Comment by tbragin** [comment]
I'll go ahead and close this due to lack of response. Please let us know if you think there is still a defect.
