### ISSUE TITLE
Listen to traffic and forward it to logstash?

### ISSUE THREAD

**Issue by cedw93** [elastic/logstash-forwarder#517]
Is there a way to set up `logstash-forwarder` so it listens to traffic on localhost and send the data to the `logstash` instance(s).

I have `logstash-forwarder` set up and working but I want to try and avoid having several instances of `logstash-forwarder` on all my servers. 

Ideally I want to host `logstash-forwarder` on one server and it will listen to traffic coming into that server and forward it the the `logstash` host. 

Is this actually possible?

**Comment by gjvoit** [comment]
I believe the point of LS Forwarder is to avoid having to install Logstash on all of your servers. From my understanding, you need to install LS Forwarder on any server you wish to collect logs from, then point each Forwarder to your primary Logstash server / balancer.

**Comment by tbragin** [comment]
Please join us on https://discuss.elastic.co for support and general questions. Github is reserved for bug reports and enhancements only :)
