### ISSUE TITLE
File deletion kills logstash-forwarder

### ISSUE THREAD

**Issue by tsprlng** [elastic/logstash-forwarder#523]
The harvester, upon encountering an EOF, immediately tries to stat the file. Presumably this returns nil if it's gone, causing a panic on the call to Size(). 

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x40 pc=0x403a45]

    goroutine 9 [running]:
    main.(*Harvester).Harvest(0xc208050e40, 0xc208050ba0)
            /home/jenkins/workspace/logstash-forwarder/harvester.go:60 +0x635
    created by main.(*Prospector).scan
            /home/jenkins/workspace/logstash-forwarder/prospector.go:164 +0x1119
    […]

https://github.com/elastic/logstash-forwarder/blob/v0.4.0/harvester.go#L60

I'd guess the preferred behaviour would be to politely finish the harvest, allowing the prospector to launch another if a new file is created matching the same path?

On the other hand maybe a warning is helpful, although this might be best limited to cases where deletion happens before the file is completely read (but of course this is difficult to determine)…

No time to attempt a patch now, sadly, but I could have a go later if you like? My understanding is extremely partial though, so it might take some time.

That said, it could be as simple as `if (info==nil) { break; }`, depending how the prospector works.

Meanwhile, thanks for your work on this. I really like the way it deals with log rotation – hence the surprise here as cleanly handling deletion/replacement seems like a natural extension of the same behaviour (if we "sanely" assume a new file has no content in common with the deleted one).

**Comment by ruflin** [comment]
I think the easiest solution here is to check on line 59 for the error provided by Stat as the second return value.

**Comment by ruflin** [comment]
This was fixed in https://github.com/elastic/filebeat/pull/70 As filebeat is going to be the next release of logstash-forwarder, I will close this issue.
