### ISSUE TITLE
Allow logstash-forwarder to read from pipes

### ISSUE THREAD

**Issue by dooblem** [elastic/logstash-forwarder#525]
Hello,

Is it possible to tweak logstash-forwarder (harvester.go) to allow to read from pipes (fifo files) ?

Here is the error I get:
```
2015/09/07 14:57:03.429111 Connected to 62.193.57.230
panic: Harvester: not a regular file:"prw-r--r--"%!(EXTRA string=access-error-pipe)
```

To reproduce:
 * mkfifo /tmp/mypipe
 * point your LF config to path /tmp/mypipe
 * start LF : everything ok
 * echo test >/tmp/mypipe  --> crassh

Thanks in advance,
Marc

See also: https://groups.google.com/forum/#!topic/logstash-users/lIMXnuGxE9M

**Comment by Dids** [comment]
I'm also seeing this when trying to use logstash-forwarder inside a Docker container.

**Comment by ruflin** [comment]
@Dids Is this just for some specific files inside the docker container (shared volumes) or in general? Can you check if you have the same issues with Filebeat (https://github.com/elastic/filebeat) which is the next version of logstash-forwarder.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?

**Comment by dooblem** [comment]
Hello,
This is still an issue in Filebeat.
I got the following error

`Aug 11 12:31:23 XXXXXXXXXXXXXXX /usr/bin/filebeat[20879]: log.go:103: Stop Harvesting. Unexpected file opening error: Given file is not a regular file`

I'm opening a ticket in Filebeat issues.
