### ISSUE TITLE
Allow a setting for log backlog retention

### ISSUE THREAD

**Issue by SamSaffron** [elastic/logstash-forwarder#528]
I would like to set a "setting" that would allow me to tell Logstash Forwarder only to retain 5 minutes of logs, have it ignore everything prior to that.

This is particularly useful for cases of long term outages for logstash.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
