### ISSUE TITLE
error sending logs - Failed to tls handshake with  read tcp : i/o timeout

### ISSUE THREAD

**Issue by AlekMarkus** [elastic/logstash-forwarder#529]
hello , my logstash-forwarder was working without errors, suddnley i get this message : 

Failed to tls handshake with  read tcp : i/o timeout

what could happen ? 

Version logstash-forwarder  : 0.4.0

**Comment by kvashishta** [comment]
I am experiencing exactly the same issue:
2015/09/26 14:36:32.432186 Connecting to [192.168.1.235]:5001 (192.168.1.235)
2015/09/26 14:36:47.433350 Failed to tls handshake with 192.168.1.235 read tcp 192.168.1.235:5001: i/o timeout

logstash-forwarder-0.4.0-1.x86_64

**Comment by kvashishta** [comment]
This issue has been resolved thanks to google. I googled and found that upgrading elasticsearch to the latest version alleviates the issue. I also increased the logstash-forwarder timeout to 5 minutes(from 15 seconds). I now have three logstash forwarders supplying logs to the logstash server. I am however keeping my fingers crossed.

**Comment by AlekMarkus** [comment]
well i didnt think to update to a newer version. thanks for the update :) i will check it soon

Best Regards,
Alek

**Comment by kvashishta** [comment]
Alek,

This link helped me a lot. I am wondering about open source effectiveness.
I guess it is certainly better than buying a commercial for sale product. I
have had a rough ride with ELK, finally finding some stability, need to put
MS exchange logs into ELK, let's see how that goes. Regards,

Kartik Vashishta

**Comment by kvashishta** [comment]
Sorry forgot to paste the link:
https://github.com/elastic/logstash-forwarder/issues/360

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
