### ISSUE TITLE
Allow paths with wildcard directories

### ISSUE THREAD

**Issue by roji** [elastic/logstash-forwarder#532]
In some cases log files are grouped into subdirectories, and it seems impossible to specify the following for logstash-forwarder: `/syslog/log/**/*`.

This capability is supported by logstash, see [this conversation](https://groups.google.com/forum/#!msg/logstash-users/BrxgwKktvwg/Ob3FosqsskAJ).

(BTW: Is logstash-forwarder still being maintained? It seems there hasn't been real activity here for months...)

**Comment by ruflin** [comment]
@roji All new features for logstash-forwarder go into filebeat. Filebeat will be the future replacement of logstash-forwarder. So it is best to open this issue directly in the Filebeat repo: https://github.com/elastic/filebeat

**Comment by roji** [comment]
Thanks, opened https://github.com/elastic/libbeat/issues/117
