### ISSUE TITLE
Support sending grok config for logs

### ISSUE THREAD

**Issue by nuth** [elastic/logstash-forwarder#533]
I recently understood (after reading README.md) that logstash-forwarder is design specifically to be lightweight and only send logs somewhere else to be processed. I'd still like to propose being able to send the grok config or something similar with the logs, so that I can configure my formats at the source, rather than maintaining a centralized formatting config in logstash, and just plug in any application with a logstash-forwarder pointing to logstash which will instantly format my logs correctly. (I think sort of like a gelf appender for log4j?)

I'm planning to dive into the source of logstash and logstash-forwarder to see how I can do this, but I wouldn't mind if someone with more experience would like to look into this.

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
