### ISSUE TITLE
Mutual Authentication SSL over Lumberjack protocol

### ISSUE THREAD

**Issue by ersushantsood** [elastic/logstash-forwarder#534]
Hi I want to know if Lumberjack supports Mutual Authentication when integrated with Logstash collector . As per the documentation on git it support One way authentication . Please confirm if Mutual Authentication is supported or if not then can i use any tool like proxy server to achieve the same .

**Comment by jordansissel** [comment]
lsf at present will authenticate the server it connects to, but at this time, I think logstash (lumberjack input) will not require authentication of lsf connections (lsf only sends to trusted targets, logstash/lumberjack currently accept from all senders). The initial threat model was to prevent lsf from leaking data to an untrusted server, and that is what is accomplished by the current behavior.

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
