### ISSUE TITLE
logstash-forwarder missing log events for frequently rolling log files

### ISSUE THREAD

**Issue by kkdoitall** [elastic/logstash-forwarder#536]
Logstash forwarder missing log events for frequently rolling log files.

My java application has lot of batch jobs and real time data feeds. Basically its a enterprise integration application. 

My application creates log files for each batch jobs and using log4j2 as a logging framework. The log4j2 is customized to create log files dynamically based on the feed name that I provide through bash script invocation and uses log4j2 routing adapter for log file creation. 

Here is the log4j2 configuration.

```
<?xml version="1.0" encoding="UTF-8"?> 
<Configuration xmlns="http://logging.apache.org/log4j/2.0/config" shutdownHook="disable"> 
<Appenders>
  <Routing name="RoutingAppender" ignoreExceptions="true">
 <Routes pattern="${ctx:logFileName}">
       <Route>
              <RollingFile name="${ctx:logFileName}"
                    fileName="${log-path}/${ctx:logFileName}.log"
                    filePattern="${log-path}/${ctx:logFileName}_%i.log.gz">
                    <BurstFilter level="DEBUG" rate="16" maxBurst="100"/>
                    <PatternLayout pattern="%d{MM-dd-yyyy HH:mm:ss,SSS}|%level|[%thread]|    [${env:USERNAME}]|[%C]|- %msg%n"/>
                    <SizeBasedTriggeringPolicy size="50MB" />
                <DefaultRolloverStrategy max="20"/>
            </RollingFile>
        </Route>
    </Routes>
</Routing> </Appenders> <Loggers>
<Root level="INFO">
    <AppenderRef ref="RoutingAppender"/>
</Root> 
```

</Loggers>
     </Configuration>

This configuration is working perfectly and creates log files based on the loggerFile name provied

There are few batch jobs that runs longer and process millions of data. The business requirement is to capture data thats flow through my application and log it for audit purpose. 

However, for most of the jobs, I do not see any log events lost for most of the feeds. But fror some feeds, where the size based rollup is happening every 3 min. because of the amount of data processed,There are log events lost. 

I may not be able to increate the sizeBasedTriggeringPoicy because at any given time there may be more than 1500 feeds processing, and increasing the sizeBasedTriggeringPolicy may lead to disk space issue.

Here is my logstash forwarder configuration

```
{
  "network": {
"servers": [ "Server1:5004","Server2:5004","Server3:5004"],
"ssl certificate": "./certs/logstash.crt",
"ssl key": "./certs/logstash.key",
"ssl ca": "./certs/logstash.crt",
"timeout": 15
  },

 "files": [
{
  "paths": [
    "/opt/logs/*.log"],
  "fields": { "type": "application" },
  "dead time": "10m"
}
  ]
}
```

Here are the args set for logstash forwarder

```
./logstash-forwarder -quiet=true -config=./logstash-forwarder.conf
```

Kibana, shows evidence, the logs received every 2 min. But my application is processing data continuously and could see the events logged in my log file. From my analysis, I find the offset of previously rolled file is taken and been used for the current log file 
enter image description here

What configurations should be added to the logstash forwarder in order to capture all the log events.

I have tried -tail=true, which did not work.

I am using 0.4.0 version of logstash-forwarder and my Operating system is RHEL 5.X

**Comment by ruflin** [comment]
Based on your description I assume the following is happening: Logstash-forwarder is reading your current log file. Then the log file is rotated and zipped, but before it was zipped still some messages were added that logstash-forwarder was not able to read anymore. If you don't use the tail flag, logstash-forwarder should start reading from scratch for every new file. logstash-forwarder can detect if it is the same file that was renamed or a different file with the same name. I assume the new log files is a new file generated and not the same file but the content dumped?

As logstash-forwarder is able to detect a renamed file, I recommend to keep the "old" log file around before you zip it, for example as logfile.old.log so logstash-forwarder can finish reading.

**Comment by karthikeyan-kesavaraj** [comment]
Hi Ruflin, 

As you suggested, I have changed the log rolling properties. 
Max File size : 250 MB
File Format : ${ctx:logFileName}_%i.log

But I see still events are missing when shipped.

**Comment by ruflin** [comment]
@karthikeyan-kesavaraj Can you check if the log data missing are the last lines of the rotated file?

**Comment by karthikeyan-kesavaraj** [comment]
Thats correct. Its the last part of the log file

**Comment by ruflin** [comment]
@karthikeyan-kesavaraj we plan to roll out the filebeat beta4 this week. As this is the next version of logstash-forwarder with quite a few improvements, would you have a chance to test if the same problem persists with filebeat as soon as the beat is out? https://github.com/elastic/filebeat

**Comment by karthikeyan-kesavaraj** [comment]
@ruflin would definitely like to check filebeat !!!

**Comment by ruflin** [comment]
@karthikeyan-kesavaraj Filebeat beta 4 is out: https://www.elastic.co/blog/beats-beta4-filebeat-lightweight-log-forwarding
The migration guide can be found here: https://www.elastic.co/guide/en/beats/filebeat/current/_logtash_forwarder_to_filebeat_migration.html

**Comment by ruflin** [comment]
Closing as since then even filebeat 5.0 was shipped which should definitively fix this issue.
