### ISSUE TITLE
Q: can this program send to papertrailapp.com?

### ISSUE THREAD

**Issue by stig** [elastic/logstash-forwarder#537]
Is it possible to use this program to send logs to papertrailapp.com? We'd rather not have to run our own ES + Kibana, but logstash-forwarder is already installed everywhere. I was thinking it would ease our migration if we could reconfigure it rather than install their remote_syslog2 program and configure that instead.

**Comment by jordansissel** [comment]
There's no support that I know of for papertrail to receive stuff from logstash-forwader.

If you just want to avoid running ES+Kibana, Elastic offers a hosted service called Found: https://www.elastic.co/found
