### ISSUE TITLE
logstash-forwarder tcp input

### ISSUE THREAD

**Issue by philipmeadows** [elastic/logstash-forwarder#543]
Are there any plans to support tcp input of logstash messages which would then be forwarded onto a remote logstash instance.

What I would like to do would be to use something like https://github.com/logstash/logstash-logback-encoder#tcp-appenders to have my applications sending logs directly to a port on localhost and then use logstash forwarder to forward that on to my remote logstash with logstash forwarder taking care of buffering, SSL comms and failover.

**Comment by ruflin** [comment]
@philipmeadows As Filebeat will be the next version of logstash-forwarder I suggest to open this issue directly in the filebeat repository: https://github.com/elastic/filebeat

**Comment by philipmeadows** [comment]
Great, thanks. I will open it in that repo.

**Comment by ruflin** [comment]
@philipmeadows Cool. Best is to link it then here and close this issue.

**Comment by philipmeadows** [comment]
Opened here https://github.com/elastic/filebeat/issues/213 Will close this issue.
