### ISSUE TITLE
rotate logstash forwarder's log

### ISSUE THREAD

**Issue by naviehuynh** [elastic/logstash-forwarder#546]
By default Logstash Forwarder logs into `/var/log/logstash-forwarder` but the file is not rotated and takes up disk space over time. How should I deal with it?

**Comment by ruflin** [comment]
As filebeat is the next version of logstash-forwarder and is now in version 1.0.0 available, we recommend to use filebeat. Filebeat handles log rotation. https://github.com/elastic/filebeat

**Comment by naviehuynh** [comment]
@ruflin so logstash forwarder doesn't handle log rotation? We will put Filebeat in our near future release but for now, what is the best workaround? Can I disable that log?

**Comment by ruflin** [comment]
@naviehuynh There could be two options: Enabled the quite flag so only errors are logged. Or try using the log-to-syslog flag so events are logged to syslog.

**Comment by naviehuynh** [comment]
Thank you.
