### ISSUE TITLE
Logstash-forwarder cannot get data from the beginning.

### ISSUE THREAD

**Issue by MarcoWangL** [elastic/logstash-forwarder#547]
From the answer "Based on the original report (lsf not shipping files) - the described behavior seems like the default behavior (start following a file stream at the end for unknown files). The fix is to use -from-beginning flag to tell it to start at the beginning for unknown files." 
I have already know how to fix this issue, but I don't know where can set the option "from-beginning" in the logstash-forwarder? Can anyone one help me? many thanks.

**Comment by MarcoWangL** [comment]
@jordansissel  can you give me some detailed advice? thanks

**Comment by ruflin** [comment]
@MarcoWangL As the new version of logstash forwarder is filebeat, I recommend to switch to filebeat: https://www.elastic.co/products/beats/filebeat Let me know in case you have some issues with Filebeat.

In case the problem persist, please open a new issue here: https://github.com/elastic/beats
