### ISSUE TITLE
way to override 24hr inactivity in a file harvester?

### ISSUE THREAD

**Issue by pmoust** [elastic/logstash-forwarder#549]
I know that logstash-forwarder is no longer actively developed,
is there a way to override 24hr inactivity in a file harvester?

**Comment by ruflin** [comment]
@pmoust I assume you are referring to dead time? You can set it in the configuration file: https://github.com/elastic/logstash-forwarder/blob/5fdbfdca0db6d2f25d27152d2edd3afa379bb36a/config_test.go#L97

**Comment by pmoust** [comment]
Thanks @ruflin
