### ISSUE TITLE
tailing log file not registering events (logstash forwarder with -tail=true)

### ISSUE THREAD

**Issue by abinay** [elastic/logstash-forwarder#552]
I want my logstash forwarder to ship only the data which has been appended into my file . But by default logstash forwarder reads the specified file from the beginning and then sends it . Though many discussions say that one can simpy run logstash forwarder by adding -tail=true flag but it keeps harvesting and does not process events . i am stuck with this . What can be done ??? I am not running logstash forwarder using as a service . I am simply running the it using the command /opt/logstash-forwarder/bin/logstash-forwarder -tail=true -config /etc/logstash-forwarder.conf

**Comment by ruflin** [comment]
logstash-forwarder was replaced by filebeat: https://www.elastic.co/downloads/beats/filebeat. What you are looking for seems to be tail_files: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_tail_files In case of an issue with filebeat, feel free to open a discussion topic under https://discuss.elastic.co/c/beats/filebeat
