### ISSUE TITLE
Filebeat - transport.go:125: SSL client failed to connect with: read tcp connection reset by peer 

### ISSUE THREAD

**Issue by charannaik** [elastic/logstash-forwarder#555]
hi, i configured filebeat as instructed here https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-centos-7 (execpt that i did this on Red had server) however i have issues shipping logs and i get the following error on filebeat restart

transport.go:125: SSL client failed to connect with: read tcp connection reset by peer

Can you someone suggest how to trouble shoot this?

nc -vz 'servername' 5044 works is successful
telnet to 5044 works fine
firewall is off on both machines.
selinux is disabled.
copied the certificate on the client machine
The configuration is same as described in the article

**Comment by ruflin** [comment]
Please check our FAQ entry for this issue: https://www.elastic.co/guide/en/beats/filebeat/current/ssl-client-fails.html For questions please use the beats forum: https://discuss.elastic.co/c/beats/filebeat Closing this issue.
