### ISSUE TITLE
Logstash-forwarder exclude gzip files

### ISSUE THREAD

**Issue by hulk22** [elastic/logstash-forwarder#561]
Hi @jordansissel . Can you please help me here. I want to exclude gzip files from a folder. this is the config I used.

 "files": [
    {
      "paths": [ "/mnt/game/logs/chat-log-*.log.[0-9]{4}-[0-9]{2}-[0-9]{2}?(.)[0-9]{0,2}" ],
      "fields": { "type": "chat-log" }
    },
    {
      "paths": [ "/mnt/game/logs/game-server.log.[0-9]{4}-[0-9]{2}-[0-9]{2}?(.)[0-9]{0,2}" ],
      "fields": { "type": "gameserver-log" }
    },
    {
      "paths": [ "/mnt/game/logs/delta_consumer.log.[0-9]{4}-[0-9]{2}-[0-9]{2}?(.)[0-9]{0,2}" ],
      "fields": { "type": "delta-log" }
    }
 ]
}

and this is giving me this. 2017/03/27 15:16:39.110383 All prospectors initialised with 0 states to persist
2017/03/27 15:16:39.111093 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
2017/03/27 15:16:39.112038 Connecting to [172.31.8.12]:5000 (172.31.8.12)
2017/03/27 15:16:39.253889 Connected to 172.31.8.12

**Can you please help me this is an urgent requirement on prod**. I cannot change to filebeat for now as this will require whole restructuring.
No events are processed. Is there anything that i can do to exclude *.gz in logstash-forwarder

**Comment by ph** [comment]
@hulk22 I don't know the file name format of your logs but you should be able to use wildcards to only take plain text files. Also, I don't think we support regular expression in the path definition and we don't have any exclude option.

**Comment by hulk22** [comment]
@ph can i not use above pattern. to exclude gz files. I have tried another glob pattern because as per logstash-forwarder conf example file it is written globs are fine too. below is the example.

  "files": [
    {
      "paths": [ "/mnt/game/logs/chat-log-*.!(*.gz)" ],
      "fields": { "type": "chat-log" }
    },
    {
      "paths": [ "/mnt/game/logs/game-server.log!(*.gz)" ],
      "fields": { "type": "gameserver-log" }
    },
    {
      "paths": [ "/mnt/game/logs/delta_consumer.log.!(*.gz)" ],
      "fields": { "type": "delta-log" }
    }
 ]

Files that i have in my folder. 

chat-log-1490360975876.log.2017-03-27-1490601601.gz
game-server.log.2017-03-27-1490616001.gz
game-server.log.2017-03-27.1-1490616001.gz
chat-log-1490360975876.log.2017-03-27-1490616001.gz
game-server.log.2017-03-27
chat-log-1490360975876.log.2017-03-27
chat-log-1490627671385.log.2017-03-27.

I want to exclude all gzip using any pattern in logstash-forwarder conf file

**Comment by ph** [comment]
@hulk The pattern matching that LSF is using is pretty limited, and is provided by the golang std library. We just send the configuration to that FilePath's Glob method at https://github.com/elastic/logstash-forwarder/blob/master/prospector.go#L83

From the std library https://golang.org/pkg/path/filepath/#Glob, it uses the same pattern as the match method described there: https://golang.org/pkg/path/filepath/#Match

I see two solution for you right now:

- Change the format of the logging to have a pattern we can glob on with wildcards`*.log` and the compressed format would be `*.log.gz`
- Have a script that periodically rename the file?

**Comment by hulk22** [comment]
We can do this but there must be some way around any glob pattern that should meet my requirement. any negation or all.

**Comment by hulk22** [comment]
@ph someone at below url:--

https://github.com/elastic/logstash-forwarder/issues/89

mentioned this blog:-- https://blog.vladionescu.com/excluding-from-a-path-glob/. I am not able to open this link

**Comment by ruflin** [comment]
@hulk22 I strongly recommend you to switch over to filebeat as logstash-forward is no longer maintained. In filebeat you can use `exclude_files` for this: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#exclude-files

**Comment by hulk22** [comment]
@ruflin I have resolved this issue for now by renaming files with *.log and yes I will soon switch to filebeat in my infrastructure. And Already testing it :)
