### ISSUE TITLE
Run on the ARM (RaspberryPi)

### ISSUE THREAD

**Issue by dshowing** [elastic/logstash-forwarder#563]
Is the logstash-forward used on ARM, like RaspberryPi ?
I run UbuntuMATE on the RaspberryPi 3B , and there is not suitable package with it.
Thanks !

**Comment by ruflin** [comment]
@dshowing logstash-forwarder is EOL and is replaced by filebeat: https://www.elastic.co/products/beats/filebeat Having said that filebeat can be built for ARM but is not officially supported at the moment. But there are quite a few in the community doing some work around it.
