### ISSUE TITLE
lumberjack does to keep last read through stop / start

### ISSUE THREAD

**Issue by pkubat** [elastic/logstash-forwarder#61]
config file:
{
  "network": {
    "servers": [ "log01.dev:8514" ],
    "ssl ca": "/etc/lumberjack/lumberjackCA.pem"
  },
  "files": [
    {
      "paths": [ "/var/log/messages" ],
      "fields": { "type": "syslog" }
    }, {
      "paths": [ "/tmp/foo" ],
      "fields": { "type": "foo" }
    }
  ]
}

commandline:
/opt/lumberjack/bin/lumberjack.sh --config test.conf

#steps

$ date  >> /tmp/foo
$ cat .lumberjack  
{"/tmp/foo":{"source":"/tmp/foo","offset":406,"inode":494459,"device":2049}}
[stop lumberjack]
$ date  >> /tmp/foo
$ date  >> /tmp/foo
$ cat .lumberjack  
{"/tmp/foo":{"source":"/tmp/foo","offset":406,"inode":494459,"device":2049}}
[start lumberjack]
$ cat .lumberjack 
{"/tmp/foo":{"source":"/tmp/foo","offset":406,"inode":494459,"device":2049}}
$ date  >> /tmp/foo
$ cat .lumberjack  
{"/tmp/foo":{"source":"/tmp/foo","offset":493,"inode":494459,"device":2049}}

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by jordansissel** [comment]
I think this was resolved with the last release.
