### ISSUE TITLE
Can't add multiple tags to inputs

### ISSUE THREAD

**Issue by avleen** [elastic/logstash-forwarder#65]
In the config for the Go version of Lumberjack, this works:
      "fields": { "type": "gearman_manager_log", "tags": "gearman_manager" }
But this fails:
      "fields": { "type": "gearman_manager_log", "tags": [ "gearman_manager", "foo", "bar" ] }

With the following error:
2013/08/19 06:11:17 Failed unmarshalling json: json: cannot unmarshal array into Go value of type string

Tags are supposed to be an array!

**Comment by jordansissel** [comment]
This is still a known limitation. No change planned, but we can probably fix this for filebeat.

**Comment by ruflin** [comment]
Closing this issue in favor of https://github.com/elastic/filebeat/issues/69 as filebeat as the next release of logstash-forwarder.
