### ISSUE TITLE
Having several instances of logstash, how to make lumberjacks reconnect?

### ISSUE THREAD

**Issue by Hoodoo** [elastic/logstash-forwarder#72]
Hello and thank you for a perfect log shipper and aggregator!

I'm evaluating logstash as an aggregator of logs from two dozens of servers. To manage which users can search which logs, I ship logs from different sources to different indices and restrict access to them with nginx.

To accomplish that, I need several simple grep filters, which (as I've noticed) are prone to break the application. In order not to lose my events, I run two instances of logstash and lumberjacks are configured to connect to both of them.

If a logstash crashes, I can launch it again pretty quickly with puppet (ensure => running), but by that time all of lumberjacks would be shipping logs to another instance.

Is there a good way to make lumberjack reconnect so that they are shipping to randomly picked logstashes somehow? I wouldn't like to use cron here because I think some events would duplicate this way because of that window setting.

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by jordansissel** [comment]
Closing I'm not sure this is still a problem. Please open a new ticket if so.
