### ISSUE TITLE
Log4j rotated logs locked by lumberjack.

### ISSUE THREAD

**Issue by lmorfitt** [elastic/logstash-forwarder#77]
Hello,

We have a java app which uses log4j to output to a log file. The log file is rotated based on size. (200mb).

Lumberjack appears to be locking the file after it has been deleted by Log4J. This means the file is never deleted and eventually we run out of disk space.

[root@server folder]# lsof |grep -i del|grep -i lum
lumberjac 18491              root    9r      REG              253,5 403973659      66690 /usr/local/APP/logs/dailyShell.log.4 (deleted)
lumberjac 18491              root   14r      REG              253,5 209760944      65034 /usr/local/APP/logs/dailyShell.log.4 (deleted)
lumberjac 18491              root   15r      REG              253,5 209715244      65036 /usr/local/APP/logs/dailyShell.log.4 (deleted)
lumberjac 18491              root   16r      REG              253,5 209771415      65037 /usr/local/APP/logs/dailyShell.log.4 (deleted)
lumberjac 18491              root   17r      REG              253,5 209799901      65041 /usr/local/APP/logs/dailyShell.log.4 (deleted)
lumberjac 18491              root   18r      REG              253,5 209728019      65060 /usr/local/APP/logs/dailyShell.log.4 (deleted)
lumberjac 18491              root   19r      REG              253,5 209720933      65061 /usr/local/APP/logs/dailyShell.log.4 (deleted)
[root@server folder]# 

Restarting lumberjack removes the file locks and frees the disk space up. however the app creates 1GB's of log per hour.

The RPM we built is lumberjack-0.1.2-1.x86_64.rpm

Red Hat Enterprise Linux Server release 6.3 (Santiago)

Linux server.common 2.6.32-279.22.1.el6.x86_64 #1 SMP Sun Jan 13 09:21:40 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

Additionally we see lumberjack start harvesting on the new log file as it is rotated.

2013/09/05 23:28:33.594797 Saving registrar state.
2013/09/05 23:28:36.231139 Launching harvester on rotated file: /usr/local/APP/logs/dailyShell.log
2013/09/05 23:28:36.231265 Starting harvester: /usr/local/APP/logs/dailyShell.log
2013/09/05 23:28:37.531868 Registrar received 1000 events
2013/09/05 23:28:37.532050 Saving registrar state.
2013/09/05 23:28:38.651929 Registrar received 1000 events

Thanks
Luke

**Comment by jordansissel** [comment]
I tihnk this is fixed. Each file watch has a "dead time" after a file has been idle for a while. After that time, the file is closed. This setting is tunable.
