### ISSUE TITLE
Events shipped by lumberjack are agitated

### ISSUE THREAD

**Issue by Wolfsrudel** [elastic/logstash-forwarder#80]
See: https://logstash.jira.com/browse/LOGSTASH-1288

Jordan mentioned this could be a lumberjack issue.

**Comment by jordansissel** [comment]
Is this still an issue?

**Comment by ssotos** [comment]
Well, I'm still using 1.1.13, I didn't try installing a newer version again since the system is stable and I don't want to brake it.

**Comment by jordansissel** [comment]
In truth, I'm not sure I ever understood the reported problem. I haven't heard of anyone reporting it similar. Will close> We can reopen later if it's still a problem on a recent release of lsf/logstash.
