### ISSUE TITLE
Ability to exclude files

### ISSUE THREAD

**Issue by chrisarn** [elastic/logstash-forwarder#89]
It would be neat to be able to exclude files.

So one could do something like this:
 {
      "paths": [ 
        "/var/log/messages",
        "/var/log/*.log"
      ],
      "exclude": [
        "/var/log/uninteresting.log", 
        "/var/log/alotofjunk.log"
       ],
      "fields": { "type": "syslog" }
}

**Comment by hartfordfive** [comment]
Considering that I'll most likely need this functionality in the near future, I've started working on this feature.  Hopefully I'll have this completed and tested shortly!

**Comment by driskell** [comment]
I can see your commit and have a suggestion.

Use filepath.Match to check if a file name matches any exclude pattern.
http://golang.org/pkg/path/filepath/#Match

It'll save doing two deep directory listings (which I think glob does) and it'll prevent race condition where a file appears between generating excluded files list and then doing path glob.

**Comment by hartfordfive** [comment]
Thanks for that tip @driskell.  I hadn't considered that possibility of a race condition which will most likely happen at some point.  I've applied that modification locally and I'll test it shortly before I push the changes.

**Comment by wybczu** [comment]
:+1:

**Comment by brotbert** [comment]
:+1:

**Comment by goerge** [comment]
+1

**Comment by khoamisfit** [comment]
+1

**Comment by leedm777** [comment]
:+1:

**Comment by sshunt** [comment]
++

**Comment by phunqe** [comment]
Awesome addition, was just looking for this. Eagerly awaiting a merge :)

**Comment by mholmbergC** [comment]
+1

**Comment by nelsonauner** [comment]
:+1:

**Comment by rmoff** [comment]
It's worth noting that some simple exclusions can be done with a glob regex, detailed here https://blog.vladionescu.com/excluding-from-a-path-glob/

**Comment by hartfordfive** [comment]
@rmoff  Thanks for that example, I guess it can also be accomplished with that query.   Keep in mind if you have files that you don't want indexed or that aren't necessary, then they shouldn't be sent to Logstash to begin with.  No point in having unused data being processed by Logstash or stored by Elasticsearch.

**Comment by kylekrall** [comment]
+1

**Comment by jaynefox** [comment]
+1

**Comment by gibre** [comment]
big +1

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better!

Logstash-forwarder is going away and is replaced by https://github.com/elastic/filebeat/. If this is still an issue with filebeat, would you mind opening a ticket [there](https://github.com/elastic/filebeat/issues)?
