### ISSUE TITLE
Failed to tls handshake with logstash

### ISSUE THREAD

**Issue by ojohn** [elastic/logstash-forwarder#98]
I suddenly ran into the same issue as https://github.com/jordansissel/lumberjack/issues/69

...with having the same cert and private key installed on lumberjack-host and logstash-host

1. error message by lumberjack is:
----------

"Failed to tls handshake with logstash-host:9501 local error: protocol version not supported"

----------

2. error message by logstash is:
----------
```
"{:accept_error=><OpenSSL::SSL::SSLError: Received fatal alert: protocol_version>}"
"{:accept_error=><OpenSSL::SSL::SSLError: Received fatal alert: protocol_version>}"
```
----------

How can i check for correct TLS version being used? OpenSSL is 1.0.0-27 on both machines.

Logstash is 1.2.1

**Comment by jordansissel** [comment]
@ojohn OpenSSL library is not used by this project, so I dont think that's related :)

Is this still a problem? What version of java are you using?

**Comment by jordansissel** [comment]
Closing since no respose. We can open a new ticket if there are continued problems.
